mikro-orm/mikro-orm

- docs/cascading.md
- lib/EntityManager.ts
- lib/MikroORM.ts
- lib/decorators/ManyToMany.ts
- lib/decorators/ManyToOne.ts
- lib/decorators/OneToMany.ts
- lib/drivers/AbstractSqlDriver.ts
- lib/drivers/PostgreSqlDriver.ts
- lib/entity/EntityValidator.ts
- lib/entity/enums.ts
- lib/metadata/JavaScriptMetadataProvider.ts
- lib/metadata/MetadataDiscovery.ts
- lib/schema/SchemaGenerator.ts
- lib/unit-of-work/ChangeSetPersister.ts
- lib/unit-of-work/UnitOfWork.ts
- lib/utils/ValidationError.ts
- tests/EntityManager.mongo.test.ts
- tests/UnitOfWork.test.ts
This also renames UoW.addToIdentityMap() to UoW.merge().
Closes #16
> feat(core): implement Cascade.MERGE and Cascade.ALL

- .codeclimate.yml
- docs/cascading.md
- docs/defining-entities.md
- lib/decorators/OneToOne.ts
- lib/decorators/index.ts
- lib/entity/EntityAssigner.ts
- lib/entity/EntityLoader.ts
- lib/entity/enums.ts
- lib/hydration/ObjectHydrator.ts
- lib/index.ts
- lib/metadata/MetadataDiscovery.ts
- lib/metadata/MetadataValidator.ts
- lib/query/QueryBuilder.ts
- lib/query/QueryBuilderHelper.ts
- lib/schema/SchemaGenerator.ts
- lib/unit-of-work/ChangeSetComputer.ts
- lib/unit-of-work/UnitOfWork.ts
- tests/EntityManager.mysql.test.ts
- tests/QueryBuilder.test.ts
- tests/__snapshots__/SchemaGenerator.test.ts.snap
- tests/bootstrap.ts
- tests/decorators.test.ts
- tests/entities-sql/Book2.ts
- tests/entities-sql/FooBar2.ts
- tests/entities-sql/FooBaz2.ts
- tests/entities-sql/Test2.ts
- tests/entities-sql/index.ts
- tests/mysql-schema.sql
- tests/postgre-schema.sql
> feat(core): add @OneToOne decorator

- .codeclimate.yml
- lib/EntityManager.ts
- lib/entity/EntityRepository.ts
- lib/metadata/MetadataDiscovery.ts
- lib/query/QueryBuilder.ts
- lib/query/QueryBuilderHelper.ts
- tests/EntityRepository.test.ts
- tests/QueryBuilder.test.ts
> feat(query-builder): add support for `join()` and `leftJoin()`

- lib/decorators/Entity.ts
- lib/decorators/OneToMany.ts
- lib/decorators/OneToOne.ts
- lib/entity/Collection.ts
- lib/unit-of-work/ChangeSetComputer.ts
- lib/unit-of-work/UnitOfWork.ts
- tests/EntityManager.mongo.test.ts
- tests/entities-sql/FooBar2.ts
- tests/entities/Author.ts
- tests/entities/FooBar.ts
- tests/entities/FooBaz.ts
> feat(core): implement orphan removal

- .travis.yml
- lib/hydration/ObjectHydrator.ts
- lib/query/QueryBuilder.ts
- tests/EntityFactory.test.ts
- tests/RequestContext.test.ts
- tests/UnitOfWork.test.ts
- tests/Utils.test.ts
- yarn.lock
> fix(deps): update dependencies to support node 12

- docs/entity-manager.md
- docs/query-builder.md
- lib/EntityManager.ts
- lib/drivers/DatabaseDriver.ts
- lib/drivers/IDatabaseDriver.ts
- lib/drivers/MongoDriver.ts
- lib/entity/EntityRepository.ts
- tests/EntityManager.mysql.test.ts
> feat(core): add support for mapping raw DB results via EM.map()

- docs/lifecycle-hooks.md
- lib/decorators/Entity.ts
- lib/decorators/hooks.ts
- lib/entity/EntityFactory.ts
- lib/unit-of-work/UnitOfWork.ts
- tests/EntityManager.postgre.test.ts
- tests/entities-sql/Author2.ts
This hook is synchronous. It is fired after entity is created.
Closes #83
> feat(hooks): add onInit hook fired after entity is created

- lib/decorators/Entity.ts
- lib/decorators/Property.ts
- lib/entity/EntityAssigner.ts
- lib/entity/EntityTransformer.ts
- lib/hydration/ObjectHydrator.ts
- tests/EntityManager.mongo.test.ts
- tests/entities/Author.ts
> feat(hooks): add support for virtual property getters

- docs/collections.md
> Fix miss-type in collection docs

- lib/query/QueryBuilder.ts
- lib/query/QueryBuilderHelper.ts
- lib/query/SmartQueryHelper.ts
- tests/QueryBuilder.test.ts
> feat(sql): support multiple conditions in JOINs

- lib/decorators/Entity.ts
- lib/decorators/Property.ts
- lib/metadata/MetadataDiscovery.ts
- lib/metadata/MetadataStorage.ts
- lib/query/QueryBuilder.ts
- lib/query/QueryBuilderHelper.ts
- lib/schema/DatabaseSchema.ts
- lib/schema/DatabaseTable.ts
- lib/schema/EntityGenerator.ts
- lib/schema/MySqlSchemaHelper.ts
- lib/schema/PostgreSqlSchemaHelper.ts
- lib/schema/SchemaGenerator.ts
- lib/schema/SchemaHelper.ts
- lib/schema/SqliteSchemaHelper.ts
- lib/schema/index.ts
- lib/utils/Utils.ts
- tests/SchemaGenerator.test.ts
- tests/SchemaHelper.test.ts
- tests/__snapshots__/EntityGenerator.test.ts.snap
- tests/__snapshots__/SchemaGenerator.test.ts.snap
SchemaGenerator now offers `updateSchema` and `getUpdateSchemaSQL` methods.
> feat(schema): add basic schema update

- .codeclimate.yml
- lib/connections/MariaDbConnection.ts
- lib/drivers/MariaDbDriver.ts
- lib/utils/Configuration.ts
- package.json
- tests/EntityManager.mariadb.test.ts
- tests/bootstrap.ts
- yarn.lock
> feat(drivers): add support for MariaDB

- docs/index.md
(sorry i missed this, maybe there is some way to re-use the toc and the sidebar?)
> [docs] add postgres to toc

- docs/entity-manager.md
- docs/repositories.md
- lib/EntityManager.ts
- lib/entity/EntityRepository.ts
- lib/utils/Configuration.ts
- lib/utils/ValidationError.ts
- tests/EntityManager.mongo.test.ts
- tests/EntityRepository.test.ts
- tests/entities/Publisher.ts
> feat(core): add findOneOrFail method to entity manager and repository

- docs/installation.md
I noticed weird rendered output
> docs: declare correct type of codeblock

- docs/entity-manager.md
- docs/unit-of-work.md
- lib/drivers/AbstractSqlDriver.ts
- lib/drivers/DatabaseDriver.ts
- lib/entity/EntityLoader.ts
- lib/metadata/MetadataDiscovery.ts
- lib/query/CriteriaNode.ts
- lib/query/QueryBuilder.ts
- lib/query/QueryBuilderHelper.ts
- lib/utils/Utils.ts
- package.json
- tests/EntityManager.mariadb.test.ts
- tests/EntityManager.mysql.test.ts
- tests/EntityManager.postgre.test.ts
- tests/EntityManager.sqlite.test.ts
- tests/QueryBuilder.test.ts
Refactor handling of where/having/orderBy criteria to CriteriaNode helper that allows better control over deeply nested structures.
Closes #172
> feat(core): add support for deep nested conditions with operators

- CONTRIBUTING.md
- scripts/database_setup.sh
- tests/scripts/database_setup.sh
Signed-off-by: Ranvir Singh <ranvir.singh1114@gmail.com>
> docs: add database creation guide to CONTRIBUTION file

- docs/upgrading-v2-to-v3.md
- lib/connections/MongoConnection.ts
- package.json
- tests/EntityManager.mongo.test.ts
- yarn.lock
> chore: update mongodb to 3.3 and use new unified topology

- lib/drivers/AbstractSqlDriver.ts
- tests/issues/GH268.test.ts
> fix(sql): support uuid like PKs in M:N references

- docs/docs/migrations.md
Fixed grammar and wording for migrations and transactions.
> docs: Update migrations.md

- docs/docs/entity-generator.md
- lib/schema/EntityGenerator.ts
- tests/__snapshots__/EntityGenerator.test.ts.snap
Please let me know if there is a reason for this behaviour, and I can close or update PR.
> fix: add TS non-null assertion operator for non-nullable columns

- docs/docs/decorators.md
- docs/docs/defining-entities.md
- lib/MikroORM.ts
- lib/decorators/Indexed.ts
- lib/decorators/Property.ts
- lib/decorators/index.ts
- lib/metadata/MetadataDiscovery.ts
- lib/metadata/MetadataStorage.ts
- lib/schema/SchemaGenerator.ts
- lib/schema/SchemaHelper.ts
- lib/typings.ts
- lib/utils/Utils.ts
- tests/MikroORM.test.ts
- tests/SchemaGenerator.test.ts
- tests/__snapshots__/SchemaGenerator.test.ts.snap
- tests/entities-sql/Author2.ts
- tests/mysql-schema.sql
- tests/postgre-schema.sql
Closes #328, Original PR: #226
> feat(sql): add @Index() and @Unique() decorators

- lib/entity/EntityRepository.ts
Closes https://github.com/mikro-orm/mikro-orm/issues/342
> fix(typing): align EntityRepository populate signature to EntityManager

- docs/docs/collections.md
- lib/entity/Collection.ts
Sugar for await init() and getItems()
Closes https://github.com/mikro-orm/mikro-orm/issues/346
> feat(core): add loadItems() method to Collection

- docs/docs/defining-entities.md
- docs/versioned_docs/version-3.0/defining-entities.md
- docs/versioned_docs/version-3.1/defining-entities.md
- docs/versioned_docs/version-3.2/defining-entities.md
- docs/versioned_docs/version-3.3/defining-entities.md
- lib/schema/PostgreSqlSchemaHelper.ts
- lib/schema/SchemaHelper.ts
- tests/issues/GH369.test.ts
- tests/issues/GH380.test.ts
> fix(core): improve default value handling in postgres

- tests/entities-sql/Author2.ts
It fixes failing master branch. See https://github.com/mikro-orm/mikro-orm/pull/373/checks?check_run_id=490535503
> fix: default property value

- docs/docs/defining-entities.md
- docs/docs/using-bigint-pks.md
- docs/sidebars.js
- lib/connections/MySqlConnection.ts
- lib/entity/EntityAssigner.ts
- lib/metadata/MetadataDiscovery.ts
- lib/platforms/Platform.ts
- lib/platforms/PostgreSqlPlatform.ts
- lib/query/QueryBuilder.ts
- lib/schema/DatabaseTable.ts
- lib/schema/MySqlSchemaHelper.ts
- lib/schema/PostgreSqlSchemaHelper.ts
- lib/schema/SchemaGenerator.ts
- lib/types/BigIntType.ts
- lib/types/index.ts
- lib/typings.ts
- package.json
- tests/EntityHelper.mongo.test.ts
- tests/EntityManager.mysql.test.ts
- tests/EntityManager.postgre.test.ts
- tests/SchemaGenerator.test.ts
- tests/__snapshots__/EntityGenerator.test.ts.snap
- tests/__snapshots__/SchemaGenerator.test.ts.snap
- tests/entities-sql/BookTag2.ts
- tests/mysql-schema.sql
- tests/postgre-schema.sql
- tests/types.test.ts
- yarn.lock
Adds BigIntType custom type that can be used to handle bigints.
Closes #361
> feat(sql): add support for bigint

- docs/docs/migrations.md
This needs to be adapted to find .js files, thus should also be
documented.
> Add migration pattern to the documentation

- lib/drivers/MongoDriver.ts
- lib/metadata/MetadataDiscovery.ts
- lib/schema/DatabaseTable.ts
- lib/schema/EntityGenerator.ts
- lib/schema/EntitySchema.ts
- lib/schema/MySqlSchemaHelper.ts
- lib/schema/PostgreSqlSchemaHelper.ts
- lib/schema/SchemaGenerator.ts
- lib/schema/SchemaHelper.ts
- lib/schema/SqliteSchemaHelper.ts
- tests/EntityGenerator.test.ts
- tests/__snapshots__/EntityGenerator.test.ts.snap
- tests/__snapshots__/SchemaGenerator.test.ts.snap
- tests/composite-keys.mysql.test.ts
- tests/entities-sql/Address2.ts
- tests/entities-sql/Car2.ts
- tests/entities-sql/CarOwner2.ts
- tests/mysql-schema.sql
- tests/postgre-schema.sql
> feat(core): support indexes in entity generator

- docker-compose.yml
- lib/schema/MySqlSchemaHelper.ts
- lib/schema/SchemaHelper.ts
- tests/bootstrap.ts
- tests/issues/GH491.test.ts
> fix(mariadb): fix diffing nullable columns in mariadb 10.4

- lib/schema/SchemaGenerator.ts
- lib/schema/SchemaHelper.ts
- tests/SchemaGenerator.test.ts
- tests/__snapshots__/SchemaGenerator.test.ts.snap
> fix(schema): fix handling of FKs in updateSchema()

- lib/schema/SchemaHelper.ts
- tests/__snapshots__/SchemaGenerator.test.ts.snap
- tests/entities-sql/Author2.ts
> fix(schema): improve diffing of nullable columns

- docs/docs/usage-with-sql.md
(sorry, didn't realize this was the right folder)
> [docs] small grammar change

- lib/query/QueryBuilder.ts
- tests/issues/GH519.test.ts
> fix(core): fix qb.count() with composite keys

- .github/workflows/tests.yml
- tests/FileCacheAdapter.test.ts
> feat(core): add support for Node.js 14

- lib/utils/Utils.ts
- tests/issues/GH535.test.ts
> fix(core): avoid evaluating virtual properties on find

- lib/unit-of-work/ChangeSetPersister.ts
- tests/issues/GH560.test.ts
> fix(core): propagate PKs created via `prop.onCreate`

- lib/utils/RequestContext.ts
> fix(core): do not extend domain typings (collides with sentry)

- lib/schema/EntitySchema.ts
- tests/issues/GH557.test.ts
> fix(mapping): fix handling of fieldName vs joinColumn in m:1/1:1

- packages/knex/src/AbstractSqlDriver.ts
- tests/MikroORM.test.ts
- tests/__snapshots__/EntityGenerator.test.ts.snap
- tests/__snapshots__/SchemaGenerator.test.ts.snap
- tests/bootstrap.ts
- tests/composite-keys.mysql.test.ts
- tests/entities-sql/User2.ts
- tests/entities-sql/index.ts
- tests/entities-sql/sandwich.ts
- tests/mysql-schema.sql
when populating m:n relation in some cases was error, where wrong metadata used to check is there composite PK involved in query, which caused some cryptic errors
> fix(mapping): support mixed M:N with composite PK on one side only

- packages/core/src/EntityManager.ts
- packages/core/src/drivers/IDatabaseDriver.ts
- packages/core/src/entity/EntityLoader.ts
- packages/knex/src/AbstractSqlDriver.ts
- packages/knex/src/query/QueryBuilder.ts
- tests/EntityManager.mysql.test.ts
- tests/joined-strategy.postgre.test.ts
> refactor: finalize support for joined strategy

- packages/core/src/utils/Utils.ts
- tests/issues/GH603.test.ts
> fix(core): allow date to be used as primary key

- tests/embedded-entities.mysql.test.ts
Fix expected and received values in embedded entities mysql test.
> test: fix load embedded entities mysql test

- docs/versioned_docs/version-3.6/custom-driver.md
> docs: update custom driver section

- packages/core/src/entity/EntityAssigner.ts
- packages/core/src/entity/EntityLoader.ts
- packages/core/src/entity/Reference.ts
- packages/core/src/unit-of-work/UnitOfWork.ts
- packages/core/src/utils/QueryHelper.ts
I think this completely fixes #676. Thanks for bearing with me.
> refactor: test for Reference via __reference instead of instanceof #679

- docs/docs/configuration.md
- docs/docs/installation.md
Cli output now reflects the current state again.
Also before it was unclear how to import multiline dump files.
> docs: update cli output and describe importing sql dump files

- docs/docs/installation.md
The postgres package is @mikro-orm/postgresql:  https://www.npmjs.com/package/@mikro-orm/postgresql
> docs: correct postgresql package name

- packages/core/src/decorators/Entity.ts
- packages/core/src/typings.ts
- packages/core/src/unit-of-work/ChangeSetComputer.ts
- tests/UnitOfWork.test.ts
- tests/__snapshots__/EntityGenerator.test.ts.snap
- tests/__snapshots__/SchemaGenerator.test.ts.snap
- tests/entities-sql/Dummy2.ts
- tests/entities/Dummy.ts
- tests/mysql-schema.sql
> feat(core): readonly entity

- README.md
- docs/docs/index.md
> feat: added graphql example

- packages/knex/src/query/QueryBuilderHelper.ts
- tests/QueryBuilder.test.ts
Fix for https://github.com/mikro-orm/mikro-orm/issues/792
> fix(query-builder): make sure `$or` and `$and` combined works correctly

- packages/knex/src/query/QueryBuilderHelper.ts
- tests/QueryBuilder.test.ts
> fix(query-builder): use correct operators in complex and/or conditions

- packages/core/src/entity/EntityFactory.ts
- packages/core/src/hydration/Hydrator.ts
- packages/core/src/metadata/MetadataDiscovery.ts
- packages/core/src/typings.ts
- tests/entities-sql/BaseUser2.ts
- tests/single-table-inheritance.mysql.test.ts
> fix(core): hydrate user defined discriminator columns

- docs/docs/usage-with-nestjs.md
> docs(nestjs): update reference to old package

- packages/core/src/metadata/MetadataDiscovery.ts
> fix(core): skip index initialization for abstract entities

- docs/docs/inheritance-mapping.md
For reference: https://mikroorm.slack.com/archives/CFSAF8DEX/p1601905449127700
> docs: fix the explicit discriminator column example

- docs/docs/repositories.md
- docs/versioned_docs/version-4.0/repositories.md
- docs/versioned_docs/version-4.1/repositories.md
My fork was behind, reopened for 4.1
> docs: add note on circular dependencies

- packages/migrations/src/Migrator.ts
https://github.com/mikro-orm/mikro-orm/issues/907#issuecomment-713532649
> fix: only create migrations folder if migrationsList is not used

- docs/docs/filters.md
- packages/core/src/utils/Configuration.ts
- tests/MikroORM.test.ts
Add documentation for all parameters and describe when global filters
are default enabled or not
> fix(core): ensure global filters are enabled by default

- docs/docs/caching.md
- docs/versioned_docs/version-4.2/caching.md
> docs: fix typo

- docs/docs/defining-entities.md
- docs/versioned_docs/version-4.2/defining-entities.md
> docs: add example of nullable string enum definition

- packages/knex/src/AbstractSqlConnection.ts
- tests/issues/GH1176.test.ts
> fix(knex): reject in `commit()` method if commit statement fails

- packages/core/src/hydration/ObjectHydrator.ts
- tests/__snapshots__/embedded-entities.postgres.test.ts.snap
- tests/embedded-entities.mongo.test.ts
- tests/embedded-entities.postgres.test.ts
- tests/issues/GH1191.test.ts
- tests/issues/__snapshots__/GH1191.test.ts.snap
This PR fixes the issue with embeddables not having their inner properties hydrated properly.
fixes #1191
> fix(core): hydrate embeddable scalar properties

- packages/core/src/entity/ArrayCollection.ts
- tests/issues/GH1224.test.ts
> fix(core): support FK as PK in `Collection.getIdentifiers()`

- docs/package.json
- docs/yarn.lock
Reverts mikro-orm/mikro-orm#1243
> Revert "chore(deps): update dependency typedoc to v0.20.1"

- docs/docs/query-builder.md
- docs/versioned_docs/version-4.4/query-builder.md
I found this example in tests particularly helpful.
> docs: add additional sub-query example

- packages/migrations/package.json
> chore(deps): add knex to migrations package

- .codeclimate.yml
- docker-compose.yml
- docs/docs/embeddables.md
- packages/core/src/decorators/Embedded.ts
- packages/core/src/hydration/ObjectHydrator.ts
- packages/core/src/metadata/EntitySchema.ts
- packages/core/src/metadata/MetadataDiscovery.ts
- packages/core/src/platforms/Platform.ts
- packages/core/src/utils/EntityComparator.ts
- packages/knex/src/AbstractSqlPlatform.ts
- packages/knex/src/query/QueryBuilderHelper.ts
- tests/__snapshots__/embedded-entities.postgres.test.ts.snap
- tests/__snapshots__/nested-embeddables.mongo.test.ts.snap
- tests/__snapshots__/nested-embeddables.postgres.test.ts.snap
- tests/embedded-entities.mongo.test.ts
- tests/embedded-entities.postgres.test.ts
- tests/nested-embeddables.postgres.test.ts
```ts
@Embedded(() => Address, { array: true })
addresses: Address[] = [];
```
Closes #1369
> feat(core): support embeddable arrays

- docs/docs/migrations.md
- docs/versioned_docs/version-3.6/migrations.md
- docs/versioned_docs/version-4.0/migrations.md
- docs/versioned_docs/version-4.1/migrations.md
- docs/versioned_docs/version-4.2/migrations.md
- docs/versioned_docs/version-4.3/migrations.md
- docs/versioned_docs/version-4.4/migrations.md
Fixes documentation that explains how to use migrator to migrate
up to a specific migration
> docs: update migration docs

- docs/docs/cascading.md
Remove a duplicated example (the last one is exactly the same).
> docs: update cascading example

- docs/docs/usage-with-nestjs.md
- docs/docs/usage-with-sql.md
- docs/versioned_docs/version-4.0/usage-with-sql.md
- docs/versioned_docs/version-4.1/usage-with-sql.md
- docs/versioned_docs/version-4.2/usage-with-sql.md
- docs/versioned_docs/version-4.3/usage-with-sql.md
- docs/versioned_docs/version-4.4/usage-with-nestjs.md
- docs/versioned_docs/version-4.4/usage-with-sql.md
After the docs are improved I'll upload the same to docs.nestjs.com repo so MikroORM is represented there as well. Hopefully more people will then make the right call.
> docs: improve nestjs integration docs

- docs/docs/usage-with-nestjs.md
- docs/versioned_docs/version-4.5/usage-with-nestjs.md
Fixes: https://github.com/mikro-orm/nestjs/issues/22
> docs: add a section on using MikroORM in NestJS with GraphQL

- docs/docs/custom-types.md
> docs: update custom-types.md

- packages/core/src/utils/ConfigurationLoader.ts
- tests/features/cli/CLIHelper.test.ts
> fix(core): support extending in `tsconfig.json`

- tests/features/migrations/Migrator.test.ts
- tests/features/migrations/__snapshots__/Migrator.test.ts.snap
Pulling out unrelated changes from the multi-schema PR.
This basically just made it easier for me to follow exactly what part of the test was broken.
> test(migrator): split one large test case into several smaller ones

- packages/knex/src/schema/SchemaHelper.ts
- packages/mysql-base/src/MySqlSchemaHelper.ts
- packages/postgresql/src/PostgreSqlSchemaHelper.ts
Another small change from multi-schema support PR.
> refactor: extract methods for disabling FKs

- packages/core/src/utils/ConfigurationLoader.ts
- tests/features/cli/CLIHelper.test.ts
This way the extended property of the tsconfig file can be read
property.
Fixes #1849
> fix(core): use tsconfig-paths loadConfig function

- docs/docs/embeddables.md
- packages/core/src/entity/EntityHelper.ts
- packages/core/src/entity/EntityLoader.ts
- packages/core/src/entity/WrappedEntity.ts
- packages/core/src/hydration/ObjectHydrator.ts
- packages/core/src/metadata/MetadataStorage.ts
- packages/core/src/platforms/Platform.ts
- packages/core/src/unit-of-work/ChangeSetComputer.ts
- packages/core/src/unit-of-work/ChangeSetPersister.ts
- packages/core/src/unit-of-work/UnitOfWork.ts
- packages/core/src/utils/EntityComparator.ts
- packages/core/src/utils/Utils.ts
- packages/knex/src/AbstractSqlPlatform.ts
- packages/knex/src/schema/SchemaComparator.ts
- packages/mongodb/src/MongoPlatform.ts
- packages/postgresql/src/PostgreSqlPlatform.ts
- packages/sqlite/src/SqlitePlatform.ts
- tests/features/embeddables/__snapshots__/entities-in-embeddables.mongo.test.ts.snap
- tests/features/embeddables/__snapshots__/entities-in-embeddables.postgres.test.ts.snap
- tests/features/embeddables/entities-in-embeddables.mongo.test.ts
- tests/features/embeddables/entities-in-embeddables.postgres.test.ts
> feat(embeddables): allow using m:1 properties inside embeddables

- docs/docs/identity-map.md
> docs: incorrect spelling in identity map

- packages/core/src/index.ts
Fixes https://github.com/mikro-orm/mikro-orm/issues/2284
> chore: export EntityClass from root

- docs/docs/configuration.md
- docs/docs/seeding.md
- packages/cli/src/commands/CreateSeederCommand.ts
- packages/core/src/utils/ConfigurationLoader.ts
> refactor: fix cli seeder generate and add seeder env vars

- packages/core/src/metadata/ReflectMetadataProvider.ts
- packages/mongodb/src/MongoConnection.ts
- tests/bootstrap.ts
Only cherry-picking the non-conflicting commits with the type `fix`
> 4.x cherry picking

- packages/knex/src/query/QueryBuilderHelper.ts
- tests/issues/GH2401.test.ts
> fix(knex): quote version column

- docs/docs/faq.md
- docs/versioned_docs/version-4.5/faq.md
Address comment about `useDefineForClassFields` from #1984
> Update FAQ to reflect #1984

- docs/docs/defining-entities.md
- docs/versioned_docs/version-4.5/defining-entities.md
Suggest edit to entities definition in docs
> docs: Update defining-entities.md

- docs/docs/decorators.md
- docs/docs/entity-manager.md
- packages/core/src/decorators/Property.ts
- packages/core/src/platforms/Platform.ts
- packages/core/src/typings.ts
- packages/knex/src/AbstractSqlPlatform.ts
- packages/knex/src/query/QueryBuilderHelper.ts
- tests/EntityManager.mongo.test.ts
- tests/features/custom-order/custom-order.mysql.test.ts
- tests/features/custom-order/custom-order.postgres.test.ts
- tests/features/custom-order/custom-order.sqlite.test.ts
Related: https://github.com/mikro-orm/mikro-orm/discussions/2178
> feat(core): add support for custom property ordering

- docs/versioned_docs/version-4.5/inheritance-mapping.md
Small tweak to make the sentence more grammatically correct.
> docs: improve grammar

- packages/core/src/index.ts
contributes to https://github.com/nextauthjs/adapters/pull/335/files#r765957397
> refactor: expose `EntityClassGroup` type

- docs/docs/lifecycle-hooks.md
This just adds a basic description of transaction events to the docs.
> docs(core): add transaction events detail

- packages/core/src/utils/QueryHelper.ts
- packages/knex/src/query/ObjectCriteriaNode.ts
- tests/issues/GH2648.test.ts
Some tests are broken but at least the cases of #2649 are working as expected. Both changes break tests separately and i only have a rough idea why.
@B4nan I try to improve this fix tomorrow, but i'm missing insight.
> fix(core): fix nested query with fk as pk

- packages/core/src/platforms/Platform.ts
- tests/issues/GH2663.test.ts
> fix(core): fix missing embedded columns on joined select query

- packages/core/src/entity/EntityLoader.ts
- tests/issues/GH2675.test.ts
Closes [#2675](https://github.com/mikro-orm/mikro-orm/issues/2675) issue.
> fix(core): respect specified schema when populating (select-in)

- docs/docs/identity-map.md
fix asynclocalstorage docs link url in docs.
> docs: fix asynclocalstorage docs url

- packages/core/src/utils/Utils.ts
- tests/Utils.test.ts
> fix(core): fix object key utilities for null prototype objects

- docs/versioned_docs/version-5.0/usage-with-nestjs.md
See : 
https://github.com/mikro-orm/nestjs/pull/66
https://github.com/mikro-orm/nestjs/discussions/65
> docs: add a caveat about serialization 1/2

- docs/docs/usage-with-nestjs.md
See  :
- https://github.com/mikro-orm/nestjs/pull/66
- https://github.com/mikro-orm/nestjs/discussions/65
> docs: add a caveat about serialization 2/2

- packages/core/src/decorators/ManyToMany.ts
- packages/core/src/drivers/DatabaseDriver.ts
- packages/core/src/metadata/MetadataDiscovery.ts
- packages/core/src/metadata/MetadataStorage.ts
- packages/core/src/typings.ts
- packages/core/src/unit-of-work/CommitOrderCalculator.ts
- packages/knex/src/AbstractSqlDriver.ts
- packages/knex/src/query/QueryBuilder.ts
- packages/knex/src/query/QueryBuilderHelper.ts
- tests/EntityManager.sqlite2.test.ts
- tests/features/composite-keys/__snapshots__/custom-pivot-entity.sqlite.test.ts.snap
- tests/features/composite-keys/custom-pivot-entity.sqlite.test.ts
```ts
@ManyToMany({ entity: () => Product, pivotEntity: () => OrderItem })
products = new Collection<Product>(this);
```
> feat(core): allow specifying custom pivot table entity

- packages/core/src/metadata/MetadataDiscovery.ts
I haven't created a bug ticket for this, but I did explain the problem in [this Slack thread](https://mikroorm.slack.com/archives/CFTFEK39D/p1651689602208229).
> fix(core): improve validation of wrong entity references

- packages/knex/src/query/ObjectCriteriaNode.ts
- tests/EntityManager.mysql.test.ts
> fix(core): fix aliasing of formula properties in complex conditions

- packages/core/src/hydration/ObjectHydrator.ts
- tests/features/embeddables/GH3134.test.ts
- tests/features/embeddables/__snapshots__/entities-in-embeddables.mongo.test.ts.snap
- tests/features/embeddables/__snapshots__/entities-in-embeddables.postgres.test.ts.snap
- tests/features/embeddables/__snapshots__/polymorphic-embedded-entities.sqlite.test.ts.snap
As proposed in https://github.com/mikro-orm/mikro-orm/issues/3134#issuecomment-1133862820
Updated snapshots using `yarn test -u`
> fix(core): assign new embeddable entity only when it is null or undefined

- packages/seeder/package.json
> fix(seeder): fs-extra dep

- docs/docs/metadata-providers.md
> fix: docs typo

- packages/knex/src/query/ObjectCriteriaNode.ts
- tests/issues/GH3301.test.ts
> fix(knex): fix $or over 1:m and m:1 auto-joined relations

- packages/knex/src/schema/SchemaGenerator.ts
- packages/knex/src/schema/SchemaHelper.ts
- tests/issues/GH3339.test.ts
> fix(schema): respect schema when renaming columns in postgres

- jest.config.ts
- packages/core/src/entity/ArrayCollection.ts
- packages/core/src/entity/Collection.ts
- packages/core/src/logging/SimpleLogger.ts
- packages/core/src/platforms/Platform.ts
- packages/core/src/utils/Utils.ts
- packages/knex/src/query/QueryBuilderHelper.ts
- packages/postgresql/src/PostgreSqlPlatform.ts
- tests/QueryBuilder.test.ts
- tests/features/schema-generator/SchemaGenerator.mysql.test.ts
- tests/issues/GH1003.test.ts
> fix(query-builder): support top level `$not` operator in join condition

- packages/core/src/entity/EntityAssigner.ts
- packages/core/src/entity/EntityFactory.ts
- packages/core/src/utils/Utils.ts
- tests/features/composite-keys/GH3599.test.ts
> fix(core): fix assigning objects to collections

- docs/docs/installation.md
Hello
I'm going through reading the docs line by line, and found this sentence could be better with this fix.
Thanks for your work ,B4nan!
Joy
> docs: fix grammatical error

- docs/docs/usage-with-nestjs.md
- docs/versioned_docs/version-4.5/lifecycle-hooks.md
- docs/versioned_docs/version-4.5/usage-with-nestjs.md
- docs/versioned_docs/version-5.4/usage-with-nestjs.md
- docs/versioned_docs/version-5.5/usage-with-nestjs.md
Added a note since other variants didn't work in NestJS
Ref: https://github.com/mikro-orm/nestjs/issues/14
> docs: note about usage with NestJS for lifecycle subscriber

- docs/docs/identity-map.md
Found this sentence will be better with this fix. :)
> docs: fix-grammar-error

- docs/docs/entity-manager.md
While reading the docs, I thought this example will be better with result comments. :)
> docs: add example result comment

- docs/docs/defining-entities.md
valued -> values
is -> in the
reexport -> re-export
> fix(docs): fixes a typo

- .yarnrc.yml
- docs/docs/query-builder.md
- docs/versioned_docs/version-5.5/query-builder.md
Hi,
Fixed a comment and added result in comment.
Thanks! 🤓
Joy
> docs: fix-comment

- packages/core/src/entity/Collection.ts
> fix(core): allow adding array of refs to collection

- packages/cli/src/CLIHelper.ts
- packages/cli/src/commands/DebugCommand.ts
- tests/features/cli/CLIHelper.test.ts
- tests/features/cli/CreateDatabaseCommand.test.ts
- tests/features/cli/DebugCommand.test.ts
Hi,
Even though @liang799 did his nice [PR work ](https://github.com/mikro-orm/mikro-orm/pull/3874), I tried mine, too 😹. As I knew we already have PR, I just want to get a review if it is okay. 
While working with this PR, I wanted to ask a question. Is it okay to fix existing test? As I added information to dump, it crashed with existing test. So I fixed them test but doesn't feel right.. 👀.. 
Thank you!
> feat(cli): check database connection in debug command

- packages/core/src/entity/EntityHelper.ts
- tests/issues/GH2371.test.ts
> fix(core): propagate ManyToOne only to matching collections (STI)

- docs/docs/relationships.md
This adds the documentation for usage of `Rel` wrapper for avoiding circular dependencies mostly on esm projects
> doc: add usage for Rel wrapper

- packages/core/src/entity/Collection.ts
- tests/features/load-count-where.test.ts
- tests/issues/GH3527.test.ts
> feat(core): allow filtering in `Collection.loadCount()`

- packages/core/src/utils/Configuration.ts
- packages/migrations-mongodb/src/Migrator.ts
- packages/migrations/src/Migrator.ts
- tests/features/migrations/Migrator.test.ts
- tests/features/migrations/__snapshots__/Migrator.test.ts.snap
In case @stabai doesn't reply, I'd like to submit my PR.
Closes #4005
> feat(migrations): add `cjs` option for emit

- packages/core/src/typings.ts
- packages/knex/src/query/QueryBuilder.ts
- packages/knex/src/typings.ts
- tests/features/paginate-flag.postgres.test.ts
- tests/issues/GH3871.test.ts
> fix(core): use `join on` conditions for `populateWhere`

- packages/mongodb/src/MongoDriver.ts
- tests/issues/GH4065.test.ts
> fix(mongo): move $fulltext from $and to top level

- packages/core/src/metadata/EntitySchema.ts
- packages/core/src/metadata/MetadataDiscovery.ts
- packages/core/src/platforms/Platform.ts
- packages/core/src/types/JsonType.ts
- packages/core/src/typings.ts
- packages/knex/src/AbstractSqlDriver.ts
- packages/knex/src/query/CriteriaNode.ts
- packages/knex/src/query/CriteriaNodeFactory.ts
- packages/knex/src/query/QueryBuilder.ts
- packages/knex/src/query/QueryBuilderHelper.ts
- packages/knex/src/typings.ts
- packages/mariadb/src/MariaDbConnection.ts
- packages/postgresql/src/PostgreSqlPlatform.ts
- tests/EntityManager.sqlite2.test.ts
- tests/features/custom-types/json-properties.test.ts
- tests/features/embeddables/embedded-entities.postgres.test.ts
- tests/features/embeddables/entities-in-embeddables.postgres.test.ts
- tests/features/embeddables/nested-embeddables.postgres.test.ts
> fix(core): detect `JsonType` based on `columnType`

- packages/core/src/EntityManager.ts
- packages/knex/src/AbstractSqlDriver.ts
- tests/features/upsert/GH4242-2.test.ts
- tests/features/upsert/GH4242.test.ts
- tests/features/upsert/__snapshots__/upsert.test.ts.snap
> fix(core): ensure `em.upsert` returns initialized entity

- packages/cli/src/CLIConfigurator.ts
- packages/cli/src/commands/MigrationCommandFactory.ts
- tests/features/cli/CLIHelper.test.ts
Please let me know if you want me to make any changes. Feel free to make edits to the branch directly if you prefer that.
> fix(cli): expose missing `migration:check` command

- packages/core/src/drivers/DatabaseDriver.ts
- packages/core/src/entity/EntityValidator.ts
- packages/core/src/logging/DefaultLogger.ts
- packages/core/src/metadata/MetadataDiscovery.ts
- packages/core/src/typings.ts
- packages/knex/src/AbstractSqlDriver.ts
- packages/knex/src/query/QueryBuilder.ts
- packages/knex/src/query/QueryBuilderHelper.ts
- tests/EntityManager.mysql.test.ts
- tests/QueryBuilder.test.ts
- tests/features/partial-loading/partial-loading.mysql.test.ts
- tests/features/single-table-inheritance/GH4422.test.ts
- tests/features/single-table-inheritance/GH4423.test.ts
- tests/issues/GH234.test.ts
> fix(core): rework pivot table joining

- docs/docs/events.md
- docs/versioned_docs/version-5.7/events.md
EventArgs is updated to FlushEventArgs where flush events are used.
> docs: improve events section

- packages/knex/src/query/QueryBuilderHelper.ts
- tests/issues/GH4472.test.ts
When both tables have wildcard schema, join not use the correct schema.
Closes #4472
> fix(sql): schema not inherited in query with relations

- docs/docs/usage-with-sql.md
- docs/versioned_docs/version-5.7/usage-with-sql.md
> docs: Add instructions for using sqlite extensions

- docs/docs/collections.md
- packages/core/src/entity/ArrayCollection.ts
- packages/core/src/entity/Collection.ts
- tests/EntityManager.mongo.test.ts
- tests/EntityManager.mysql.test.ts
- tests/EntityManager.postgre.test.ts
- tests/EntityManager.sqlite.test.ts
- tests/EntityManager.sqlite2.test.ts
- tests/features/composite-keys/custom-pivot-entity-auto-discovery.sqlite.test.ts
- tests/features/composite-keys/custom-pivot-entity-fixed-order.sqlite.test.ts
- tests/features/composite-keys/custom-pivot-entity-uni.sqlite.test.ts
- tests/features/composite-keys/custom-pivot-entity-wrong-order.sqlite.test.ts
- tests/features/composite-keys/custom-pivot-entity.sqlite.test.ts
Adds the isExists which returns either true false based on the collection count same as doctrine
> feat(core): add `Collection.isEmpty()` method

- packages/core/src/metadata/MetadataDiscovery.ts
- packages/core/src/metadata/MetadataValidator.ts
- tests/features/embeddables/__snapshots__/nested-embeddables.postgres.test.ts.snap
- tests/features/embeddables/nested-embeddables.postgres.test.ts
> fix(core): respect `@Index` and `@Unique` decorators on embeddables

- packages/core/src/unit-of-work/ChangeSet.ts
- tests/issues/GH4720.test.ts
> fix(core): fix updating complex composite key entities via UoW

- packages/core/src/metadata/MetadataDiscovery.ts
- packages/core/src/unit-of-work/ChangeSetComputer.ts
- packages/core/src/unit-of-work/UnitOfWork.ts
- packages/knex/src/AbstractSqlDriver.ts
- packages/knex/src/schema/DatabaseTable.ts
- tests/features/single-table-inheritance/GH2388.test.ts
- tests/features/single-table-inheritance/single-table-inheritance.mysql.test.ts
> feat(core): support mapping one column to different STI properties

- packages/core/src/metadata/EntitySchema.ts
> chore(core): export schema types

- packages/core/src/serialization/EntitySerializer.ts
- packages/core/src/serialization/EntityTransformer.ts
- tests/features/serialization/GH4859.test.ts
Fixes https://github.com/mikro-orm/mikro-orm/issues/4859
> fix(serialization): run custom serializer on getters

- .github/ISSUE_TEMPLATE/bug_report.yml
- CONTRIBUTING.md
> docs: add new issue template

- docs/docs/entity-manager.md
- packages/core/src/EntityManager.ts
- packages/core/src/drivers/IDatabaseDriver.ts
- packages/core/src/entity/EntityRepository.ts
- tests/EntityManager.postgre.test.ts
```ts
const books = await em.findAll(Book, {
where: { publisher: { $ne: null } }, // optional
populate: ['author.friends'],
});
```
Related: #3982
> feat(core): add `em.findAll()` with optional `where` option

- docs/docs/property-validation.md
The code provided was not copy pastable, T was not defined
> docs: property-validation.md

- docs/docs/faq.md
- packages/core/src/MikroORM.ts
- packages/core/src/connections/Connection.ts
- packages/knex/src/AbstractSqlConnection.ts
- packages/mongodb/src/MongoConnection.ts
- tests/Connection.test.ts
- tests/EntityManager.mariadb.test.ts
- tests/EntityManager.mongo2.test.ts
- tests/EntityManager.mysql.test.ts
- tests/EntityManager.postgre.test.ts
- tests/EntityManager.sqlite2.test.ts
- tests/features/reusing-mongo-client.test.ts
```ts
// boolean
const isConnected = await orm.isConnected();
// object with `ok`, `reason` and `error` keys
const check = await orm.checkConnection();
console.log(check.ok, check.reason);
```
Closes #4959
> feat(core): add `orm.checkConnection()` helper

- packages/core/src/EntityManager.ts
- packages/core/src/entity/Collection.ts
- packages/core/src/entity/Reference.ts
- packages/core/src/utils/DataloaderUtils.ts
- tests/features/__snapshots__/dataloader.test.ts.snap
- tests/features/dataloader.test.ts
- tests/issues/GH4977.test.ts
- tests/issues/__snapshots__/GH4977.test.ts.snap
It's mostly done and tests are passing but I'm marking this as draft until I add more tests for filters and options with the Collection dataloader.
> Fixes Reference.load(), Collection.loadItems(), dataloader enabling logic. Dataloaders honor options and filters.

- docs/docs/migrations.md
- docs/docs/seeding.md
- docs/versioned_docs/version-6.0/migrations.md
- docs/versioned_docs/version-6.0/seeding.md
Related to the changes added in #5087 (702409298214904ebac6b6e73455c3fb6fdf89e4)
> docs: fix typos

- tests/features/result-cache/result-cache.mongo.test.ts
Although merely replacing 
```ts
await new Promise(r => setTimeout(r, 100)); // wait for cache to expire
```
with
```ts
jest.advanceTimersByTime(100); // wait for cache to expire
```
did the job too, I thought I keep the test a bit more realistic by advancing time between the find calls.
This approach also implicitly tests something else I wasn't sure about... Running a second find() with a cache option does not re-vitalize the cache to add 50ms on top of the current time (which at this point is 25ms forward), so as soon as 51ms passed after the first find(), there's already a cache miss.
If this behavior changes, the test would show it.
> test(result-cache): fixed flaky Mongo result cache test by using fake timers

- packages/core/src/EntityManager.ts
> fix(core): ensure `em.insertMany` returns array of PKs for a single item too

- packages/core/src/cache/CacheAdapter.ts
> fix(core): allow `CacheAdapter.get` to return `Promise<undefined>`

- docs/docs/entity-generator.md
- docs/versioned_docs/version-6.0/entity-generator.md
- packages/core/src/index.ts
- packages/core/src/metadata/EntitySchema.ts
- packages/core/src/typings.ts
- packages/core/src/utils/Configuration.ts
- packages/entity-generator/src/EntityGenerator.ts
- packages/entity-generator/src/EntitySchemaSourceFile.ts
- packages/entity-generator/src/SourceFile.ts
- tests/features/entity-generator/MetadataHooks.mysql.test.ts
- tests/features/entity-generator/__snapshots__/MetadataHooks.mysql.test.ts.snap
> feat(entity-generator): allow post processing the metadata

- packages/core/src/typings.ts
> fix(migrator): type mismatch between Migration interface and class

- packages/knex/src/schema/SchemaHelper.ts
- packages/knex/src/schema/SqlSchemaGenerator.ts
- packages/postgresql/src/PostgreSqlSchemaHelper.ts
- tests/SchemaHelper.test.ts
- tests/features/native-postgres-enums/__snapshots__/native-enum-diffing.postgres.test.ts.snap
- tests/features/schema-generator/__snapshots__/SchemaGenerator.postgres.test.ts.snap
- tests/features/schema-generator/enum-diffing.postgres.test.ts
> fix(postgres): drop text enum check constraints only when necessary

- docs/docs/identity-map.md
- docs/versioned_docs/version-6.1/identity-map.md
Fix typo and ambiguous use of `it`.
> docs: Update identity-map.md

- docs/docs/guide/00-introduction.md
- docs/versioned_docs/version-6.2/guide/00-introduction.md
Removing "provide" here as it seems to have snuck in on accident.
> docs: Fix typo in 00-introduction.md

- packages/core/src/serialization/EntityTransformer.ts
- tests/features/virtual-entities/virtual-entities.mongo.test.ts
> fix(core): ignore serialization options when using `toPOJO()`

- packages/knex/src/dialects/mysql/MySqlSchemaHelper.ts
> fix(mysql): fix support for older MySQL versions than v8.0.13 when reading indexes

- packages/knex/src/query/ObjectCriteriaNode.ts
- packages/knex/src/typings.ts
- tests/QueryBuilder.test.ts
> fix(query-builder): don't use alias in more complex queries when not needed

- packages/entity-generator/src/EntitySchemaSourceFile.ts
- tests/features/entity-generator/CustomBase.sqlite.test.ts
- tests/features/entity-generator/__snapshots__/CustomBase.sqlite.test.ts.snap
Also renamed it from ".mysql." to ".sqlite.", since it uses sqlite.
> test(entity-generator): changed the CustomBase test to properly cover the existing base class case

- docs/docs/guide/01-first-entity.md
- docs/docs/metadata-cache.md
- docs/docs/query-builder.md
- docs/docs/query-conditions.md
- docs/versioned_docs/version-2.7/metadata-cache.md
- docs/versioned_docs/version-3.6/metadata-cache.md
- docs/versioned_docs/version-4.5/metadata-cache.md
- docs/versioned_docs/version-5.9/metadata-cache.md
- docs/versioned_docs/version-5.9/query-builder.md
- docs/versioned_docs/version-5.9/query-conditions.md
- docs/versioned_docs/version-6.0/guide/01-first-entity.md
- docs/versioned_docs/version-6.0/metadata-cache.md
- docs/versioned_docs/version-6.0/query-builder.md
- docs/versioned_docs/version-6.0/query-conditions.md
- docs/versioned_docs/version-6.1/guide/01-first-entity.md
- docs/versioned_docs/version-6.1/metadata-cache.md
- docs/versioned_docs/version-6.1/query-builder.md
- docs/versioned_docs/version-6.1/query-conditions.md
- docs/versioned_docs/version-6.2/guide/01-first-entity.md
- docs/versioned_docs/version-6.2/metadata-cache.md
- docs/versioned_docs/version-6.2/query-builder.md
- docs/versioned_docs/version-6.2/query-conditions.md
- packages/core/src/utils/DataloaderUtils.ts
- packages/core/src/utils/Utils.ts
Spell fixes on md files and comments
> docs: fix some spell issues

- docs/docs/events.md
- docs/versioned_docs/version-6.2/events.md
> docs: fix typo in events.md

- packages/core/src/EntityManager.ts
- packages/core/src/drivers/DatabaseDriver.ts
- packages/core/src/entity/EntityHelper.ts
- packages/core/src/serialization/EntitySerializer.ts
- packages/core/src/serialization/EntityTransformer.ts
- packages/core/src/serialization/SerializationContext.ts
- packages/core/src/typings.ts
- packages/knex/src/query/QueryBuilder.ts
> perf(core): rework `EntityKey` type to improve tsserver performance

- docs/docs/naming-strategy.md
- packages/core/src/naming-strategy/AbstractNamingStrategy.ts
- packages/core/src/naming-strategy/NamingStrategy.ts
- packages/entity-generator/src/EntityGenerator.ts
- tests/UnderscoreNamingStrategy.test.ts
- tests/features/entity-generator/MetadataHooks.mysql.test.ts
- tests/features/entity-generator/__snapshots__/AmbiguousFks.mysql.test.ts.snap
- tests/features/entity-generator/__snapshots__/ConflictingEntityNames.mysql.test.ts.snap
- tests/features/entity-generator/__snapshots__/EntityGenerator.mysql.test.ts.snap
- tests/features/entity-generator/__snapshots__/FkIndexSelection.mysql.test.ts.snap
- tests/features/entity-generator/__snapshots__/FkSharedWithColumn.mysql.test.ts.snap
- tests/features/entity-generator/__snapshots__/FksWithDefaults.mysql.test.ts.snap
- tests/features/entity-generator/__snapshots__/ManyToManyRelations.mysql.test.ts.snap
- tests/features/entity-generator/__snapshots__/MetadataHooks.mysql.test.ts.snap
- tests/features/entity-generator/__snapshots__/NonCompositeAmbiguousFks.mysql.test.ts.snap
- tests/features/entity-generator/__snapshots__/NullableFks.mysql.test.ts.snap
- tests/features/entity-generator/__snapshots__/OverlapFks.mysql.test.ts.snap
> fix(entity-generator): generate all bidirectional relations in case of conflicts

- packages/core/src/platforms/Platform.ts
- packages/core/src/types/JsonType.ts
- packages/mongodb/src/MongoPlatform.ts
- packages/mssql/src/MsSqlPlatform.ts
- tests/features/custom-types/GH5176.test.ts
- tests/features/custom-types/json-properties.test.ts
- tests/features/embeddables/GH3327.test.ts
> fix(core): improve handling of JSON properties to support numeric strings in all drivers

- packages/core/src/hydration/ObjectHydrator.ts
- packages/core/src/metadata/EntitySchema.ts
- packages/core/src/metadata/MetadataDiscovery.ts
- tests/features/embeddables/GH2987.test.ts
- tests/features/embeddables/__snapshots__/polymorphic-embedded-entities.sqlite.test.ts.snap
- tests/features/embeddables/polymorphic-embedded-entities.mongo.test.ts
- tests/features/embeddables/polymorphic-embedded-entities.sqlite.test.ts
> fix(core): support overloading embedded properties

- docs/docs/guide/04-advanced.md
- docs/versioned_docs/version-6.3/guide/04-advanced.md
> docs: fix validation example in getting started guide

- packages/core/src/metadata/MetadataDiscovery.ts
- packages/core/src/utils/Utils.ts
- tests/issues/GH5842.test.ts
> feat(core): support `Date` type on primary keys

- packages/knex/src/query/QueryBuilder.ts
- packages/knex/src/query/QueryBuilderHelper.ts
- packages/knex/src/query/enums.ts
- packages/knex/src/typings.ts
- tests/EntityManager.mysql.test.ts
- tests/features/__snapshots__/dataloader.test.ts.snap
- tests/features/collection/partial-collections.test.ts
- tests/features/embeddables/GH5325.test.ts
- tests/features/filters/filters.postgres.test.ts
- tests/features/joined-strategy.postgre.test.ts
- tests/issues/GH1882.test.ts
- tests/issues/GH5872.test.ts
> fix(knex): use nested join for `populateWhere` condition

- packages/core/src/drivers/IDatabaseDriver.ts
- packages/core/src/entity/Collection.ts
- packages/core/src/entity/EntityLoader.ts
- packages/core/src/entity/WrappedEntity.ts
- packages/core/src/entity/utils.ts
- packages/core/src/typings.ts
- tests/issues/GH5559.test.ts
> fix(core): adjust collection owner's serialization context when lazy-loading

- packages/knex/src/schema/DatabaseTable.ts
- tests/features/entity-generator/GH5912.postgresql.test.ts
- tests/features/entity-generator/__snapshots__/GH5912.postgresql.test.ts.snap
> fix(entity-generator): fix the search for FK indexes to only match exact columns, not "at least"

- packages/core/src/utils/Utils.ts
This most notably affects the migration generator.
> fix(core): fix dynamic imports on Windows

- packages/knex/src/schema/SchemaHelper.ts
- tests/features/embeddables/GH5847.test.ts
- tests/issues/GH5996.test.ts
- tests/issues/GH6072.test.ts
- tests/issues/__snapshots__/GH5996.test.ts.snap
- tests/issues/__snapshots__/GH6072.test.ts.snap
> fix(schema): resolve missing auto_increment for PK in `MySQL/MariaDB` update DDL

- packages/knex/src/dialects/mysql/MySqlColumnCompiler.ts
- packages/knex/src/dialects/mysql/MySqlSchemaHelper.ts
- packages/knex/src/schema/SchemaHelper.ts
- packages/knex/src/typings.ts
- tests/features/embeddables/GH5847.test.ts
- tests/issues/GH6095.test.ts
> refactor(schema): move increment related changes to `MySqlSchemaHelper`

- packages/core/src/utils/EntityComparator.ts
- tests/features/embeddables/GH6105.test.ts
- tests/features/embeddables/non-persisted-in-embeddables.test.ts
> fix(core): ignore non-persisted properties on embeddables

- docs/docs/embeddables.md
- packages/core/src/decorators/Embedded.ts
- packages/core/src/metadata/MetadataDiscovery.ts
- packages/core/src/typings.ts
- packages/core/src/utils/Configuration.ts
- tests/features/embeddables/GH6112.test.ts
fixes #6112 
I'm not totally convinced by the documentation I propose ...
> feat(core): add `prefixMode` option to embeddables

- docs/docs/migrations.md
- packages/core/src/utils/Configuration.ts
- packages/migrations-mongodb/src/Migrator.ts
- packages/migrations/src/Migrator.ts
- tests/bootstrap.ts
- tests/features/migrations/Migrator.mongo.test.ts
- tests/features/migrations/Migrator.test.ts
- tests/features/migrations/__snapshots__/Migrator.mongo.test.ts.snap
- tests/features/migrations/__snapshots__/Migrator.test.ts.snap
> feat(migrations): allow passing list of classes to `migrationsList`

- packages/entity-generator/src/EntityGenerator.ts
- tests/features/entity-generator/__snapshots__/ManyToManyRelations.mysql.test.ts.snap
> fix(entity-generator): output inverse sides for pure pivot tables when outputted

- packages/core/src/typings.ts
- packages/core/src/unit-of-work/ChangeSet.ts
- packages/core/src/utils/EntityComparator.ts
- tests/features/upsert/GH6252.test.ts
> fix(core): support upserting entities with FK as PK when the target entity has composite PK

- docs/docs/entity-helper.md
- packages/core/src/entity/EntityAssigner.ts
- packages/core/src/utils/Configuration.ts
- tests/features/entity-assigner/GH6338.test.ts
> feat(core): add `ignoreUndefined` flag to `assign` helper

- packages/core/src/entity/EntityValidator.ts
- packages/core/src/metadata/MetadataDiscovery.ts
- packages/core/src/utils/EntityComparator.ts
- tests/features/embeddables/GH6351.test.ts
- tests/features/embeddables/__snapshots__/polymorphic-embedded-entities.sqlite.test.ts.snap
- tests/features/embeddables/embedded-entities.mongo.test.ts
- tests/features/embeddables/embedded-entities.mysql.test.ts
- tests/features/embeddables/embedded-entities.postgres.test.ts
> fix(core): reduce chance of collisions of internal embedded properties

- packages/core/src/EntityManager.ts
- packages/core/src/utils/RawQueryFragment.ts
- tests/features/embeddables/embedded-entities.postgres.test.ts
> fix(core): allow querying by embedded instance with `em.findAndCount`

- packages/core/src/connections/Connection.ts
- packages/core/src/drivers/DatabaseDriver.ts
- packages/core/src/drivers/IDatabaseDriver.ts
- packages/core/src/entity/EntityFactory.ts
- packages/core/src/hydration/Hydrator.ts
- packages/core/src/hydration/ObjectHydrator.ts
- packages/core/src/typings.ts
- packages/core/src/unit-of-work/IdentityMap.ts
- packages/core/src/unit-of-work/UnitOfWork.ts
- packages/core/src/utils/Configuration.ts
- packages/knex/src/query/QueryBuilder.ts
- packages/knex/src/query/QueryBuilderHelper.ts
- tests/EntityManager.mssql.test.ts
- tests/EntityManager.postgre.test.ts
- tests/QueryBuilder.test.ts
- tests/features/filters/filters.postgres.test.ts
- tests/features/joined-strategy.postgre.test.ts
- tests/features/multiple-schemas/GH3177.test.ts
- tests/features/raw-queries/GHx6.mssql.test.ts
- tests/features/sharing-column-in-composite-fk/GH6373.test.ts
- tests/features/virtual-entities/virtual-entities.postgres.test.ts
- tests/issues/GH482.test.ts
> fix(query-builder): fix default schema resolution when root entity has a custom schema

- packages/knex/src/dialects/sqlite/BaseSqliteSchemaHelper.ts
- tests/features/schema-generator/__snapshots__/enum-diffing.sqlite.test.ts.snap
> fix(sqlite): ensure correct order of columns in temp table

- packages/knex/src/query/CriteriaNode.ts
- packages/knex/src/query/QueryBuilderHelper.ts
- tests/features/sharing-column-in-composite-fk/GH6359-2.test.ts
- tests/features/single-table-inheritance/GH6436.test.ts
> fix(core): fix querying by a composite property with shared columns

- packages/core/src/EntityManager.ts
- packages/core/src/drivers/IDatabaseDriver.ts
- packages/knex/src/AbstractSqlDriver.ts
- packages/knex/src/query/ObjectCriteriaNode.ts
- packages/knex/src/query/QueryBuilder.ts
- packages/knex/src/typings.ts
- tests/EntityManager.mariadb.test.ts
- tests/EntityManager.mssql.test.ts
- tests/EntityManager.mysql.test.ts
- tests/EntityManager.postgre.test.ts
- tests/features/collection/partial-collections.test.ts
- tests/features/filters/GH6458.test.ts
- tests/features/joined-strategy.postgre.test.ts
> fix(query-builder): apply filters to auto-joined relations

- packages/core/src/utils/Utils.ts
> fix(core): improve TS detection logic

- packages/core/src/EntityManager.ts
- packages/knex/src/query/QueryBuilder.ts
- tests/issues/GH6585.test.ts
Initial proposal to fix https://github.com/mikro-orm/mikro-orm/issues/6584
> fix(result-cache) properly handle valid `null` cache results

- packages/core/src/entity/Reference.ts
- tests/features/lazy-scalar-properties/lazy-scalar-properties.mysql.test.ts
Add `loadOrFail()` to ScalarRef
> feat(core): add `loadOrFail` to `ScalarReference` wrapper

- docs/docs/entity-manager.md
- docs/versioned_docs/version-6.4/entity-manager.md
I found something wrong in entity-manager.md file
> docs: Update entity-manager.md

- packages/core/src/utils/QueryHelper.ts
- tests/issues/GH234.test.ts
- tests/issues/GH6795.test.ts
> fix(query-builder): support group operators inside join conditions

- packages/knex/src/query/QueryBuilderHelper.ts
- tests/issues/GH6830.test.ts
- wrap composite keys in join conditions
Closes #6830
> fix(query-builder): properly wrap composite keys in join conditions
