package.json

https://github.com/observing/pre-commit requires more universal syntax for pre-commit definition. So you can use `npm` instead of `yarn` if you want

Use pre-commit.js instead of git-pre-commit => removed dependency on yarn

---

lib/EntityFactory.ts
lib/EntityManager.ts
lib/UnitOfWork.ts
lib/decorators/Entity.ts
lib/utils/EntityHelper.ts
lib/utils/EntityIdentifier.ts
lib/utils/Utils.ts
package.json
tests/EntityFactory.test.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/RequestContext.test.ts
tests/UnitOfWork.test.ts
tests/entities-sql/Book2.ts

Refactor unit of work to never run queries before committing

---

README.md
docs/entity-manager.md
docs/repositories.md
lib/EntityManager.ts
lib/EntityRepository.ts
lib/index.ts
lib/utils/Utils.ts
tests/EntityManager.mongo.test.ts
tests/EntityRepository.test.ts
tests/QueryBuilder.test.ts

EM and EntityRepository now supports providing options in object:
```
const books = await booksRepository.find({ author: '...' }, {
populate: ['author'],
limit: 1,
offset: 2,
sort: { title: QueryOrder.DESC },
});
```

feat: allow using options object in EntityManager.find()

---

lib/EntityManager.ts
lib/drivers/AbstractSqlDriver.ts
lib/drivers/IDatabaseDriver.ts
lib/query/QueryBuilder.ts
lib/query/QueryBuilderHelper.ts
lib/utils/Utils.ts
tests/EntityManager.mysql.test.ts
tests/QueryBuilder.test.ts
tests/mysql-schema.sql

Now it is possible to use custom expressions in where conditions:
`const book = await orm.em.findOne(Book, { 'JSON_CONTAINS(meta, ?)': [{ items: 1 }, true] });`
which will result in following query:
`SELECT `e0`.* FROM `book` AS `e0` WHERE JSON_CONTAINS(meta, ?) = ?` with params `['{"items":1}', true]`

feat(query-builder): add support for custom query expressions

---

lib/utils/RequestContext.ts
tests/RequestContext.test.ts

After observing huge performance impact when using async_hooks when concurrent requests are involved, Domain API seems like much better fit for this task. Even though they are deprecated, they will most likely stay till another (stable) solution will be available.
So far async_hooks caused memory leaks even without ORM being involved. Simple express server with async_hooks tracing enabled created dozens of references in CONTEXT map without properly destroying them (the destroy hook was simply not called for those resource).

perf: use Domain API instead of async_hooks

---

lib/drivers/IDatabaseDriver.ts
lib/entity/ArrayCollection.ts
lib/entity/Collection.ts
lib/unit-of-work/UnitOfWork.ts
tests/EntityManager.mongo.test.ts

When you use `Object.assign(entity, { ... })` instead of `entity.assign({ ... })` you could put your entity
into invalid state where there will be PK instead of entity reference. With this change all managed entities
will be validated before flushing and this case will be automatically handled, converting the PK to entity
when persisting it.
This is especially handy when you migrate existing project where you used `Object.assign(entity, { ... })`
to update entities (like in TypeORM) as this kind of error could be hard to find because they were failing
silently.

feat(core): automatically fix wrongly assigned associations

---

lib/EntityManager.ts
lib/entity/EntityRepository.ts
lib/utils/Configuration.ts
tests/EntityHelper.mongo.test.ts
tests/EntityHelper.mysql.test.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite.test.ts
tests/RequestContext.test.ts
tests/Utils.test.ts

Having auto flushing enabled by default was a poor choice, as it could produce multiple small transactions without user knowing it. EM.persist() now won't flush anything (by default), so ORM will behave the same way as others like hibernate or doctrine.
**BREAKING CHANGES:**
- With default `autoFlush` value, `em.persist()`, `em.removeEntity()` and `em.remove(e: IEntity)` will not flush the EM. Either use second `flush` parameter or flush method variants (like `em.removeAndFlush()`).
Closes #63

fix(core): disable auto flushing by default

---

lib/metadata/MetadataDiscovery.ts
lib/naming-strategy/AbstractNamingStrategy.ts
lib/naming-strategy/MongoNamingStrategy.ts
lib/naming-strategy/NamingStrategy.ts
lib/naming-strategy/UnderscoreNamingStrategy.ts
lib/naming-strategy/index.ts

getClassName() is used to find entity class name based on its file name. Now users can override the default implementation to accommodate their specific needs.
Closes #15

feat(mapping): allow overriding getClassName() in NamingStrategy

---

lib/MikroORM.ts
lib/decorators/Entity.ts
lib/metadata/MetadataDiscovery.ts
lib/platforms/MongoPlatform.ts
lib/platforms/MySqlPlatform.ts
lib/platforms/Platform.ts
lib/platforms/PostgreSqlPlatform.ts
lib/platforms/SqlitePlatform.ts
lib/schema/MySqlSchemaHelper.ts
lib/schema/PostgreSqlSchemaHelper.ts
lib/schema/SchemaGenerator.ts
lib/schema/SchemaHelper.ts
lib/schema/SqliteSchemaHelper.ts
lib/utils/Configuration.ts
tests/EntityFactory.test.ts
tests/EntityHelper.mongo.test.ts
tests/EntityManager.mongo.test.ts
tests/MikroORM.test.ts
tests/RequestContext.test.ts
tests/SchemaGenerator.test.ts
tests/UnitOfWork.test.ts
tests/Utils.test.ts
tests/__snapshots__/SchemaGenerator.test.ts.snap
tests/bootstrap.ts
tests/mysql-schema.sql
tests/postgre-schema.sql
tests/sqlite-schema.sql

SchemaGenerator now offers `createSchema` and `dropSchema` methods that by default return the necessary SQL, as well as with a `run` flag enabled it can run the SQL directly.
There is also `SchemaGenerator.execute()` that breaks the query into separate lines and executes it on current connection. This method is used under the hood when using the `run` flag. 
**BREAKING CHANGES:**
`SchemaGenerator.generate()` is now async.

feat(schema): use knex in schema generator

---

.gitignore
lib/MikroORM.ts
lib/entity/EntityValidator.ts
lib/metadata/MetadataDiscovery.ts
lib/naming-strategy/AbstractNamingStrategy.ts
lib/naming-strategy/NamingStrategy.ts
lib/platforms/PostgreSqlPlatform.ts
lib/schema/EntityGenerator.ts
lib/schema/MySqlSchemaHelper.ts
lib/schema/PostgreSqlSchemaHelper.ts
lib/schema/SchemaGenerator.ts
lib/schema/SchemaHelper.ts
lib/schema/SqliteSchemaHelper.ts
lib/utils/Utils.ts
package.json
tests/EntityGenerator.test.ts
tests/SchemaHelper.test.ts
tests/Utils.test.ts
tests/__snapshots__/EntityGenerator.test.ts.snap
tests/__snapshots__/SchemaGenerator.test.ts.snap
tests/entities-sql/Author2.ts
tests/entities-sql/Book2.ts
tests/entities-sql/FooBar2.ts
tests/entities-sql/FooBaz2.ts
tests/mysql-schema.sql
tests/postgre-schema.sql
tests/sqlite-schema.sql

New `EntityGenerator` class is present that allows to reverse engineer current database schema and build entity classes based on it. It supports only basic scalar and M:1 properties currently.
You can get the entities source code as a string, or save entities into files via `generate({ save: true })`.
Closes #78

feat(schema): add basic entity generator

---

ents/Author3.ts
ents/Book3.ts
ents/Book3ToBookTag3.ts
ents/BookTag3.ts
ents/Publisher3.ts
ents/Publisher3ToTest3.ts
ents/Test3.ts
lib/MikroORM.ts
lib/cache/CacheAdapter.ts
lib/cache/FileCacheAdapter.ts
lib/cache/NullCacheAdapter.ts
lib/cli.ts
lib/cli/CLIHelper.ts
lib/cli/ClearCacheCommand.ts
lib/cli/CreateSchemaCommand.ts
lib/cli/DropSchemaCommand.ts
lib/cli/GenerateEntitiesCommand.ts
lib/cli/UpdateSchemaCommand.ts
package.json
tests/FileCacheAdapter.test.ts
tests/NullCacheAdapter.test.ts
tests/cli-config.ts
tests/cli/CLIHelper.test.ts
tests/cli/ClearCacheCommand.test.ts
tests/cli/CreateSchemaCommand.test.ts
tests/cli/DropSchemaCommand.test.ts
tests/cli/GenerateEntitiesCommand.test.ts
tests/cli/UpdateSchemaCommand.test.ts
tsconfig.json
yarn.lock

Adds `mikro-orm` npm command that allows to clear cache and work with SchemaGenerator and EntityGenerator.
First one needs to provide `cli-config.[jt]s` file in the root directory that will export the ORM configuration.
Closes #101

feat(cli): add basic CLI tool

---

lib/EntityManager.ts
lib/MikroORM.ts
lib/connections/Connection.ts
lib/drivers/AbstractSqlDriver.ts
lib/drivers/DatabaseDriver.ts
lib/drivers/IDatabaseDriver.ts
lib/drivers/MongoDriver.ts
lib/drivers/MySqlDriver.ts
lib/query/QueryBuilder.ts
lib/unit-of-work/UnitOfWork.ts
lib/utils/Configuration.ts
lib/utils/Utils.ts
tests/EntityManager.mysql.test.ts
tests/QueryBuilder.test.ts
tests/bootstrap.ts

Now users can specify multiple read connections via `replicas` option. You can provide only fields that differ from master connection, rest will be taken from it.
By default select queries will use random read connection if not inside transaction. You can specify connection type manually in `EntityManager.getConnection(type: 'read' | 'write')`.
Closes #77

feat(core): add support for read connections

---

docs/entity-generator.md

should probably find/replace the whole docs for `bash`....

docs: declare correct type of codeblock

---

tests/Utils.test.ts
tests/cli/DebugCommand.test.ts

Added Utils.normalizePath to fix errors with running tests on windows. As this function is tested seperately, I assume that it's working correctly.
Example errors:
- (expected)    "   - C:\\Users\\XX\\Repositories\\mikro-orm/path/orm-config.ts (found)",
+ (received)"   - C:/Users/AW/Repositories/mikro-orm/path/orm-config.ts (found)",

Fixes for tests on windows.

---

README.md
docs/defining-entities.md
docs/relationships.md
lib/decorators/ManyToMany.ts
lib/decorators/OneToMany.ts
lib/metadata/TypeScriptMetadataProvider.ts
tests/decorators.test.ts
tests/entities-sql/Author2.ts
tests/entities-sql/FooBaz2.ts
tests/entities-sql/Publisher2.ts
tests/entities-sql/Test2.ts
tests/entities/Author.ts
tests/entities/Book.ts
tests/entities/Publisher.ts

Now the type from `prop: Collection<MyEntity>` is sniffed via reflection, so you do not have to define `entity` or `type` attributes in collection decorators (`@ManyToMany` and `@OneToMany`).

feat(core): do not require entity attribute in collection decorators

---

package.json
tests/post-test.js
tests/pre-test.js

`graceful-fs` and `jest` does not like each other, so this removes the `graceful-fs` implementation before running tests and adds it back afterwards.
https://github.com/facebook/jest/issues/6399
https://github.com/facebook/jest/issues/6814
https://github.com/isaacs/node-graceful-fs/issues/102

test: 'fix' memory leak in graceful-fs

---

docs/deployment.md

Fix for errors thrown when using Webpack (a MikroORM dependency, acorn, added mjs files which webpack can't load correctly and aren't needed during Webpack runtime).

Webpack fixes

---

lib/EntityManager.ts
lib/entity/EntityAssigner.ts
lib/entity/EntityLoader.ts
lib/utils/Utils.ts
tests/EntityManager.postgre.test.ts
tests/issues/GH222.test.ts
tests/issues/GH269.test.ts

This also fixes loading of 1:1 owners via populate when `autoJoinOneToOneOwner` option is disabled.
Closes #269

feat(core): add `refresh` parameter to `FindOptions`

---

.codeclimate.yml
docs/docs/entity-helper.md
docs/docs/upgrading-v2-to-v3.md
lib/EntityManager.ts
lib/entity/ArrayCollection.ts
lib/entity/Collection.ts
lib/entity/EntityAssigner.ts
lib/entity/EntityFactory.ts
lib/entity/EntityHelper.ts
lib/entity/EntityTransformer.ts
lib/entity/Reference.ts
lib/hydration/Hydrator.ts
lib/hydration/ObjectHydrator.ts
lib/types.ts
lib/unit-of-work/ChangeSetComputer.ts
lib/unit-of-work/UnitOfWork.ts
lib/utils/Configuration.ts
lib/utils/ValidationError.ts
tests/EntityFactory.test.ts
tests/EntityManager.mariadb.test.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/entities-js/BaseEntity4.js
tests/entities-sql/Book2.ts

Previously all entities had internal reference to the root EM - the one created when
initializing the ORM. Now only managed entities (those merged to the EM, e.g. loaded
from the database) have this internal reference.
To use `assign()` method on new (not managed) entities, you need to provide the `em`
parameter:
```typescript
const book = new Book();
wrap(book).assign(data, { em: orm.em });
```
Closes: #267

fix(core): do not set EM to entity until merging [BC]

---

docs/docs/upgrading-v2-to-v3.md
lib/entity/ArrayCollection.ts
lib/entity/EntityFactory.ts
lib/unit-of-work/UnitOfWork.ts
tests/EntityFactory.test.ts
tests/EntityManager.mongo.test.ts

Persist is now cascaded only to initialized entities. Previously all entities and all their properties
were cascaded, which was unnecessary overhead.
Previously all entity instances, including entity references (not fully loaded entities where
we know only the primary key), had instantiated collection classes. Now only initialized entities
have them.
Entity references (not initialized entities) now don't have instantiated collections.
```typescript
const book = em.getReference(Book, 1);
console.log(book.tags); // undefined
await book.init();
console.log(book.tags); // instance of Collection (not initialized)
```

perf(core): do not cascade persist entity references

---

lib/EntityManager.ts
lib/entity/EntityFactory.ts
lib/typings.ts
lib/unit-of-work/ChangeSet.ts
lib/unit-of-work/ChangeSetComputer.ts
lib/unit-of-work/ChangeSetPersister.ts
lib/unit-of-work/CommitOrderCalculator.ts
lib/unit-of-work/UnitOfWork.ts
lib/unit-of-work/index.ts
tests/CommitOrderCalculatorTest.test.ts
tests/EntityFactory.test.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.sqlite2.test.ts
tests/bootstrap.ts

- uses topological sorting to find correct order of entities when persisting to ensure FK availability
- postpones m:n collection updates (removes them from entity change sets)
- changes the logic when extra updates are used

feat(core): rework commit logic of UoW to ensure right query order

---

docs/docs/configuration.md
docs/docs/propagation.md
docs/sidebars.js
lib/entity/EntityHelper.ts
lib/unit-of-work/ChangeSetComputer.ts
lib/utils/Configuration.ts
lib/utils/Utils.ts
tests/EntityHelper.mongo.test.ts
tests/bootstrap.ts
tests/entities/Book.ts
tests/issues/GH269.test.ts
tests/issues/GH302.test.ts

MikroORM now defines getter and setter for every owning side of m:1 and 1:1 relation. This is
then used for propagation of changes to the inverse side of bi-directional relations.
```typescript
const author = new Author('n', 'e');
const book = new Book('t');
book.author = author;
console.log(author.books.contains(book)); // true
```
Closes #307

feat(core): propagate changes to 1:1 and m:1 relations

---

lib/utils/Utils.ts
tests/Utils.test.ts

Merge would convert Buffers into Objects with integer keys, which prevented ObjectIds from being persisted to MongoDB if EntityAssigner.assign was used with mergeObjects.
Closes #365

fix(utils): Treat ObjectIds and Buffers as scalars

---

lib/query/QueryBuilder.ts
lib/typings.ts

As discussed in the Slack channel, this improves typings and provides intelliSense for the `QueryBuilder` `where` methods, without breaking change.

feat(query-builder): improved typing of where(), andWhere(), orWhere()

---

docs/docs/entity-manager.md
docs/docs/multiple-schemas.md
docs/docs/query-builder.md
docs/docs/repositories.md
lib/EntityManager.ts
lib/drivers/AbstractSqlDriver.ts
lib/drivers/DatabaseDriver.ts
lib/drivers/IDatabaseDriver.ts
lib/drivers/MongoDriver.ts
lib/entity/EntityRepository.ts
lib/query/QueryBuilder.ts
lib/unit-of-work/ChangeSetPersister.ts
tests/EntityManager.mysql.test.ts
tests/QueryBuilder.test.ts
tests/bootstrap.ts

Now one can also query for entity in specific schema via `EntityManager`, `EntityRepository` or
`QueryBuilder`:
```typescript
const user = await em.findOne(User, { ... }, { schema: 'client-123' });
```
To create entity in specific schema, we will need to use `QueryBuilder`:
```typescript
const qb = em.createQueryBuilder(User);
await qb.insert({ email: 'foo@bar.com' }).withSchema('client-123');
```
Closes #284

feat(sql): add `schema` param to `FindOptions` and QB

---

docs/docs/usage-with-mongo.md
lib/MikroORM.ts
lib/connections/MongoConnection.ts
lib/drivers/DatabaseDriver.ts
lib/drivers/IDatabaseDriver.ts
lib/drivers/MongoDriver.ts
lib/utils/Configuration.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/bootstrap.ts
tests/entities/Author.ts
tests/entities/Book.ts

MongoDB driver now supports indexes and unique constraints. You can use `@Index()` and `@Unique()`.
To automatically create new indexes when initializing the ORM, you need to enable `ensureIndexes` option.
```typescript
const orm = await MikroORM.init({
entitiesDirs: ['entities'], // relative to `baseDir`
dbName: 'my-db-name',
type: 'mongo',
ensureIndexes: true, // defaults to false
});
```
Alternatively you can call `ensureIndexes()` method on the `MongoDriver`:
```typescript
await orm.em.getDriver().ensureIndexes();
```
Closes #159

feat(mongodb): add support for indexes in mongo driver

---

.npmignore

mikro-orm is currently published with 920 MB of test data left over from run-rs. Adding /data to .npmignore excludes this test data from the published package and greatly reduces the installation footprint.
I'm unsure how to add a test for this, if it's even reasonably possible. I saw tests requested as part of the pull request guidelines, so let me know if there's anything I ought to do in that regard.
I've only been working with mikro-orm for a short while now, and I'm really liking it so far. Keep up the good work, and I'm happy to have the opportunity to contribute!

fix(.npmignore): Ignore MongoDB data directory

---

lib/drivers/AbstractSqlDriver.ts
lib/drivers/DatabaseDriver.ts
lib/drivers/IDatabaseDriver.ts
lib/entity/Collection.ts
lib/unit-of-work/ChangeSetPersister.ts
lib/unit-of-work/UnitOfWork.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts

When updating m:n collections, snapshots are now used to compute the exact different with the current state.
This means that we now execute only the queries that are needed (e.g. if we only append 1 item, we do not
clear the whole collection and insert everything as it was before, but rather fire 1 precise query for the
missing item).

feat(sql): use collection snapshots to compute precise diff

---

docs/docs/deployment.md

This shows how to avoid sniffing with ts-morph when deploying with webpack.

Update deployment example for Enums

---

lib/entity/EntityAssigner.ts
lib/entity/EntityFactory.ts
lib/entity/EntityTransformer.ts
lib/entity/EntityValidator.ts
lib/unit-of-work/ChangeSetComputer.ts
lib/unit-of-work/ChangeSetPersister.ts
lib/unit-of-work/UnitOfWork.ts
lib/utils/Utils.ts
tests/EntityManager.mysql.test.ts
tests/Utils.test.ts

There are some cases where an entity will have a primary key of 0.
Our use case is a table of static statuses that are pervasive
throughout our application. We add the rows when we generate the
schema, not through the ORM. We only want to map relationships
to those statuses with the ORM. Some of these statuses start with
the id of 0 versus 1. Previous to this fix, there were generic
falsy checks that would take a primary key with a value of 0 as
if the primary key was not set. This fix makes those checks
specific for both null and undefined values.

feat(core): allow for the number zero as a primary key

---

lib/connections/PostgreSqlConnection.ts
lib/connections/SqliteConnection.ts
lib/schema/DatabaseSchema.ts
lib/schema/DatabaseTable.ts
lib/schema/MySqlSchemaHelper.ts
lib/schema/PostgreSqlSchemaHelper.ts
lib/schema/SchemaGenerator.ts
lib/schema/SchemaHelper.ts
package.json
tests/Migrator.test.ts
tests/SchemaGenerator.test.ts
tests/__snapshots__/SchemaGenerator.test.ts.snap
tests/mysql-schema.sql
yarn.lock

String enums are now discovered properly, and we diff the actual enum items to know whether something changed.
This also fixes postgres enum altering that produced invalid query.
Postgres dialect in knex is now monkey patched to have control over how column alters are working.
Now only necessary queries should be made (so no `drop null` followed by `set null`, etc).
Closes #397
Closes #432

fix(schema): rework enum handling in schema generator

---

docs/docs/usage-with-mongo.md
lib/drivers/MongoDriver.ts
tests/EntityManager.mongo.test.ts
tests/entities/Book.ts

Added support for text indexes in MongoDB.
Added text index test.
Closes #479

feat(mongo): add support for mongodb text indexes

---

lib/drivers/MongoDriver.ts

Adds sparse option to nullable unique indexes
Closes #484

feat(mongo): add support for nullable unique indexes

---

package.json
packages/core/src/decorators/Entity.ts
packages/core/src/decorators/Enum.ts
packages/core/src/decorators/Indexed.ts
packages/core/src/decorators/ManyToMany.ts
packages/core/src/decorators/ManyToOne.ts
packages/core/src/decorators/OneToMany.ts
packages/core/src/decorators/PrimaryKey.ts
packages/core/src/decorators/Property.ts
packages/core/src/decorators/Repository.ts
packages/core/src/decorators/hooks.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/metadata/MetadataStorage.ts
packages/core/src/utils/Utils.ts
tests/Utils.test.ts
tests/decorators.test.ts

Decorators are using static MetadataStorage, now the keys includes also the path to entity, so technically it is possible to have multiple entities with the same name (although not in the same ORM context, but with multiple ORM instances).
This should also fix issues with HMR and "multiple property decorators used" validation error.
Runtime metadata (`orm.getMetadata()`) are kept intact, so the key there is just the entity name.

feat(discovery): use both entity name and path as key in MetadataStorage

---

ROADMAP.md
packages/core/src/entity/ArrayCollection.ts
packages/core/src/entity/Collection.ts
packages/core/src/unit-of-work/UnitOfWork.ts
packages/knex/src/AbstractSqlDriver.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite.test.ts
tests/EntityManager.sqlite2.test.ts

Works for both 1:m and m:n collections.
```typescript
const a = await orm.em.findOneOrFail(Author2, god.id);
console.log(a.books.isInitialized()); // false
const b2 = new Book2('Bible 2', a);
const b3 = new Book2('Bible 3', a);
a.books.add(b2, b3);
await orm.em.flush();
```

feat(core): allow adding items to not initialized collections

---

ROADMAP.md
docs/docs/defining-entities.md
docs/docs/inheritance-mapping.md
docs/sidebars.js
packages/core/src/decorators/Entity.ts
packages/core/src/entity/EntityAssigner.ts
packages/core/src/entity/EntityFactory.ts
packages/core/src/entity/EntityValidator.ts
packages/core/src/hydration/Hydrator.ts
packages/core/src/metadata/EntitySchema.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/typings.ts
packages/core/src/unit-of-work/UnitOfWork.ts
packages/core/src/utils/Utils.ts
packages/knex/src/schema/SchemaGenerator.ts
tests/__snapshots__/EntityGenerator.test.ts.snap
tests/__snapshots__/SchemaGenerator.test.ts.snap
tests/bootstrap.ts
tests/entities-sql/Address2.ts
tests/entities-sql/BaseUser2.ts
tests/entities-sql/CompanyOwner2.ts
tests/entities-sql/Employee2.ts
tests/entities-sql/Manager2.ts
tests/entities-sql/index.ts
tests/mysql-schema.sql
tests/single-table-inheritance.mysql.test.ts

```typescript
@Entity({
discriminatorColumn: 'discr',
discriminatorMap: { person: 'Person', employee: 'Employee' },
})
export class Person {
// ...
}
@Entity()
export class Employee extends Person {
// ...
}
```
Closes #33

feat(core): add support for single table inheritance

---

ROADMAP.md
docs/docs/embeddables.md
packages/core/src/decorators/Embeddable.ts
packages/core/src/decorators/Embedded.ts
packages/core/src/decorators/index.ts
packages/core/src/entity/EntityAssigner.ts
packages/core/src/entity/EntityHelper.ts
packages/core/src/entity/enums.ts
packages/core/src/hydration/Hydrator.ts
packages/core/src/hydration/ObjectHydrator.ts
packages/core/src/metadata/EntitySchema.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/metadata/MetadataValidator.ts
packages/core/src/typings.ts
packages/core/src/utils/Utils.ts
packages/core/src/utils/ValidationError.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/CriteriaNode.ts
packages/knex/src/query/ObjectCriteriaNode.ts
packages/knex/src/query/QueryBuilderHelper.ts
packages/knex/src/schema/SchemaGenerator.ts
packages/mongodb/src/MongoDriver.ts
tests/EntityManager.mongo.test.ts
tests/__snapshots__/embedded-entities.mysql.test.ts.snap
tests/embedded-entities.mongo.test.ts
tests/embedded-entities.mysql.test.ts

Embeddables are classes which are not entities themselves, but are embedded in entities.
```typescript
@Embeddable()
class Address {
@Property()
street!: string;
@Property()
city!: string;
@Property()
country!: string;
}
@entity()
class User {
@PrimaryKey()
id!: number;
@Embedded(() => Address)
address!: Address;
}
```

feat(mapping): add support for embeddables

---

ROADMAP.md
docs/docs/query-builder.md
packages/knex/src/query/CriteriaNode.ts
packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
tests/QueryBuilder.test.ts
tests/entities-sql/Author2.ts

You can use sub-queries in selects or in where conditions. To select subquery, use `qb.as(alias)` method:
```typescript
const knex = orm.em.getKnex();
const qb1 = orm.em.createQueryBuilder(Book2, 'b').count('b.uuid', true).where({ author: knex.ref('a.id') }).as('Author2.booksTotal');
const qb2 = orm.em.createQueryBuilder(Author2, 'a');
qb2.select(['*', qb1]).orderBy({ booksTotal: 'desc' });
console.log(qb2.getQuery());
// select `a`.*, (select count(distinct `b`.`uuid_pk`) as `count` from `book2` as `b` where `b`.`author_id` = `a`.`id`) as `books_total` from `author2` as `a` order by `books_total` desc
```
When you want to filter by sub-query, you will need to register it first via `qb.withSubquery()`:
> The dynamic property (`booksTotal`) needs to be defined at the entity level (as …

feat(sql): add support for sub-queries

---

ROADMAP.md
packages/knex/src/query/ArrayCriteriaNode.ts
packages/knex/src/query/CriteriaNode.ts
packages/knex/src/query/ObjectCriteriaNode.ts
packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/enums.ts
tests/QueryBuilder.test.ts

```typescript
qb.update({ name: 'test 123', type: PublisherType.GLOBAL }).where({ books: { author: 123 } });`
```
will result in following query:
```sql
update `publisher2` set `name` = ?, `type` = ? where `id` in (select `e0`.`id` from (
select distinct `e0`.`id` from `publisher2` as `e0` left join `book2` as `e1` on `e0`.`id` = `e1`.`publisher_id` where `e1`.`author_id` = ?
) as `e0`)
```
Closes #319

feat(sql): allow update queries with auto-joining via sub-queries

---

ROADMAP.md
packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/enums.ts
tests/QueryBuilder.test.ts

```typescript
qb.delete({ books: { author: 123 } });`
```
will result in following query:
```sql
delete from `publisher2` where `id` in (select `e0`.`id` from (
select distinct `e0`.`id` from `publisher2` as `e0` left join `book2` as `e1` on `e0`.`id` = `e1`.`publisher_id` where `e1`.`author_id` = ?
) as `e0`)
```
Closes #492

feat(sql): allow delete queries with auto-joining via sub-queries

---

.codeclimate.yml
ROADMAP.md
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/exceptions.ts
packages/core/src/index.ts
packages/core/src/platforms/ExceptionConverter.ts
packages/core/src/platforms/Platform.ts
packages/core/src/platforms/index.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/schema/SchemaGenerator.ts
packages/migrations/src/MigrationRunner.ts
packages/mongodb/src/MongoDriver.ts
packages/mongodb/src/MongoExceptionConverter.ts
packages/mongodb/src/MongoPlatform.ts
packages/mysql-base/src/MySqlExceptionConverter.ts
packages/mysql-base/src/MySqlPlatform.ts
packages/mysql-base/src/index.ts
packages/postgresql/src/PostgreSqlExceptionConverter.ts
packages/postgresql/src/PostgreSqlPlatform.ts
packages/postgresql/src/index.ts
packages/sqlite/src/SqliteDriver.ts
packages/sqlite/src/SqliteExceptionConverter.ts
packages/sqlite/src/SqlitePlatform.ts
packages/sqlite/src/index.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite.test.ts

Custom exceptions are now thrown from the driver for common problems like:
- `NotNullConstraintViolationException`
- `UniqueConstraintViolationException`
- `SyntaxErrorException`
Mongo driver currently supports only `UniqueConstraintViolationException`.
```typescript
const driver = orm.em.getDriver();
await driver.nativeInsert(Author3.name, { name: 'author', email: 'email' });
await expect(driver.nativeInsert(Author3.name, { name: 'author', email: 'email' })).rejects.toThrow(UniqueConstraintViolationException);
await expect(driver.nativeInsert(Author3.name, {})).rejects.toThrow(NotNullConstraintViolationException);
await expect(driver.nativeInsert('not_existing', { foo: 'bar' })).rejects.toThrow(TableNotFoundException);
await expect(driver.execute('create table author3 (foo text not …
```

feat(core): use custom exceptions for driver related errors

---

ROADMAP.md
docs/docs/defining-entities.md
docs/docs/upgrading-v3-to-v4.md
packages/core/src/decorators/Property.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/typings.ts
packages/knex/src/query/QueryBuilderHelper.ts
packages/knex/src/schema/DatabaseTable.ts
packages/knex/src/schema/SchemaGenerator.ts
packages/knex/src/schema/SchemaHelper.ts
packages/mysql-base/src/MySqlSchemaHelper.ts
tests/EntityManager.mysql.test.ts
tests/SchemaGenerator.test.ts
tests/SchemaHelper.test.ts
tests/__snapshots__/SchemaGenerator.test.ts.snap
tests/entities-sql/Author2.ts
tests/entities-sql/Book2.ts
tests/issues/GH380.test.ts
tests/mysql-schema.sql
tests/postgre-schema.sql

Previously the `default` option of properties was used as is, so we had to wrap
strings in quotes (e.g. `@Property({ default: "'foo bar'" })`).
In v4 the `default` is typed as `string | number | boolean | null` and when used
with string value, it will be automatically quoted.
To use SQL functions we now need to use `defaultRaw`: `@Property({ defaultRaw: 'now()' })`.
Related: #534
**BREAKING CHANGE:**
To use SQL functions, you will need to use `defaultRaw`.
String defaults in `default` should be no longer explicitly quoted (use `default: 'foo'` instead of `default: "'foo'"`).

refactor(schema): change behaviour of property default, add defaultRaw

---

ROADMAP.md
docs/docs/decorators.md
docs/docs/defining-entities.md
packages/core/src/decorators/Formula.ts
packages/core/src/decorators/Property.ts
packages/core/src/decorators/index.ts
packages/core/src/metadata/EntitySchema.ts
packages/core/src/typings.ts
packages/knex/src/query/QueryBuilder.ts
tests/EntityHelper.mysql.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/QueryBuilder.test.ts
tests/entities-sql/Book2.ts
tests/entities-sql/FooBar2.ts

`@Formula()` decorator can be used to map some SQL snippet to your entity.
The SQL fragment can be as complex as you want and even include subselects.
```typescript
@Formula('obj_length * obj_height * obj_width')
objectVolume?: number;
```
Formulas will be added to the select clause automatically. In case you are facing
problems with `NonUniqueFieldNameException`, you can define the formula as a
callback that will receive the entity alias in the parameter:
```typescript
@Formula(alias => `${alias}.obj_length * ${alias}.obj_height * ${alias}.obj_width`)
objectVolume?: number;
```

feat(sql): add support for computed properties via `@Formula()`

---

packages/cli/package.json
packages/cli/src/CLIHelper.ts
packages/core/src/utils/ConfigurationLoader.ts
tests/cli/CLIHelper.test.ts
yarn.lock

This enables the use of path aliases in the config file.
Example `tsconfig.json`
```json
{
"compilerOptions": {
"paths": {
"@foo": ["src/foo/index.ts"]
}
},
}
```
Example `mikro-orm.config.ts`
```ts
import * as foo from '@foo';
const config = foo.myFancyFunctionThatReturnsAFancyConfig();
export default config;
```

feat(cli): allow the use of TS path mapping

---

docs/versioned_docs/version-3.3/relationships.md
docs/versioned_docs/version-3.4/relationships.md
docs/versioned_docs/version-3.5/relationships.md
docs/versioned_docs/version-3.6/relationships.md

Hello, 
This PR improves the docs about multiple M:N Relationships on the same entity via manual naming of the pivot table on all V3 docs as mentioned [here](https://github.com/mikro-orm/mikro-orm/issues/555#issuecomment-625854857). 
This PR references [this issue](https://github.com/mikro-orm/mikro-orm/issues/555). 
I have also added an example to demonstrate how it is done but let me know if this is extra and I can remove it. 
Many thanks for this great project,
Ali

docs: add note about multiple m:n between same entities

---

docs/docs/custom-types.md
packages/core/src/decorators/Property.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/platforms/Platform.ts
packages/core/src/types/ArrayType.ts
packages/core/src/types/BlobType.ts
packages/core/src/types/JsonType.ts
packages/core/src/types/index.ts
packages/knex/src/schema/DatabaseTable.ts
packages/mongodb/src/MongoPlatform.ts
packages/postgresql/src/PostgreSqlPlatform.ts
packages/postgresql/src/PostgreSqlSchemaHelper.ts
packages/sqlite/src/SqlitePlatform.ts
tests/EntityHelper.mysql.test.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite2.test.ts
tests/__snapshots__/EntityGenerator.test.ts.snap
tests/__snapshots__/SchemaGenerator.test.ts.snap
tests/entities-schema/FooBar4.ts
tests/entities-sql/FooBar2.ts
tests/entities/FooBar.ts
tests/mysql-schema.sql
tests/postgre-schema.sql
tests/types/ArrayType.test.ts

In PostgreSQL and MongoDB, it uses native arrays, otherwise it concatenates the 
values into string separated by commas. This means that you can't use values that
contain comma with the `ArrayType` (but you can create custom array type that will
handle this case, e.g. by using different separator).
By default array of strings is returned from the type. You can also have arrays 
of numbers or other data types - to do so, you will need to implement custom 
`hydrate` method that is used for converting the array values to the right type.
```typescript
@Property({ type: new ArrayType(i => +i), nullable: true })
array?: number[];
```
Blob type can be used to store binary data in the database. 
```typescript
@Property({ type: BlobType, nullable: true })
blob?: Buffer;
```
To store objects we can …

feat(core): add custom types for array, blob and json

---

packages/core/src/decorators/Enum.ts
packages/core/src/decorators/ManyToMany.ts
packages/core/src/decorators/ManyToOne.ts
packages/core/src/decorators/OneToMany.ts
packages/core/src/decorators/OneToOne.ts
packages/core/src/decorators/PrimaryKey.ts
packages/core/src/decorators/Property.ts
packages/core/src/metadata/EntitySchema.ts
packages/core/src/typings.ts
packages/core/src/unit-of-work/ChangeSetPersister.ts
tests/EntityHelper.mongo.test.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.sqlite.test.ts
tests/entities/FooBar.ts

```typescript
@Property({ onCreate: (bar: FooBar) => '...return new value based on the entity state...' })
onCreateTest?: string;
```

feat(core): pass entity as parameter in `onCreate` and `onUpdate`

---

packages/knex/src/query/QueryBuilder.ts
tests/QueryBuilder.test.ts

This allows to skip `qb.select('*')` call.

feat(sql): initialize query builder in select mode

---

docs/versioned_docs/version-3.6/defining-entities.md

Currently on https://mikro-orm.io/docs/defining-entities these two blocks aren't styled correctly as the markdown parser doesn't recognise the language hint. Fixing the spacing to match the rest of the file should fix this.

docs: improve code snippets in entity definition section

---

packages/core/src/entity/EntityFactory.ts
packages/mongodb/src/MongoDriver.ts
packages/mongodb/src/MongoPlatform.ts
tests/issues/GH349.test.ts

feat(mongo): allow using different primary key types than ObjectId

---

docs/docs/lifecycle-hooks.md
docs/versioned_docs/version-3.6/lifecycle-hooks.md
lib/unit-of-work/UnitOfWork.ts
lib/utils/ValidationError.ts
tests/issues/GH493.test.ts

Hooks are executed inside the commit action of unit of work, after all change
sets are computed. This means that it is not possible to create new entities as
usual from inside the hook. Calling `em.flush()` from hooks will result in
validation error. Calling `em.persist()` can result in undefined behaviour like
locking errors.
> The **internal** instance of `EntityManager` accessible under `wrap(this).__em` is
> not meant for public usage.
Closes #493

fix(validation): throw when trying to call `em.flush()` from hooks

---

packages/core/src/EntityManager.ts
packages/core/src/decorators/Property.ts
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/entity/EntityLoader.ts
packages/core/src/entity/EntityRepository.ts
packages/core/src/entity/enums.ts
packages/core/src/metadata/EntitySchema.ts
packages/core/src/typings.ts
packages/core/src/unit-of-work/ChangeSetPersister.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/QueryBuilder.ts
tests/JoinedLoads.test.ts
tests/QueryBuilder.test.ts
tests/entities-sql/Author2.ts

This adds support for alternate load strategies. As of now, only one additional strategy is supported: `joined`. Currently, the only way to specify the strategy is on on the decorator for the relationship:
```ts
@Entity()
export class Author2 {
@OneToMany({
entity: () => Book2,
mappedBy: 'author',
orderBy: { title: QueryOrder.ASC },
strategy: LoadStrategy.JOINED, // new property
})
books!: Collection<Book2>;
}
```
---
Closes #440 (reopen of #517)

feat(core): add support for alternative loading strategies

---

packages/core/src/utils/ConfigurationLoader.ts

When using a custom tsconfig it fails on the ` require(tsConfigPath);` because the path is wrong:
`(node:34784) UnhandledPromiseRejectionWarning: Error: Cannot find module 'tsconfig.server.json'`
Before this fix only the default parameter had the correct path.

fix(cli): custom tsconfig gets wrong path

---

docs/docs/decorators.md
docs/docs/lifecycle-hooks.md
packages/core/src/EntityManager.ts
packages/core/src/decorators/Subscriber.ts
packages/core/src/decorators/hooks.ts
packages/core/src/decorators/index.ts
packages/core/src/entity/EntityFactory.ts
packages/core/src/events/EventManager.ts
packages/core/src/events/EventSubscriber.ts
packages/core/src/events/EventType.ts
packages/core/src/events/index.ts
packages/core/src/index.ts
packages/core/src/metadata/MetadataStorage.ts
packages/core/src/typings.ts
packages/core/src/unit-of-work/UnitOfWork.ts
packages/core/src/utils/Configuration.ts
tests/EntityManager.mysql.test.ts
tests/bootstrap.ts
tests/subscribers/Author2Subscriber.ts
tests/subscribers/EverythingSubscriber.ts

Use `EventSubscriber` to hook to multiple entities or if you do not want to pollute
the entity prototype. All methods are optional, if you omit the `getSubscribedEntities()`
method, it means you are subscribing to all entities.
```typescript
@Subscriber()
export class EverythingSubscriber implements EventSubscriber {
async afterCreate<T>(args: EventArgs<T>): Promise<void> { ... }
async afterDelete<T>(args: EventArgs<T>): Promise<void> { ... }
async afterUpdate<T>(args: EventArgs<T>): Promise<void> { ... }
async beforeCreate<T>(args: EventArgs<T>): Promise<void> { ... }
async beforeDelete<T>(args: EventArgs<T>): Promise<void> { ... }
async beforeUpdate<T>(args: EventArgs<T>): Promise<void> { ... }
onInit<T>(args: EventArgs<T>): void { ... }
}
```
Closes #516

feat(core): add support for event subscribers

---

packages/knex/src/schema/SchemaGenerator.ts
tests/__snapshots__/SchemaGenerator.test.ts.snap

Use `CommitOrderCalculator` to calculate correct order for defining tables.

feat(sql): ensure correct table order in schema generator

---

docs/docs/upgrading-v3-to-v4.md
packages/cli/src/commands/DebugCommand.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/metadata/MetadataValidator.ts
packages/core/src/utils/Configuration.ts
packages/core/src/utils/Utils.ts
packages/reflection/src/TsMorphMetadataProvider.ts
tests/MikroORM.test.ts
tests/SchemaGenerator.test.ts
tests/Webpack.test.ts
tests/__snapshots__/SchemaGenerator.test.ts.snap
tests/bootstrap.ts
tests/cli/CLIHelper.test.ts
tests/cli/DebugCommand.test.ts
tests/reflection/TsMorphMetadataProvider.test.ts
tests/single-table-inheritance.mysql.test.ts

`entitiesDirs` and `entitiesDirsTs` were removed in favour of `entities` and `entitiesTs`,
`entities` will be used as a default for `entitiesTs` (that is used when we detect `ts-node`).
`entities` can now contain mixture of paths to directories, globs pointing to entities,
or references to the entities or instances of `EntitySchema`. Negative globs are also
supported.
This basically means that all you need to change is renaming `entitiesDirs` to `entities`.
```typescript
MikroORM.init({
entities: ['dist/**/entities', 'dist/**/*.entity.js', FooBar, FooBaz],
entitiesTs: ['src/**/entities', 'src/**/*.entity.ts', FooBar, FooBaz],
});
```
**BREAKING CHANGE:**
`entitiesDirs` and `entitiesDirsTs` are removed in favour of `entities` and `entitiesTs`.
Closes #605

feat(core): support globs in `entities`

---

docs/docs/lifecycle-hooks.md
packages/core/src/entity/EntityFactory.ts
packages/core/src/events/EventManager.ts
packages/core/src/events/EventSubscriber.ts
packages/core/src/unit-of-work/ChangeSet.ts
packages/core/src/unit-of-work/ChangeSetComputer.ts
packages/core/src/unit-of-work/UnitOfWork.ts
tests/EntityManager.mysql.test.ts
tests/entities-sql/Author2.ts

Lifecycle hooks are now executed the same way as `EntitySubscriber`s, this means that they
will also get the `EventArgs` in the parameters.
`EventArgs` now also optionally contain the `ChangeSet` object, so it is possible to get
the information about what fields actually changed or access the original entity data.
Closes #622

feat(core): execute hooks via `EventManager`

---

docs/docs/lifecycle-hooks.md
packages/core/src/entity/EntityFactory.ts
packages/core/src/events/EventManager.ts
packages/core/src/events/EventSubscriber.ts
packages/core/src/events/EventType.ts
packages/core/src/unit-of-work/UnitOfWork.ts
tests/EntityManager.mysql.test.ts
tests/UnitOfWork.test.ts
tests/bootstrap.ts
tests/entities-sql/Author2.ts
tests/subscribers/FlushSubscriber.ts

There is a special kind of events executed during the commit phase (flush operation).
They are executed before, during and after the flush, and they are not bound to any
entity in particular.
- `beforeFlush` is executed before change sets are computed, this is the only
event where it is safe to persist new entities.
- `onFlush` is executed after the change sets are computed.
- `afterFlush` is executed as the last step just before the `flush` call resolves.
it will be executed even if there are no changes to be flushed.
Flush event args will not contain any entity instance, as they are entity agnostic.
They do contain additional reference to the `UnitOfWork` instance.
Closes #637

feat(core): add support for flush events

---

docs/docs/configuration.md
docs/docs/entity-manager.md
docs/docs/repositories.md
docs/docs/unit-of-work.md
docs/docs/upgrading-v3-to-v4.md
docs/docs/usage-with-nestjs.md
packages/core/src/EntityManager.ts
packages/core/src/entity/EntityRepository.ts
packages/core/src/entity/EntityValidator.ts
packages/core/src/utils/Utils.ts
tests/EntityManager.mariadb.test.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite.test.ts
tests/EntityManager.sqlite2.test.ts
tests/EntityRepository.test.ts
tests/bootstrap.ts
tests/composite-keys.mysql.test.ts
tests/issues/GH349.test.ts
tests/issues/GH401.test.ts
tests/issues/GH493.test.ts

`persist()` and `remove()` are now sync methods that only mark the entity for
persistence or removal. They now return the `EntityManager` to allow fluid flushing:
```typescript
// before
await em.persist(jon, true);
await em.remove(Author, jon, true);
// after
await em.persist(jon).flush();
await em.remove(jon).flush();
```
Additionally `remove()` method now requires entity instances.
The `em.remove()` method originally allowed to pass either entity instance, or
a condition. When one passed a condition, it was firing a native delete query,
without handling transactions or hooks.
In v4, the method is now simplified and works only with entity instances. Use
`em.nativeDelete()` explicitly if you want to fire a delete query instead of
letting the `UnitOfWork` doing its job.
```typescript
// …
```

refactor(core): remove flush parameter from persist and remove

---

docs/docs/decorators.md
docs/versioned_docs/version-3.5/decorators.md
docs/versioned_docs/version-3.6/decorators.md

Since mikro-orm has now composite PK support it's not true that every entity must have exactly one PK. 
Also I clarified a little bit about 'auto_increment' prop in MySQL (maybe all SQL drivers tho, I haven't checked that) since I assume it's not 100% clear, when it's set to 'auto_increment' and when it's not.

docs: improve primary key decorator section

---

packages/core/src/utils/Utils.ts

Previously this check would break if Mikro v4 was bundled via webpack.

fix(utils): ts-node check now runs in a webpack environment

---

packages/knex/src/MonkeyPatchable.ts
packages/knex/src/index.ts
packages/mariadb/src/MariaDbConnection.ts
packages/postgresql/src/PostgreSqlConnection.ts
packages/sqlite/src/SqliteConnection.ts
tests/Utils.test.ts

Moves the portions of Knex that are being monkey patched from dynamic requires to hard requires so webpack can trace them. They're optional, but each driver insists that they're received.

refactor: move monkey patchable portions of Knex to Knex package

---

docs/docs/debugging.md
docs/versioned_docs/version-3.3/debugging.md
docs/versioned_docs/version-3.4/debugging.md
docs/versioned_docs/version-3.5/debugging.md
docs/versioned_docs/version-3.6/debugging.md

As the title says, "query-params'" logger namespace is not present in the "Debugging" section(only mentioned in "Advanced configuration"). Great ORM btw!

docs: update Debugging section with query-params namespace

---

docs/docs/decorators.md
packages/core/src/decorators/Entity.ts
packages/core/src/decorators/Property.ts
packages/core/src/typings.ts
packages/knex/src/schema/SchemaGenerator.ts
tests/__snapshots__/SchemaGenerator.test.ts.snap
tests/entities-sql/Address2.ts

feat(core): add support for entity and property comment

---

packages/knex/package.json

**What's the problem this PR addresses?**
`@mikro-orm/knex` doesn't declare the optional peer dependencies declared by `knex` (https://cdn.jsdelivr.net/npm/knex@0.21.2/package.json), continues https://github.com/mikro-orm/mikro-orm/pull/645.
Didn't notice this in the first round as `@yarnpkg/doctor` doesn't report missing optional peer dependencies (https://github.com/yarnpkg/berry/blob/c7da64d2261e4565cffac3100a98218a7c67e3ef/packages/yarnpkg-doctor/sources/cli.ts#L276-L283) and I had already fixed it locally using packageExtensions(https://yarnpkg.com/configuration/yarnrc#packageExtensions) and thus forgot it add it to the PR.
**How did you fix it?**
Add the optional peer dependencies specified by `knex`

refactor: add undeclared optional peer dependencies

---

packages/mysql-base/package.json

**What's the problem this PR addresses?**
`@mikro-orm/mysql-base` is missing a optional peer dependency on `mysql2` which it inherits from `@mikro-orm/knex` (added in https://github.com/mikro-orm/mikro-orm/pull/673)
Continues https://github.com/mikro-orm/mikro-orm/pull/645 and https://github.com/mikro-orm/mikro-orm/pull/673
**How did you fix it?**
Add undeclared optional peer dependency `mysql2` to `

refactor(mysql-base): add missing optional peer dependency

---

packages/core/src/enums.ts
packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
tests/QueryBuilder.test.ts

Extend OrderBy funcionality. See [#675  ](https://github.com/mikro-orm/mikro-orm/issues/675)

feat(core): add support for ordering by NULLS

---

packages/core/src/connections/Connection.ts

Logger doesn't actually log anything by default, and highlight is enabled by default, so this combination resulted in colorizing logs that are then not actually logged. In order to keep the default as highlight: true but perform better in the default case,  we now bail out of logQuery before doing the highlighting if the logger won't log anything anyway.

enhancement(core): Improve query performance when logging is disabled

---

packages/core/src/EntityManager.ts
packages/core/src/entity/ArrayCollection.ts
packages/core/src/entity/Collection.ts
packages/core/src/entity/EntityRepository.ts
packages/core/src/entity/Reference.ts
packages/core/src/hydration/ObjectHydrator.ts
tests/EntityFactory.test.ts

Previously `em.create()` did not handle collection updates correctly, basically ignoring all the
values if the property was not M:N owning side.
With this fix, both `em.create()` and `wrap(e).assign()` properly handled collection updates,
including propagation to the owning sides.
Closes #678

fix(core): fix `em.create()` with deeply nested data

---

packages/core/src/entity/Collection.ts
packages/core/src/unit-of-work/ChangeSetComputer.ts
packages/core/src/unit-of-work/UnitOfWork.ts
packages/core/src/utils/Utils.ts
packages/knex/src/AbstractSqlDriver.ts
tests/EntityFactory.test.ts
tests/EntityHelper.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/issues/GH467.test.ts

Previously only initialized items were allowed to be persisted when adding to
1:m collection, due to how propagation works. With this change we now allow
having inverse side collections dirty as well, firing single update query
for those if we see the items are now initialized.
Closes #467

feat(core): allow persisting 1:m collections

---

packages/core/src/connections/Connection.ts
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/knex/src/AbstractSqlConnection.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/QueryBuilderHelper.ts
packages/mongodb/src/MongoConnection.ts
packages/mongodb/src/MongoDriver.ts
tests/DatabaseDriver.test.ts
tests/EntityManager.mariadb.test.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite.test.ts
tests/QueryBuilder.test.ts

This method can be used for bulk inserts. It works in all existing drivers,
but has some limitations in SQLite and MySQL/MariaDB. Those drivers do not
return all the just created PKs.
MySQL/MariaDB will return PK of the first entity in the batch. If we have
`innodb_autoinc_lock_mode` set to 0/1 it is possible to compute the following
PKs simply by incrementing the first PK value.
(see https://stackoverflow.com/a/16592867/3665878)
SQLite on the other hand will return only the last PK.
Postgres and MongoDB both return all the PKs in the `res.rows` array.
Related: #442

feat(core): add `driver.nativeInsertMany()` method

---

packages/core/src/EntityManager.ts
packages/core/src/index.ts
packages/core/src/typings.ts
packages/knex/src/SqlEntityManager.ts
packages/mongodb/src/MongoEntityManager.ts
tests/EntityManager.mongo.test.ts
tests/entities/Author.ts

This allows to pass the type of your custom repository in the entity definition,
which will be then used in `em.getRepository(Entity)`.
```typescript
@Entity({ customRepository: () => AuthorRepository })
export class Author {
[EntityRepositoryType]?: AuthorRepository;
}
const repo = em.getRepository(Author); // repo has type AuthorRepository
```
Related: #696

feat(core): add `EntityRepositoryType` symbol

---

docs/docs/transactions.md
packages/core/src/EntityManager.ts
packages/core/src/connections/Connection.ts
packages/knex/src/AbstractSqlConnection.ts
packages/mongodb/src/MongoConnection.ts
tests/Connection.test.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts

This brings back the explicit `begin/commit/rollback` way of handling
transactions (similar to what we had in v2).
```typescript
const em = orm.em.fork(false);
await em.begin();
try {
//... do some work
const user = new User(...);
user.name = 'George';
em.persist(user);
await em.commit(); // will flush before making the actual commit query
} catch (e) {
await em.rollback();
throw e;
}
```

feat(core): add `em.begin/commit/rollback` methods

---

packages/core/src/EntityManager.ts

Before for every new context an EM was created with a new EventManager.
This EventManager would only use EventSubscribers that were annotated or explicitly defined in the
config.
Now the EventManager from the global EM is reused in every context specific EM.
Thereby lazy registeren EventSubscribers are also listening to events.
I did take a slight different approach then was suggested here https://github.com/mikro-orm/mikro-orm/issues/711#issuecomment-671087399. This I did to preserve the readonly property and keep the code cleaner (in my perspective). Hope you agree and otherwise we'll make changes.

fix: use lazy registered EventSubscribers

---

packages/core/src/unit-of-work/ChangeSetPersister.ts
packages/core/src/unit-of-work/UnitOfWork.ts
tests/EntityManager.mysql.test.ts
tests/UnitOfWork.test.ts
tests/issues/GH369.test.ts
tests/issues/GH482.test.ts

UoW will now group change sets based on the type and entity. Instead of ordering
all the change sets based on the type and entity, we can now travers those groups
based on the commit order.
Related: #732

perf(core): implement bulk deletes

---

package.json
packages/core/src/EntityManager.ts
packages/core/src/entity/Collection.ts
packages/core/src/entity/EntityAssigner.ts
packages/core/src/entity/EntityFactory.ts
packages/core/src/entity/EntityLoader.ts
packages/core/src/hydration/Hydrator.ts
packages/core/src/hydration/ObjectHydrator.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/unit-of-work/ChangeSetPersister.ts
packages/core/src/utils/QueryHelper.ts
packages/core/src/utils/Utils.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/QueryBuilder.ts
tests/EntityAssigner.mongo.test.ts
tests/EntityFactory.test.ts
tests/EntityHelper.mongo.test.ts
tests/EntityRepository.test.ts
tests/QueryBuilder.test.ts
tests/SmartQueryHelper.test.ts
tests/composite-keys.mysql.test.ts
tests/embedded-entities.mongo.test.ts
tests/issues/GH446.test.ts

This changes internal mechanism of `em.merge()`. Originally it was using
`EntityAssigner` inside `em.merge()` together with `UoW.merge()`, which
was called twice. Because of this, the custom types were processed multiple
times, and the value passed to conversion method was often already converted.
Now we use only the `Hydrator` for this. As a sideproduct of those changes,
we can now query by custom types.
```typescript
class UuidBinaryType extends Type<string, Buffer> {
convertToDatabaseValue(value: string): Buffer {
return Buffer.from(parse(value));
}
convertToJSValue(value: Buffer): string {
return stringify(value);
}
getColumnType(): string {
return 'binary(16)';
}
}
@Entity()
class A {
@PrimaryKey({ type: UuidBinaryType })
id: string = v4();
}
const a = await em.find(A, { id: '...' …
```

feat(core): refactor merging to allow querying by custom type

---

docs/docs/migrations.md
packages/cli/src/commands/MigrationCommandFactory.ts
packages/migrations/src/Migrator.ts
tests/Migrator.test.ts
tests/__snapshots__/Migrator.test.ts.snap

If you want to start using migrations, and you already have the schema generated,
you can do so by creating so called initial migration:
> Initial migration can be created only if there are no migrations previously
> generated or executed.
```sh
npx mikro-orm migration:create --initial
```
This will create the initial migration, containing the schema dump from
`schema:create` command. The migration will be automatically marked as executed.
Closes #772

feat(migrations): add support for initial migrations

---

packages/core/src/EntityManager.ts
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/entity/ArrayCollection.ts
packages/core/src/entity/Collection.ts
packages/core/src/entity/EntityAssigner.ts
packages/core/src/entity/EntityFactory.ts
packages/core/src/entity/EntityHelper.ts
packages/core/src/entity/EntityLoader.ts
packages/core/src/entity/EntityTransformer.ts
packages/core/src/entity/EntityValidator.ts
packages/core/src/entity/Reference.ts
packages/core/src/entity/WrappedEntity.ts
packages/core/src/events/EventManager.ts
packages/core/src/hydration/Hydrator.ts
packages/core/src/hydration/ObjectHydrator.ts
packages/core/src/index.ts
packages/core/src/metadata/EntitySchema.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/typings.ts
packages/core/src/unit-of-work/ChangeSetComputer.ts
packages/core/src/unit-of-work/ChangeSetPersister.ts
packages/core/src/unit-of-work/UnitOfWork.ts
packages/core/src/utils/EntityComparator.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/CriteriaNode.ts
packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
tests/EntityFactory.test.ts
tests/EntityHelper.mongo.test.ts
tests/SchemaGenerator.test.ts

Various small performance improvements:
- adding meta.root to get rid of excessive usage of `Utils.getRootEntity()`
- store lists of properties on metadata instead of using `Object.values()` all the time
- use Set instead of array for change sets and extra updates
- improve lookup of extra updates
- simplify entity diffing via precomputed `prop.comparable`
- add hot path for `em.persist()` when its called with single entity
Related: #732

perf: move reference to metadata to entity prototype + more improvements

---

packages/core/src/typings.ts

**What's the problem this PR addresses?**
Using a filter with an async condition shows a type error that the return type is invalid
**How did you fix it?**
Update the type definition for `FilterDef.cond` to allow returning a `Promise<FilterQuery<T>>`

fix(core): update filter typing to allow async condition

---

packages/core/src/entity/ArrayCollection.ts
packages/core/src/entity/Collection.ts
packages/core/src/platforms/Platform.ts
packages/core/src/unit-of-work/ChangeSetPersister.ts
packages/core/src/utils/Configuration.ts
packages/knex/src/query/QueryBuilderHelper.ts
packages/knex/src/query/ScalarCriteriaNode.ts
packages/mongodb/src/MongoPlatform.ts
packages/postgresql/src/PostgreSqlPlatform.ts
packages/sqlite/src/SqlitePlatform.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite.test.ts
tests/EntityManager.sqlite2.test.ts
tests/QueryBuilder.test.ts

UoW will now batch all inserts statements if the driver supports returning all of their
PKs back (so postgres and mongodb currently).
This also changes how `Collection.contains()` was implemented - it did a linear check
on all values, comparing by the PK for persisted entities. This took extreme amount of
time with huge collections, just to add to a collection 1000 times, it was as slow as
1s for this, without persisting anything.
Now the collection items are stored as `Set`, and `contains` method does a simple identity
lookup (`set.has(entity)`). Another issue that slowed it down was the array like index support,
where we are able to use `coll[0]` to access the first item in the collection. This was
implemented as a re-assigning of all items to the collection object, which was extremely …

perf(core): use batch inserts in UoW (postgres & mongodb)

---

packages/knex/src/schema/SchemaHelper.ts

This PR changes hasSameType function in order of add support for type as:
```
numeric(18,4)
```
so that they do not constantly change during migration

fix(schema): improve column type equality check

---

docs/docs/embeddables.md
packages/core/src/decorators/Embedded.ts
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/hydration/ObjectHydrator.ts
packages/core/src/metadata/EntitySchema.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/metadata/MetadataStorage.ts
packages/core/src/platforms/Platform.ts
packages/core/src/types/EnumArrayType.ts
packages/core/src/typings.ts
packages/core/src/utils/EntityComparator.ts
packages/knex/src/AbstractSqlPlatform.ts
packages/knex/src/query/QueryBuilderHelper.ts
packages/knex/src/schema/SchemaGenerator.ts
packages/knex/src/schema/SchemaHelper.ts
packages/mongodb/src/MongoDriver.ts
packages/mysql-base/src/MySqlPlatform.ts
tests/SchemaGenerator.test.ts
tests/__snapshots__/embedded-entities.mysql.test.ts.snap
tests/embedded-entities.mongo.test.ts
tests/embedded-entities.mysql.test.ts

```ts
@Entity()
export class User {
@Embedded({ entity: () => Address, object: true })
address!: Address;
}
```
In SQL drivers, this will use a JSON column to store the value.
> Only MySQL and PostgreSQL drivers support searching by JSON properties currently.
Closes #906

feat(core): allow storing embeddables as objects

---

docs/docs/deployment.md
docs/versioned_docs/version-4.2/deployment.md

- devDependencies defaults to empty object - @mikro-orm/core doesn't have devDependecies in its package.json so webpack throws error
- check is optional package is not like @mikro-orm/... - like all database adapters dependencies - if so than check extended name  (@mikro-orm/mssql) in optional dependencies

docs: update deployment webpack config due to v4 release

---

packages/core/src/EntityManager.ts
packages/core/src/entity/EntityRepository.ts
packages/core/src/utils/TransactionContext.ts
packages/core/src/utils/index.ts
packages/knex/src/SqlEntityRepository.ts
packages/mongodb/src/MongoEntityRepository.ts
tests/EntityManager.sqlite2.test.ts
tests/EntityRepository.test.ts

Domain API is now used behind the scenes to automatically bare the tx context. This means
we can now use any EM, repository or a service (from DI), regardless of what EM instance
they were created from.
```ts
// this repo is based on `orm.em`, but thanks `TransactionContext` helper,
// it will use the right EM behind the scenes when used inside `em.transactional()`
const repo = orm.em.getRepository(Author4);
await orm.em.transactional(async () => {
const a = await repo.findOneOrFail(god1);
a.name = 'abc';
});
```

feat(core): maintain transaction context automatically

---

docs/docs/query-builder.md
packages/core/src/drivers/DatabaseDriver.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
packages/mongodb/src/MongoDriver.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.sqlite2.test.ts
tests/QueryBuilder.test.ts

To select multiple entities and map them from `QueryBuilder`, we can use
`joinAndSelect` or `leftJoinAndSelect` method:
```ts
// `res` will contain array of authors, with books and their tags populated
const res = await orm.em.createQueryBuilder(Author, 'a')
.select('*')
.leftJoinAndSelect('a.books', 'b')
.leftJoinAndSelect('b.tags', 't')
.where({ 't.name': ['sick', 'sexy'] })
.getResultList();
```
Closes #932

feat(query-builder): allow mapping of complex joined results

---

packages/core/src/metadata/MetadataDiscovery.ts

when the base class has properties that are also defined in the child class with different options (e.g. nullable or not nullable). the base class property would just override the child properties.
with this change the properties will be filtered out by name and allow the child class to keep its own property definitions while inheriting others from the parent

fix(core): do not override child class properties

---

packages/core/src/EntityManager.ts
packages/core/src/entity/EntityValidator.ts
packages/core/src/metadata/MetadataStorage.ts
tests/issues/GH997.test.ts

Inherited props of STI entities shouldn't be validated because they don't exist in real entity definition.
Closes #997

fix(validation): don't validate inherited STI props

---

packages/mysql-base/src/MySqlSchemaHelper.ts

It is exactly the same issue as #398 with exactly the same solution. This caused https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/schema/SchemaHelper.ts#L112 to return
```
{
"undefined": {
"columnName": undefined,
"constraintName": undefined,
"referencedTableName": undefined,
"referencedColumnName":  undefined,
"updateRule": undefined,
"deleteRule": undefined
}
}
``` 
for all found foreign keys causing all foreign keys to be dropped and re-added.

fix(schema): fix diffing FKs in MySQL 8

---

packages/cli/package.json

**What's the problem this PR addresses?**
`@mikro-orm/cli` has a direct dependency on `@mikro-orm/core` which makes it inherit its peer dependencies but they're not declared as such.
**How did you fix it?**
Explicitly declare the missing optional peer dependencies

fix(cli): add missing peer dependencies

---

docs/docs/inheritance-mapping.md
docs/versioned_docs/version-4.0/inheritance-mapping.md
docs/versioned_docs/version-4.1/inheritance-mapping.md
docs/versioned_docs/version-4.2/inheritance-mapping.md

Changed the extended class name from `Base` to `BasePerson`
```ts
@Entity()
export class Person extends Base {
// ...
}
```
```ts
@Entity()
export class Person extends BasePerson {
// ...
}
```

docs(inheritance-mapping): change extended class name

---

packages/core/src/entity/EntityAssigner.ts
tests/embedded-entities.mongo.test.ts

This fixes entity assign not merging embedded properties when the source has a prototype.
Closes #1083

fix(core): assign embedded properties from class objects

---

docs/docs/deployment.md

I've found that Terser, in some cases, also changes function and class names during its compression phase, even though mangling is disabled. This can cause trouble in some relations and table naming.
This is apparently also documented over at https://terser.org/docs/api-reference.html#mangle-options.
This PR is a minuscule addition to the docs that provides the proper options to Terser to avoid any issues occurring in production.

docs: extra flags on Terser/Webpack configuration

---

docs/blog/2020-09-08-mikro-orm-4-released.md
docs/docs/lifecycle-hooks.md
docs/versioned_docs/version-4.0/lifecycle-hooks.md
docs/versioned_docs/version-4.1/lifecycle-hooks.md
docs/versioned_docs/version-4.2/lifecycle-hooks.md
docs/versioned_docs/version-4.3/lifecycle-hooks.md

As discussed on Slack, the type is meant to be `Author` throughout the example.

docs: fix conflicting type argument

---

packages/core/src/EntityManager.ts
packages/core/src/connections/Connection.ts
packages/core/src/enums.ts
packages/core/src/events/EventManager.ts
packages/core/src/events/EventSubscriber.ts
packages/core/src/events/TransactionEventBroadcaster.ts
packages/core/src/events/index.ts
packages/core/src/unit-of-work/UnitOfWork.ts
packages/knex/src/AbstractSqlConnection.ts
packages/mongodb/src/MongoConnection.ts
tests/issues/GH1175.test.ts
tests/issues/GH1176.test.ts

Current lifecycle hooks cover entity and unit of work events, but
transaction-related ones are missing. Add beforeTransactionStart,
afterTransactionStart, beforeTransactionCommit, afterTransactionCommit,
beforeTransactionRollback, and afterTransactionRollback
Closes #1175
---
Although #1175 mentions implementing "after" entity hooks post commit, they are not included in this PR as they are not needed. Refer to the `UserSubscriber` example class in test file `GH1175.test.ts` to see how to implement an ad-hoc `afterCommitCreate` hook using a combination of `afterTransactionStart`, `afterCreate`, and `afterTransactionCommit`.
Currently, all this PR is missing right now is documentation. Please let me know if you need me to do that as well, but I was thinking maybe @B4nan could lend a hand …

feat(core): implement transaction lifecycle hooks

---

packages/knex/src/query/QueryBuilder.ts

As evidenced by the first line of the method, `path` can be falsy. This PR updates the parameter type accordingly.

fix: correct type for getAliasForJoinPath argument

---

packages/core/src/utils/Utils.ts
tests/Utils.test.ts

When passing a `Set<Foo>` into `em.persist()` for example, the TS check would accept it as an argument, but a `Set` is no actually expected.
This change allows for `Set`s to be treated like `Array`s wherever `Utils.asArray` is utilized to inspect inputs.

feat(core): support handling `Set` as array-like input

---

packages/knex/src/schema/SchemaGenerator.ts
packages/mysql-base/src/MySqlSchemaHelper.ts
tests/issues/GH1271.test.ts
tests/issues/__snapshots__/GH1271.test.ts.snap

Possibly fixes #1271 
Added logic to the `getIndexName` method to truncate index name (and add some random string to avoid duplication) if index name will go past 64 chars.
For FK, I found that the `TableBuilder` interface in knex has a `withKeyName` method that we can use to override the FK name.

fix(mysql): enforce 64 character limit for identifier names in SQL

---

docs/docs/entity-manager.md
docs/versioned_docs/version-4.3/entity-manager.md
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/entity/EntityLoader.ts
packages/knex/src/AbstractSqlDriver.ts
packages/mongodb/src/MongoDriver.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/partial-loading.mongo.test.ts
tests/partial-loading.mysql.test.ts

Adds support for nested partial loading:
```ts
const author = await orm.em.findOne(Author, '...', { fields: ['name', 'books.title', 'books.author', 'books.price'] });
```
Or with alternative object syntax:
```ts
const author = await orm.em.findOne(Author, '...', { fields: ['name', { books: ['title', 'author', 'price'] }] });
```
It is also possible to use multiple levels:
```ts
const author = await orm.em.findOne(Author, '...', { fields: ['name', { books: ['title', 'price', 'author', { author: ['email'] }] }] });
```
Primary keys are always selected even if you omit them. On the other hand, you are responsible 
for selecting the FKs - if you omit such property, the relation might not be loaded properly.
In the following example the books would not be linked the author, because we did not …

feat(core): add support for nested partial loading

---

docs/docs/entity-manager.md
packages/core/src/EntityManager.ts
packages/core/src/drivers/IDatabaseDriver.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.sqlite2.test.ts

Sometimes we might want to disable identity map and change set tracking for some query.
This is possible via `disableIdentityMap` option. Behind the scenes, it will create new
context, load the entities inside that, and clear it afterwards, so the main identity map
will stay clean.
```ts
const users = await orm.em.find(User, { email: 'foo@bar.baz' }, {
disableIdentityMap: true,
populate: { cars: { brand: true } },
});
users[0].name = 'changed';
await orm.em.flush(); // calling flush have no effect, as the entity is not managed
```
> Keep in mind that this can also have
> [negative effect on the performance](https://stackoverflow.com/questions/9259480/entity-framework-mergeoption-notracking-bad-performance).
Closes #1267

feat(core): allow disabling identity map and change set tracking

---

docs/docs/embeddables.md
packages/core/src/decorators/Embedded.ts
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/entity/EntityAssigner.ts
packages/core/src/errors.ts
packages/core/src/hydration/ObjectHydrator.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/utils/EntityComparator.ts
packages/knex/src/query/CriteriaNodeFactory.ts
packages/knex/src/schema/SchemaGenerator.ts
packages/mysql-base/src/MySqlPlatform.ts
packages/postgresql/src/PostgreSqlPlatform.ts
tests/__snapshots__/nested-embeddables.mongo.test.ts.snap
tests/__snapshots__/nested-embeddables.postgres.test.ts.snap
tests/nested-embeddables.mongo.test.ts
tests/nested-embeddables.postgres.test.ts

Embeddables can now be nested, both in object and inlined mode. The mode of the root
embedded property is always propagated, e.g. there is no way to nest object embeddable
inside inlined one and vice versa.
`assign` helper now also allows using `mergeObjects` with embeddadble properties.
Closes #1017

feat(core): add support for nested embedddables

---

packages/knex/src/AbstractSqlDriver.ts
tests/issues/GH1331.test.ts
tests/joined-strategy.postgre.test.ts

Merges a joined relation's orderBy with the parent's, keeping tableAliases in mind. Fixes #1331

fix(sql): sort fetch-joined properties on their orderBy

---

packages/entity-generator/src/SourceFile.ts
tests/__snapshots__/EntityGenerator.test.ts.snap

Updates the generator to emit the collection name when it doesn't match the namingStrategy output.
Closes: #1328

fix(entity-generator): emit collection name in decorator

---

packages/core/src/entity/EntityAssigner.ts
tests/embedded-entities.mysql.test.ts

When you have entity like this:
```
@Entity()
class Document extends BaseEntity<Document> {
...
@Embedded({
entity: () => Summary,
nullable: true,
})
summary!: Summary;
...
}
```
and do this:
```
document.assign({summary: null}, { mergeObjects: true });
```
it explode with:
```
Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at Function.assignEmbeddable (***/node_modules/@mikro-orm/core/entity/EntityAssigner.js:108:16)
```
thank you very much for your great work!

fix(core): allow assigning null to embeddable property

---

packages/migrations/src/Migrator.ts
tests/Migrator.test.ts
tests/__snapshots__/Migrator.postgres.test.ts.snap
tests/__snapshots__/Migrator.test.ts.snap

Migrations are still being created with `migrator.createMigration()` even if there is no schema diff. The current implementation of getSchemaDiff returns an Array with an empty string inside for an empty string as schema diff.

fix(migrations): fix generation of empty migrations

---

docs/docs/json-properties.md
docs/sidebars.js
docs/versioned_docs/version-4.4/json-properties.md
docs/versioned_sidebars/version-4.4-sidebars.json
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/platforms/Platform.ts
packages/core/src/utils/QueryHelper.ts
packages/knex/src/AbstractSqlPlatform.ts
packages/mysql-base/src/MySqlPlatform.ts
packages/postgresql/src/PostgreSqlPlatform.ts
packages/sqlite/src/SqlitePlatform.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite2.test.ts
tests/entities-schema/Book4.ts
tests/entities-sql/Book2.ts
tests/entities/Book.ts

We can query by JSON object properties easily:
```ts
const b = await em.findOne(Book, {
meta: {
valid: true,
nested: {
foo: '123',
bar: 321,
deep: {
baz: 59,
qux: false,
},
},
},
});
```
Will produce following query (in postgres):
```sql
select "e0".*
from "book" as "e0"
where ("meta"->>'valid')::bool = true
and "meta"->'nested'->>'foo' = '123'
and ("meta"->'nested'->>'bar')::float8 = 321
and ("meta"->'nested'->'deep'->>'baz')::float8 = 59
and ("meta"->'nested'->'deep'->>'qux')::bool = false
limit 1
```
> All drivers are currently supported (including sqlite and mongo). In postgres we
> also try to cast the value if we detect number or boolean on the right-hand side.
Closes #1359
Related: #1261

feat(core): allow querying by JSON properties

---

docs/docs/custom-types.md
docs/versioned_docs/version-4.4/custom-types.md
packages/core/src/platforms/Platform.ts
packages/core/src/types/Type.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/QueryBuilderHelper.ts
tests/DatabaseDriver.test.ts
tests/custom-types.test.ts

Adds two methods to the custom type interface that allows to adjust the SQL fragment
used to select or update the value.
Example usage:
```ts
export class PointType extends Type<Point, string> {
convertToDatabaseValue(value: Point): string {
return `point(${value.latitude} ${value.longitude})`;
}
convertToJSValue(value: string): Point {
const m = value.match(/point\((\d+(\.\d+)?) (\d+(\.\d+)?)\)/i);
return new Point(+m[1], +m[3]);
}
convertToJSValueSQL(key: string) {
return `ST_AsText(${key})`;
}
convertToDatabaseValueSQL(key: string) {
return `ST_PointFromText(${key})`;
}
getColumnType(): string {
return 'point';
}
}
```
Closes #735

feat(core): allow using SQL expressions with custom types

---

packages/knex/src/query/QueryBuilderHelper.ts
tests/custom-types.test.ts

My custom properties are not getting mapped well because in Postgres casing is ignored for identifiers unless quoted.
The mapper uses the alias to map the results back to the entity and the results are getting lost because it's all lower case.
In other words, the compiled mapping function fails:
if ('my_custom_prop' in result) { ret.myCustomProp = result.my_custom_prop; mapped.my_custom_prop = true; 
Because `result.mycustomprop` is not matched against the rule, and the generic treatment at the end of the mapping function also fails because it mappes the value into a property that doesn't exist:
for (let k in result) { if (result.hasOwnProperty(k) && !mapped[k]) ret[k] = result[k]; }
I added the plaform quotes for the custom type alias.

fix(core): quote custom type aliases

---

README.md
docs/docs/quick-start.md
docs/docs/repositories.md

I found it was documented as `sort:` but the only way I managed to compile it is with `orderBy:`.
I'm not sure if it ever was `sort:` in the past so older versions of the docs may be wrong as well.

Fix documentation for orderBy

---

packages/core/src/unit-of-work/ChangeSetComputer.ts

I was having a performance issue while saving a large list of entities having oneToMany Collection. on Debugging it turned out that processToMany method inside ChangeSetComputer.ts is taking a lot of time due to unnecessary looping through filter even if there are not items in removeStack. This quick fix will prevent running it unnecessarily. I have noticed a major performance improvement after introducing this check.

perf(core): improve processing of 1:m relations

---

docs/docs/cascading.md
docs/docs/repositories-api.md
docs/versioned_docs/version-4.4/cascading.md
docs/versioned_docs/version-4.4/repositories-api.md

Replace references to old `removeEntity` method with the current `remove` method.

docs: replace old removeEntity references

---

docs/docs/defining-entities.md
docs/versioned_docs/version-4.4/defining-entities.md

Hi,
I think this should be `export class Book extends BaseEntity<Book, 'id'> { ... }`. There's a `Book` declaration at the bottom of [entity-helper.md](https://github.com/mikro-orm/mikro-orm/blob/master/docs/versioned_docs/version-4.4/entity-helper.md) that has the correct code.

docs: update defining-entities section

---

docs/docs/installation.md
packages/core/src/utils/ConfigurationLoader.ts
tests/cli/CLIHelper.test.ts

The use case is - when I need to get my connection information from a remote system (Secret Store, Microservice etc.)

feat(cli): allow mikro-orm config to return Promise

---

.eslintrc.js
docs/docs/collections.md
packages/core/src/entity/Collection.ts
packages/core/src/errors.ts
packages/knex/src/AbstractSqlDriver.ts
tests/EntityManager.sqlite2.test.ts

Collections now have a `matching` method that allows to slice parts of data from a collection.
By default, it will return the list of entities based on the query. We can use the `store`
boolean parameter to save this list into the collection items - this will mark the
collection as `readonly`, methods like `add` or `remove` will throw.
```ts
const a = await em.findOneOrFail(Author, 1);
// only loading the list of items
const books = await a.books.matching({ limit: 3, offset: 10, orderBy: { title: 'asc' } });
console.log(books); // [Book, Book, Book]
console.log(a.books.isInitialized()); // false
// storing the items in collection
const tags = await books[0].tags.matching({
limit: 3,
offset: 5,
orderBy: { name: 'asc' },
store: true,
});
console.log(tags); // [BookTag, BookTag, BookTag] …
```

feat(core): add `Collection.matching()` method to allow pagination

---

docs/docs/entity-helper.md
packages/core/src/entity/EntityAssigner.ts
tests/EntityAssigner.mysql.test.ts

Currently, when you do the following:
```
const authorEntity = new Author('Jon2 Snow', 'snow3@wall.st');
book.author = authorEntity;
wrap(book).assign({ author: { name: 'Jon Snow2' } }, { mergeObjects: true });
console.log(book.author); // { ... name: 'Jon Snow2' ... }
console.log(book.author === authorEntity) // false
```
... it will try to create a new author entity with the name Jon Snow2 altough it can assign these values to the existing m:1 reference. Was doubting to fix the functionality for the mergeObjects flag, however that may be a breaking change.
Right now, it will only update loaded references; should I also implement initializing the enitity and then asssign the new values?

feat(core): allow updating nested 1:1 and m:1 references with EntityAssigner

---

packages/core/src/utils/Utils.ts
tests/issues/GH1626.test.ts

This PR adds bigint as acceptable type of `isPrimaryKey`.
I was following https://mikro-orm.io/docs/using-bigint-pks recipe, but saw that `update` queries were missing `where` clause when using bigint as PK.
I've pinpointed issue to those lines that doesn't prepare correct `where` object for knex when `where` is of bigint type.
https://github.com/mikro-orm/mikro-orm/blob/c0c658eb125695bd1aed760aa95f2eadc1da8d43/packages/knex/src/AbstractSqlDriver.ts#L270-L272

fix: bigint as primary key

---

packages/knex/src/query/QueryBuilderHelper.ts
tests/features/custom-types.test.ts

Fixes SQL queries using custom types as find conditions.
Field `mapper` was adding unnecessary aliases in where clause creating invalid SQL syntax:
```
... where T_AsText(`e0`.`point`) as point = 'point(1 1)' 
```
and now it's
```
... where T_AsText(`e0`.`point`) = 'point(1 1)' 
```

fix(knex): find entity by advanced custom types

---

packages/knex/src/query/QueryBuilderHelper.ts
tests/features/embeddables/__snapshots__/embedded-entities.postgres.test.ts.snap
tests/features/embeddables/embedded-entities.postgres.test.ts

When within an embedded entity a numeric query is performed on a numeric field, the query is malformed:
`SyntaxErrorException: select "e0".* from "user" as "e0" where "e0".("address4"->>'number')::float8 > 2 limit 1 - syntax error at or near "("`
in this change the query builder prefix function detects if the field name has parenthesis, to add the alias inside

fix(core): fix querying embeddables over cast fields

---

packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
tests/features/embeddables/embedded-entities.postgres.test.ts

…query over embedded field
When I perform a nativeUpdate as
```typescript
await orm.em.nativeUpdate(User, {
address4: {
number: {
$gt: 2,
},
},
}, {
after: 2,
});
```
the result is:
```
TableNotFoundException: update "user" set "after" = 2 where ("e0"."address4"->>'number')::float8 > 2 - missing FROM-clause entry for table "e0"
```
this pr refactors some checks on whether it is necessary to include a prefix based on the type of operation and it puts the decision in a single method.
Thank you for your excellent work!

fix(core): fix aliasing of embeddables in update query

---

packages/knex/src/query/QueryBuilderHelper.ts
tests/features/custom-types.test.ts

When using queries with conditions in custom types an alias gets appended in the `where` expression for the type.
```
const foundLocation = await orm.em.findOne(Location, {
point: new Point(1, 1),
extendedPoint: { $ne: null },
});
```

fix(knex): find by custom types with object subconditions

---

docs/docs/configuration.md

Change "refrences" to "references".

docs: fix typo

---

docs/docs/usage-with-nestjs.md

doc: fix typos in NestJS docs

---

packages/core/src/EntityManager.ts
packages/core/src/entity/BaseEntity.ts
packages/core/src/entity/EntityAssigner.ts
packages/core/src/entity/EntityTransformer.ts
packages/core/src/entity/wrap.ts
packages/core/src/index.ts
packages/core/src/typings.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/entities-sql/Test2.ts
tests/entities/Author.ts
tests/entities/Book.ts
tests/issues/GH222.test.ts
tests/types.test.ts

`toObject()`, `toJSON()` and `toPOJO()` now all return `EntityDTO` type, that is strict,
so it allows (deep) key autosuggestions.
The implementation is a best effort, as the serialized form of an entity can be very unpredictable.
There are many variables that define how things will be serialized, e.g. loaded entity vs reference, 
property serializers, custom entity serializer/toJSON method, eager loading, recursion checks, ...
Currently all relations are concidered as loaded on the type level, this is mainly done to allow better
DX, as if we had all relations typed as `Primary<T> | EntityDTO<T>` (e.g. `number | EntityDTO<Book>`), it 
would be impossible to benefit from intellisense/autosuggestions. Imagine this scenario:
```ts
const book = {} as Book;
const dto = wrap(book).toObject(); // …
```

feat(typings): make `toObject()` and similar strict

---

docs/docs/migrations.md
packages/core/src/utils/Configuration.ts
packages/knex/src/schema/DatabaseSchema.ts
packages/knex/src/schema/DatabaseTable.ts
packages/knex/src/schema/SchemaComparator.ts
packages/knex/src/schema/SchemaGenerator.ts
packages/migrations/src/Migrator.ts
tests/bootstrap.ts
tests/features/migrations/Migrator.postgres.test.ts
tests/features/migrations/__snapshots__/Migrator.postgres.test.ts.snap

Creating new migration will automatically save the target schema snapshot into
migrations folder. This snapshot will be then used if you try to create new migration,
instead of using current database schema. This means that if we try to create new
migration before we run the pending ones, we still get the right schema diff.
> Snapshots should be versioned just like the regular migration files.
Snapshotting can be disabled via `migrations.snapshot: false` in the ORM config.

feat(migrations): use snapshots for generating diffs in new migrations

---

packages/cli/src/commands/DatabaseSeedCommand.ts
packages/seeder/src/seed-manager.ts
tests/database/seeder/author3.seeder.ts
tests/database/seeder/database.seeder.ts
tests/database/seeder/project.seeder.ts
tests/database/seeder/user.seeder.ts
tests/features/cli/DatabaseSeedCommand.test.ts
tests/features/seeder/run-seeders.test.ts
tests/features/seeder/seed-manager.test.ts

Seeder manager now generates seed files with `export class` and the
correct seeder name (e.g. BookSeeder) instead of the default. Also when
seeding using string it executes the exported member of default instead
of the file.
Fixes #1843

refactor(seeder): seed manager generate and seedString

---

docs/docs/entity-references.md
docs/versioned_docs/version-3.6/entity-references.md
docs/versioned_docs/version-4.0/entity-references.md
docs/versioned_docs/version-4.1/entity-references.md
docs/versioned_docs/version-4.2/entity-references.md
docs/versioned_docs/version-4.3/entity-references.md
docs/versioned_docs/version-4.4/entity-references.md
docs/versioned_docs/version-4.5/entity-references.md

docs: fix references loading with key name

---

packages/cli/src/commands/SchemaCommandFactory.ts
tests/features/cli/CreateSchemaCommand.test.ts

This is a follow up for #1843, as of `5.0.0-dev.159` `schema:create --run` still triggers default seeder without explicit `--seed` argument.

refactor: fixes issue where create schema command triggers seeder by default

---

docs/docs/entity-helper.md
packages/core/src/entity/EntityAssigner.ts
packages/core/src/typings.ts
tests/bootstrap.ts
tests/features/embeddables/embedded-entities.postgres.test.ts
tests/features/entity-assigner/EntityAssigner.mongo.test.ts
tests/features/entity-assigner/EntityAssigner.mysql.test.ts
tests/features/entity-assigner/GH1811.test.ts

Deep assigning of child entities now works by default based on the presence of PKs in the payload.
This behaviour can be disable via `updateByPrimaryKey: false` in the `assign` options.
Closes #1811

feat(core): rework deep assigning of entities and enable it by default

---

docs/docs/usage-with-nestjs.md
docs/versioned_docs/version-4.5/usage-with-nestjs.md

- bodyParser is deprecated, you need to use it via express or have an annoying deprecated warning
- forgot to disable bodyparser in nest itself 
- switched our internal module name for a more generic one

docs: improvements for body parser & request context for nest

---

docs/docs/usage-with-nestjs.md
docs/versioned_docs/version-4.5/usage-with-nestjs.md

Add more information on working with @UseRequestContext in NestJS in combination with other decorators.
There is an issue when the `UseRequestContext` is used with other decorators, in this case, the `Processor` decorator used by @nest-js/bull, where based on the order of execution, the consumers stop working.

docs: update request context docs

---

packages/cli/src/commands/MigrationCommandFactory.ts

Seed option when executing migration:fresh defaulted to empty string
and so it always tried to seed after migrating.

refactor: make seed option optional

---

packages/reflection/src/TsMorphMetadataProvider.ts

The intention seems to be to strip leading `.` to get to the significant
part of the path. Previously only a single `.` was stripped, now all of
them are stripped.
Fixes #2163

fix(reflection): relative paths not stripped completely

---

docs/docs/upgrading-v4-to-v5.md
packages/core/src/EntityManager.ts
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/unit-of-work/ChangeSetPersister.ts
packages/core/src/unit-of-work/UnitOfWork.ts
packages/knex/src/AbstractSqlDriver.ts
packages/mariadb/src/MariaDbDriver.ts
packages/migrations/src/MigrationStorage.ts
packages/mongodb/src/MongoDriver.ts
packages/mysql-base/src/MySqlDriver.ts
packages/sqlite/src/SqliteDriver.ts
tests/DatabaseDriver.test.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.postgre.test.ts

Most of the methods on `IDatabaseDriver` interface now have different signature.

refactor: use options parameters in `IDatabaseDriver`

---

docs/docs/upgrading-v4-to-v5.md
packages/core/src/decorators/ManyToMany.ts
packages/core/src/decorators/OneToMany.ts
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/entity/Collection.ts
packages/core/src/entity/EntityLoader.ts
packages/core/src/enums.ts
packages/core/src/typings.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
packages/knex/src/typings.ts
packages/mongodb/src/MongoConnection.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/QueryBuilder.test.ts
tests/entities-sql/Book2.ts
tests/features/embeddables/entities-in-embeddables.mongo.test.ts
tests/features/partial-loading/partial-loading.mongo.test.ts

`FindOptions.orderBy` parameter is now strictly typed. It also allows passing an
array of objects instead of just a single object.
```ts
const books = await em.find(Book, {}, {
orderBy: [
{ title: 1 },
{ author: { name: -1 } },
],
});
```
`FindOptions.orderBy` parameter is now strictly typed.
Closes #2010

feat(core): allow passing arrays in `orderBy` parameter

---

docs/docs/upgrading-v4-to-v5.md
packages/core/src/entity/Collection.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts

`Collection.init()` now has only options parameter

refactor: fix type of `Collection.init`

---

docs/docs/index.md
docs/docs/usage-with-adminjs.md
docs/sidebars.js
docs/versioned_docs/version-4.5/index.md
docs/versioned_docs/version-4.5/usage-with-adminjs.md
docs/versioned_sidebars/version-4.5-sidebars.json

Hello, I've been asked to create a recipe for usage with AdminJS. Please, let me know if this is fine and whether I have created/updated the required files. When I ran the development server, I had to duplicate my changes from `docs/docs/*` into `docs/versioned_docs/*` to be able to see them and it's the bit I'm actually confused about.

docs(recipes): add "Usage with AdminJS" recipe

---

packages/knex/src/schema/DatabaseTable.ts
packages/knex/src/schema/SchemaComparator.ts
packages/postgresql/src/PostgreSqlPlatform.ts
packages/sqlite/src/SqlitePlatform.ts
tests/features/schema-generator/__snapshots__/enum-foreign-key.postgres.test.ts.snap
tests/features/schema-generator/enum-foreign-key.postgres.test.ts

Resolves: #2343
I'm not super confident about this particular fix, however it does seem to revert the original behaviour back to how it worked in 4.x.

refactor: don't include enum check constraint in type

---

docs/docs/configuration.md
docs/docs/identity-map.md
docs/docs/upgrading-v4-to-v5.md
package.json
packages/core/src/EntityManager.ts
packages/core/src/MikroORM.ts
packages/core/src/errors.ts
packages/core/src/utils/Configuration.ts
packages/core/src/utils/ConfigurationLoader.ts
tests/DatabaseDriver.test.ts
tests/EntityManager.postgre.test.ts
tests/features/cli/CLIHelper.test.ts
tests/setup.ts

It is no longer possible to use the global identity map. This was a
common issue that led to weird bugs, as using the global EM without request
context is wrong, we always need to have a dedicated context for each request,
so they do not interfere.
Now we get a validation error if we try to use the global context. We still can
disable this check via `allowGlobalContext` configuration, or a connected
environment variable `MIKRO_ORM_ALLOW_GLOBAL_CONTEXT` - this can be handy
especially in unit tests.

feat(core): validate usage of global context

---

docs/docs/decorators.md
docs/docs/transactions.md
packages/core/src/decorators/Property.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/typings.ts
packages/core/src/unit-of-work/ChangeSetPersister.ts
packages/knex/src/AbstractSqlDriver.ts
tests/features/concurrency-checks/concurrency-checks.mongo.test.ts
tests/features/concurrency-checks/concurrency-checks.postgre.test.ts

As opposed to version fields that are handled automatically, we can use
concurrency checks. They allow us to mark specific properties to be included
in the concurrency check, just like the version field was. But this time, we
will be responsible for updating the fields explicitly.
When we try to update such entity without changing one of the concurrency fields,
`OptimisticLockError` will be thrown. Same mechanism is then used to check whether
the update succeeded, and throw the same type of error when not.
```ts
@Entity()
export class ConcurrencyCheckUser {
// all primary keys are by default part of the concurrency check
@PrimaryKey({ length: 100 })
firstName: string;
// all primary keys are by default part of the concurrency check
@PrimaryKey({ length: 100 })
lastName: string; …
```

feat(core): add support for concurrency checks

---

docs/docs/query-builder.md
docs/docs/upgrading-v4-to-v5.md
packages/knex/src/SqlEntityManager.ts
packages/knex/src/SqlEntityRepository.ts
packages/knex/src/query/QueryBuilder.ts
tests/EntityRepository.test.ts
tests/QueryBuilder.test.ts
tests/issues/GH572.test.ts

Since v5 we can await the `QueryBuilder` instance, which will automatically execute the QB and return appropriate response. The QB instance is now typed based on usage of `select/insert/update/delete/truncate` methods to one of:
- `SelectQueryBuilder`
- awaiting yields array of entities (as `qb.getResultList()`)
- `CountQueryBuilder`
- awaiting yields number (as `qb.getCount()`)
- `InsertQueryBuilder` (extends `RunQueryBuilder`)
- awaiting yields `QueryResult`
- `UpdateQueryBuilder` (extends `RunQueryBuilder`)
- awaiting yields `QueryResult`
- `DeleteQueryBuilder` (extends `RunQueryBuilder`)
- awaiting yields `QueryResult`
- `TruncateQueryBuilder` (extends `RunQueryBuilder`)
- awaiting yields `QueryResult`
```ts
const res1 = await em.qb(Publisher).insert({
name: 'p1',
type: …
```

feat(query-builder): allow awaiting the `QueryBuilder` instance

---

docs/docs/unit-of-work.md
packages/core/src/EntityManager.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/entity/BaseEntity.ts
packages/core/src/entity/EntityFactory.ts
packages/core/src/entity/EntityHelper.ts
packages/core/src/entity/WrappedEntity.ts
packages/core/src/enums.ts
packages/core/src/typings.ts
packages/core/src/unit-of-work/UnitOfWork.ts
packages/core/src/utils/Configuration.ts
packages/core/src/utils/EntityComparator.ts
packages/knex/src/query/QueryBuilder.ts
tests/EntityHelper.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite2.test.ts
tests/bootstrap.ts
tests/entities-sql/Book2.ts
tests/features/auto-flush.postgre.test.ts
tests/features/auto-refreshing.postgre.test.ts
tests/features/embeddables/__snapshots__/embeddable-custom-types.postgres.test.ts.snap
tests/features/embeddables/__snapshots__/entities-in-embeddables.mongo.test.ts.snap
tests/features/embeddables/__snapshots__/entities-in-embeddables.postgres.test.ts.snap
tests/features/embeddables/__snapshots__/nested-embeddables.mongo.test.ts.snap
tests/features/embeddables/__snapshots__/nested-embeddables.postgres.test.ts.snap
tests/features/embeddables/__snapshots__/polymorphic-embedded-entities.sqlite.test.ts.snap
tests/features/seeder/factory.test.ts
tests/features/single-table-inheritance/single-table-inheritance.mysql.test.ts
tests/issues/GH1523.test.ts

Checks state before querying entities and flush automatically if we have queued changes to entities that are being queried.
The flushing strategy is given by the `flushMode` of the current running `EntityManager`.
- `FlushMode.COMMIT` - The `EntityManager` tries to delay the flush until the current Transaction is committed, although it might flush prematurely too.
- `FlushMode.AUTO` - This is the default mode, and it flushes the `EntityManager` only if necessary.
- `FlushMode.ALWAYS` - Flushes the `EntityManager` before every query.
`FlushMode.AUTO` will try to detect changes on the entity we are querying, and flush
if there is an overlap:
```ts
// querying for author will trigger auto-flush if we have new author persisted
const a1 = new Author(...);
orm.em.persist(a1);
const r1 = await …
```

feat(core): implement auto-flush mode

---

docs/docs/upgrading-v4-to-v5.md
packages/core/src/EntityManager.ts
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/entity/Collection.ts
packages/core/src/enums.ts
packages/core/src/unit-of-work/ChangeSet.ts
packages/core/src/unit-of-work/UnitOfWork.ts
tests/features/unit-of-work/UnitOfWork.test.ts
tests/issues/GH1126.test.ts

Closes #1126
`UnitOfWork.getScheduledCollectionDeletions()` has been removed.
Previously scheduled collection deletions were used for a hack when removing
1:m collection via orphan removal might require early deletes - in case we were
adding the same entity (but different instance), so with same PK - inserting it
in the same unit would cause unique constraint failures.
Also `IDatabaseDriver.clearCollection()` method is no longer present in the driver API.

fix(core): rework orphan removal and cascading

---

packages/migrations/src/MigrationStorage.ts
tests/features/migrations/Migrator.test.ts

The original code stripped `test.migration.ts` to `test` instead of `test.migration`.
This resulted in migrations reverts (down) failing since the migration file `test.{ext}` does not exist.
Bug introduced in 40367166f9e74a042e2f6314f31877f27a15a14d.

refactor(migrations): prevent excessive extension stripping

---

packages/postgresql/src/PostgreSqlPlatform.ts
tests/issues/GH2583.test.ts

Adding support for pg native enum arrays, for example:
```ts
export enum WithEnumArrayValue {
First = 'first',
Second = 'second',
Third = 'third'
}
@Entity()
export class WithEnumArray {
@PrimaryKey()
id!: number;
@Enum({ name: 'values', nullable: false, items: () => WithEnumArrayValue, array: true })
values!: WithEnumArrayValue[];
}
```
Looks like it works fine, but not sure it will work for all cases.
Closes #2583

fix(postgres): fix runtime support for native pg enum arrays

---

docs/docs/seeding.md
packages/core/src/MikroORM.ts
packages/core/src/typings.ts
packages/core/src/utils/Configuration.ts
packages/knex/src/schema/SchemaGenerator.ts
packages/mongodb/src/MongoDriver.ts
packages/seeder/src/seed-manager.ts
tests/EntityManager.mongo.test.ts
tests/features/schema-generator/SchemaGenerator.mysql.test.ts
tests/features/seeder/seed-manager.test.ts

Hello
refactored seeder to be more consistent to migration package (`path` processing and default path): i think we shouldn't prepend `process.cwd()` to user provided path
deleted method `refreshDatabase`. `SchemaGenerator` exist only when user uses sql, but seeder for mongodb and custom drivers too, so user can explicit call `dropSchema` and `createSchema` methods on `SchemaGenerator`
- default seeders path: `./seeders` instead `./database/seeder` (like migrations `./migrations`). 
- removed `refreshDatabase` method on `SeedManager`

refactor(seeder): path like migrations

---

packages/core/src/utils/Utils.ts

I was no able to remove those `eslint` things on line 609-610.
This closes https://github.com/mikro-orm/mikro-orm/issues/2631#issuecomment-1013506198.
Edit: I would really appreciate if you can merge this since I really can't work on windows without this. ( only with `wsl` and that is really slow ).

refactor: fix path on windows for esmodules

---

docs/docs/usage-with-mongo.md
packages/core/src/MikroORM.ts
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/platforms/Platform.ts
packages/core/src/typings.ts
packages/core/src/utils/AbstractSchemaGenerator.ts
packages/core/src/utils/index.ts
packages/knex/src/AbstractSqlPlatform.ts
packages/knex/src/schema/SchemaGenerator.ts
packages/mongodb/src/MongoDriver.ts
packages/mongodb/src/MongoPlatform.ts
packages/mongodb/src/MongoSchemaGenerator.ts
packages/mongodb/src/index.ts
tests/DatabaseDriver.test.ts
tests/EntityManager.mongo.test.ts
tests/features/embeddables/embedded-entities.mongo.test.ts
tests/features/embeddables/nested-embeddables.mongo.test.ts
tests/features/embeddables/polymorphic-embedded-entities.mongo.test.ts
tests/features/schema-generator/AbstractSchemaGenerator.test.ts
tests/features/schema-generator/SchemaGenerator.mongo.test.ts
tests/issues/GH1175.test.ts

- `em.getDriver().createCollections()` -> `orm.getSchemaGenerator().createSchema()`
- `em.getDriver().dropCollections()` -> `orm.getSchemaGenerator().dropSchema()`
- `em.getDriver().refreshCollections()` -> `orm.getSchemaGenerator().refreshCollections()`
- `em.getDriver().ensureIndexes()` -> `orm.getSchemaGenerator().ensureIndexes()`

feat(mongo): add `SchemaGenerator` support for mongo

---

docs/docs/configuration.md
docs/docs/loading-strategies.md
docs/docs/upgrading-v4-to-v5.md
packages/core/src/EntityManager.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/entity/EntityLoader.ts
packages/core/src/enums.ts
packages/core/src/utils/Configuration.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/issues/GH1041.test.ts
tests/issues/GH1882.test.ts
tests/issues/GH2121.test.ts
tests/issues/GH234.test.ts

> This applies only to SELECT_IN strategy, as JOINED strategy implies the inference.
In v4, when we used populate hints in `em.find()` and similar methods, the
query for our entity would be analysed and parts of it extracted and used for
the population. Following example would find all authors that have books with
given IDs, and populate their books collection, again using this PK condition,
resulting in only such books being in those collections.
```ts
// this would end up with `Author.books` collections having only books of PK 1, 2, 3
const a = await em.find(Author, { books: [1, 2, 3] }, { populate: ['books'] });
```
Following this example, if we wanted to load all books, we would need a separate
`em.populate()` call:
```ts
const a = await em.find(Author, { books: [1, …
```

feat(core): add `populateWhere` option

---

packages/core/src/decorators/Check.ts
packages/core/src/decorators/index.ts
packages/core/src/typings.ts
packages/knex/src/schema/DatabaseSchema.ts
packages/knex/src/schema/DatabaseTable.ts
packages/knex/src/schema/SchemaComparator.ts
packages/knex/src/schema/SchemaGenerator.ts
packages/knex/src/schema/SchemaHelper.ts
packages/knex/src/typings.ts
packages/mysql-base/src/MySqlSchemaHelper.ts
packages/postgresql/src/PostgreSqlSchemaHelper.ts
packages/sqlite/src/SqliteSchemaHelper.ts
tests/SchemaHelper.test.ts
tests/features/schema-generator/__snapshots__/check-constraint.postgres.test.ts.snap
tests/features/schema-generator/check-constraint.postgres.test.ts

Adds a new `@Check` decorator for entities, allowing to set up custom check
constraints. At the moment, this is only for Postgres, as MySQL only supports
check constraints as of version 8, which is above the minimum test version.
While SQLite does in theory support check constraints already, tests broke due
to some bug in Knex, which is why the implementation was skipped for now.
This partially addresses #1711
> **Note:**
> Due to already existing other check constraints (namely, enums in Postgres), I decided to suffix all custom check constraint names with `_custom`, so I can filter them out where necessary.

feat(core): add custom table check constraint support for postgres

---

packages/knex/src/query/QueryBuilder.ts
tests/QueryBuilder.test.ts

Providing `0` as the limit (with the intention of not returning any records) would not add a LIMIT clause to the resulting query.

fix(query-builder): respect `0` as limit

---

packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/utils/Utils.ts
packages/entity-generator/src/EntityGenerator.ts
tests/Utils.test.ts

This fixes path handling in `Utils` to handle `file://` URLs, which can sometimes be introduced in stack traces in NodeJS. This also improves handling for absolute path components in `normalizePath` so that `normalizePath("a", "C:/b")` produces `"C:/b"` rather than `"a/C:/b"`.
Fixes #2654

fix: handle `file://` urls in normalizePath

---

docs/docs/configuration.md
docs/docs/seeding.md
docs/versioned_docs/version-5.0/configuration.md
docs/versioned_docs/version-5.0/seeding.md
packages/cli/src/commands/CreateSeederCommand.ts
packages/cli/src/commands/DatabaseSeedCommand.ts
packages/cli/src/commands/MigrationCommandFactory.ts
packages/cli/src/commands/SchemaCommandFactory.ts
packages/core/src/typings.ts
packages/core/src/utils/Configuration.ts
packages/core/src/utils/ConfigurationLoader.ts
packages/seeder/src/SeedManager.ts
packages/seeder/src/Seeder.ts
tests/features/cli/CreateSeederCommand.test.ts
tests/features/seeder/factory.test.ts
tests/features/seeder/run-seeders.test.ts
tests/features/seeder/seed-manager.test.ts

This makes the whole seeding more in line with how migrations already work.
- adds `pathTs` option to support having different paths for JS and TS
- adds `emit` to support generating JS seeder files directly
- adds `glob` and rework how we require files, so we don't care about their names
- adds `fileName` to allow control over generated seeder names
- no longer uses the "nest file name strategy" for seeders (`foo.seeder.ts` -> `FooSeeder.ts`)
Closes #2728

feat(seeder): refactor seeder to support running compiled files

---

docs/versioned_sidebars/version-4.5-sidebars.json
docs/versioned_sidebars/version-5.0-sidebars.json

The sidebar link goes to the wrong page. 
1. Go here: https://mikro-orm.io/docs
2. Click References
3. Click Entity Manager API
4. Repeat from step 1 and wonder why you keep clicking on the wrong link 😆

docs: fix link to EM API docs from sidebar

---

packages/core/src/naming-strategy/AbstractNamingStrategy.ts
tests/UnderscoreNamingStrategy.test.ts

Dashes in property names would result in invalid generated typescript code.

fix(core): fix property names for columns with dashes

---

packages/knex/src/AbstractSqlDriver.ts

Looks like something got left behind during the refactoring to a single-options-object pattern

fix(knex): respect explicit transaction in `em.count()`

---

packages/core/src/entity/EntityHelper.ts
tests/issues/GH2815.test.ts

Fixing this to the doc defaults would be a backwards compatibility break (the current behaviour is that 1-1's are treated as `orphanRemoval = true`, where the docs state that the default is really `false`). Doing it this way passes all tests, but requires the user to explicitly define their relationship as `orphanRemoval = false` - not defining it at all will result in the current behaviour.
Fixes #2815

fix(core): respect `orphanRemoval` in 1:1 relations

---

tsconfig.build.json

Currenly, since the `const` keyword is used in this export, no code is generated for the enum and attempts to reference it in application code would fail (`trying to read from undefined ....`)

chore: use `preserveConstEnums: true`

---

docs/docs/read-connections.md
packages/core/src/drivers/IDatabaseDriver.ts
packages/knex/src/AbstractSqlDriver.ts
tests/EntityManager.mysql.test.ts

This allows to bypass replica read attempts through the `FindOptions`, by setting the `forceWriteConnection` flag.
The intent is to allow users to force reads onto a master, if the user assumes that an entity has not been replicated yet.

feat(core): allow forcing write connection via `forceWriteConnection`

---

packages/knex/src/query/QueryBuilder.ts
tests/QueryBuilder.test.ts

When specifying an `order by` rule on a QB query that has joins and the column/s being sorted on exist on more than one table (e.g. `id`) we end up with an `Column 'id' in order clause is ambiguous` error.
This is a side-effect of [this change](https://github.com/mikro-orm/mikro-orm/commit/db9963fff8ceb980354b328f2d59353b9177aef3) to pagination handling in joined queries.
Ensuring field names are always fully qualified resolves this.
How do you prefer these kind of scenarios to be handled? Should I be first opening an issue, and then referencing it in the PR etc ?  Since I am providing the solution - rather than asking for support - I wasn't sure what would be the right way. Am happy to follow your preference here.

fix(knex): fully qualify sub-query order-by fields

---

packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
tests/QueryBuilder.test.ts

follow on from #2848, noticed for sub-queries it was still adding `as` to formula field on `order by`

fix(knex): `order by` with a formula field should not include `as` for sub-queries

---

docs/docs/defining-entities.md
docs/docs/entity-references.md
docs/docs/query-builder.md
docs/versioned_docs/version-5.1/defining-entities.md
docs/versioned_docs/version-5.1/entity-references.md
docs/versioned_docs/version-5.1/query-builder.md

Updated several pages to add details and add emphasis around the use of the `wrappedReference` option for defining entities. I also added some extra details and emphasis on pages where the lack of this option might cause issues.
I know verbiage for docs is super important; please let me know if you'd like to modify/remove any of what I added 😉 
I also think I got the link right in `query-builder.md`, but double check me.

docs: provide more details on `wrappedReference`

---

docker-compose.yml
packages/better-sqlite/src/BetterSqlitePlatform.ts
packages/core/src/platforms/Platform.ts
packages/knex/src/schema/SchemaComparator.ts
packages/mysql/src/MySqlSchemaHelper.ts
packages/postgresql/src/PostgreSqlPlatform.ts
packages/sqlite/src/SqlitePlatform.ts
tests/Webpack.test.ts
tests/bootstrap.ts
tests/features/custom-order/custom-order.mysql.test.ts
tests/features/custom-types/GH1930.test.ts
tests/features/custom-types/GH446.test.ts
tests/features/custom-types/custom-types.mysql.test.ts
tests/features/default-values/default-values.mysql.test.ts
tests/features/embeddables/embedded-entities.mysql.test.ts
tests/features/entity-generator/__snapshots__/EntityGenerator.test.ts.snap
tests/features/schema-generator/GH2386.test.ts
tests/features/schema-generator/SchemaGenerator.mysql.test.ts
tests/features/schema-generator/SchemaGenerator.mysql2.test.ts
tests/features/schema-generator/__snapshots__/check-constraint.mysql.test.ts.snap
tests/features/schema-generator/changing-column-type.mysql.test.ts
tests/features/schema-generator/changing-pk-type.mysql.test.ts
tests/features/schema-generator/check-constraint.mysql.test.ts
tests/features/schema-generator/comment-diffing.mysql.test.ts
tests/features/schema-generator/diffing-default-values.test.ts
tests/features/schema-generator/index-diffing.mysql.test.ts
tests/features/schema-generator/length-diffing.mysql.test.ts
tests/features/schema-generator/max-index-name-length.mysql.test.ts
tests/issues/GH1326.test.ts
tests/issues/GH603.test.ts

All ORM tests are now using mysql8, which supports check constraints.
Also fixes several issues with schema diffing in mysql8 (additional queries).

feat(schema): support mysql 8

---

packages/core/src/utils/RequestContext.ts
packages/core/src/utils/TransactionContext.ts

remove unnecessary storage.run() promise
```ts
static createAsync<T>(em: EntityManager, next: (...args: any[]) => Promise<T>): Promise<T> {
const context = new TransactionContext(em);
// async_hooks.d.ts
// AsyncLocalStorage<T>.run<R, TArgs extends any[]>(store: T, callback: (...args: TArgs) => R, ...args: TArgs): R;
// AsyncLocalStorage<TransactionContext>.run<Promise<T>, []>(store: TransactionContext, callback: () => Promise<T>): Promise<T>
return this.storage.run(context, next);
}
```

refactor(core): remove unnecessary storage.run() promise

---

packages/core/src/unit-of-work/UnitOfWork.ts

When using references that are mapped to Primary Key (`mapToPk`), the expanding will result in an error as we are actually dealing with a scalar value.
Adding this constraint into the expansion logic.

fix(core): respect mapToPk when expanding properties

---

packages/seeder/src/Factory.ts
tests/features/seeder/entities/project.entity.ts
tests/features/seeder/factory.test.ts

As asked by [B4nan](https://github.com/B4nan) in related issue, I opened this PR.
Closes #3062
See issue above
Only types were changed, so no useful test which I can think of can cover that besides TypeScript itself (`yarn tsc-check-tests`). Existing tests are running successful.
Only [here](https://mikro-orm.io/docs/seeding#entity-factories) the documentation could be updated, but I think for the majority of people a simple partial is enough - so let's keep it how it is instead of:
```diff
- definition(faker: Faker): Partial<Author>
+ definition(faker: Faker): Partial<RequiredEntityData<Author>>
```

fix(seeder): fix type of Factory methods

---

packages/better-sqlite/package.json
packages/cli/package.json
packages/core/package.json
packages/entity-generator/package.json
packages/knex/package.json
packages/mariadb/package.json
packages/migrations/package.json
packages/mikro-orm/package.json
packages/mongodb/package.json
packages/mysql/package.json
packages/postgresql/package.json
packages/reflection/package.json
packages/sqlite/package.json

If module is 'node16' (typescript 4.7, see tsconfig.json) and module type is 'module' (see package.js) then typescript currently searches for a file named index.d.mts (as the base file is index.d.ts) and doesn't find it (see image).
I read about it [here](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing):  "./commonjs/index.cjs" =>  "./commonjs/index.d.cts"
A solution is to declare 'index.d.ts' explicitly as the valid typing for 'index.mjs'.
~~~json
"import": "./dist/index.mjs"
~~~
=>
~~~json
"import": {
"types": "./dist/index.d.ts",
"default": "./dist/index.mjs"
},
~~~
_______
package.json
~~~json
{
"type": "module"
}
~~~
tsconfig.json
~~~json
"compilerOptions": {
"module": "node16"
}
~~~

fix: typing detection with typescript 4.7 node16

---

docs/docs/multiple-schemas.md
docs/versioned_docs/version-3.6/multiple-schemas.md
docs/versioned_docs/version-4.5/multiple-schemas.md
docs/versioned_docs/version-5.0/multiple-schemas.md

Just fix a couple of typos in the multiple schemas docs

docs: fix typos in multiple schemas

---

packages/core/src/metadata/MetadataDiscovery.ts
tests/MikroORM.test.ts
tests/features/embeddables/GH1912.test.ts
tests/features/embeddables/GH2149.test.ts
tests/features/embeddables/GH2357.test.ts
tests/features/embeddables/GH2391.test.ts
tests/features/embeddables/GH2717.test.ts
tests/features/embeddables/GH2948.test.ts
tests/features/embeddables/GH2975.test.ts
tests/features/embeddables/GH3134.test.ts
tests/features/embeddables/embeddable-custom-types.postgres.test.ts
tests/features/embeddables/embedded-entities.mongo.test.ts
tests/features/embeddables/embedded-entities.mysql.test.ts
tests/features/embeddables/embedded-entities.postgres.test.ts
tests/features/embeddables/entities-in-embeddables.mongo.test.ts
tests/features/embeddables/entities-in-embeddables.postgres.test.ts
tests/features/embeddables/nested-embeddables.mongo.test.ts
tests/features/embeddables/nested-embeddables.postgres.test.ts
tests/features/embeddables/polymorphic-embedded-entities.mongo.test.ts

When we see a missing target entity or embeddable that is defined with a reference, e.g. `@Embedded(() => Profile)` or `@ManyToOne(() => Author)`, we now try to discover the target automatically. This means we no longer need to care about discovering embeddables explicitly as long as we specify them correctly in owning entities. This works recursively.

feat(core): automatically discover target embeddables and relationships

---

packages/core/src/utils/Utils.ts
tests/Utils.test.ts

This behavior leads to redundant changesets being created
whenever entity is added to the unit-of-work.

fix(core): consider two `NaN` as equal when computing changesets

---

docs/docs/collections.md
packages/core/src/entity/ArrayCollection.ts
packages/core/src/entity/Collection.ts
tests/QueryBuilder.test.ts
tests/issues/GH3240.test.ts

Previously we propagated adding only to initialized collections. This means that we could ignore some changes like adding items from the inverse side that. Now we propagate the `add` operation to the owning sides of M:N relations even if they are not initialized.
Closes #3240

feat(core): propagate add operation to m:n owner even if not initialized

---

packages/better-sqlite/src/BetterSqliteExceptionConverter.ts
packages/sqlite/src/SqliteExceptionConverter.ts
tests/sqlite-constraints.test.ts

Two database drivers sqlite and better-sqlite were changed according to [this](https://github.com/doctrine/dbal/blob/4.0.x/src/Driver/API/SQLite/ExceptionConverter.php#L83) link, which i found in [source code documentation](https://github.com/mikro-orm/mikro-orm/blob/master/packages/sqlite/src/SqliteExceptionConverter.ts#L13).

fix(sqlite): throwing ForeignKeyConstraintViolationException instead of the DriverException

---

packages/knex/src/query/QueryBuilderHelper.ts
tests/features/embeddables/query-builder-embeddable.test.ts

Fix a bug where inserting embeddables using a `QueryBuilder` would throw the following error:
```
● insert an object with embeddable using a QueryBuilder
SqliteError: insert into `user` (`id`, `settings`) select 1 as `id`, '[object Object]' as `settings` union all select 2 as `id`, '[object Object]' as `settings` - table user has no column named settings
223 |       this.emit('query', Object.assign({ __knexUid, __knexTxId }, obj));
224 |
> 225 |       return MonkeyPatchable.QueryExecutioner.executeQuery(connection, obj, this);
|                                               ^
226 |     };
227 |
228 |     TableCompiler.prototype.raw = function (this: any, query: string) {
at Database.prepare (node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
at Client_BetterSQLite3._query …
```

fix(query-builder): fix `qb.insert()/update()` on embeddables in inline mode

---

docs/docs/migrations.md
packages/cli/package.json
packages/cli/src/commands/MigrationCommandFactory.ts
packages/core/package.json
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/typings.ts
packages/migrations-mongodb/.npmignore
packages/migrations-mongodb/package.json
packages/migrations-mongodb/src/JSMigrationGenerator.ts
packages/migrations-mongodb/src/Migration.ts
packages/migrations-mongodb/src/MigrationGenerator.ts
packages/migrations-mongodb/src/MigrationRunner.ts
packages/migrations-mongodb/src/MigrationStorage.ts
packages/migrations-mongodb/src/Migrator.ts
packages/migrations-mongodb/src/TSMigrationGenerator.ts
packages/migrations-mongodb/src/index.ts
packages/migrations-mongodb/src/typings.ts
packages/migrations-mongodb/tsconfig.build.json
packages/migrations-mongodb/tsconfig.json
packages/mongodb/src/MongoDriver.ts
packages/mongodb/src/MongoPlatform.ts
packages/mongodb/src/MongoSchemaGenerator.ts
tests/DatabaseDriver.test.ts
tests/EntityManager.mongo.test.ts
tests/bootstrap.ts
tests/features/migrations/Migrator.mongo.test.ts
tests/features/migrations/Migrator.postgres.test.ts
tests/features/migrations/__snapshots__/Migrator.mongo.test.ts.snap

Adds new `@mikro-orm/migrations-mongodb` package that needs to be explicitly installed. Current CLI commands will work with it transparently.
Mongo migrations have some limitations:
- no nested transaction support
- no schema diffing
- only blank migrations are generated
- use `this.driver` or `this.getCollection()` to manipulate with the database
Closes #295

feat(mongo): add support for migrations in mongo driver

---

docs/docs/virtual-entities.md
docs/sidebars.js
packages/core/src/EntityManager.ts
packages/core/src/decorators/Entity.ts
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/entity/EntityFactory.ts
packages/core/src/hydration/ObjectHydrator.ts
packages/core/src/metadata/MetadataStorage.ts
packages/core/src/metadata/MetadataValidator.ts
packages/core/src/typings.ts
packages/core/src/utils/AbstractSchemaGenerator.ts
packages/entity-generator/src/EntitySchemaSourceFile.ts
packages/knex/src/AbstractSqlDriver.ts
packages/mongodb/src/MongoDriver.ts
tests/MetadataValidator.test.ts
tests/features/virtual-entities/__snapshots__/virtual-entities.sqlite.test.ts.snap
tests/features/virtual-entities/virtual-entities.mongo.test.ts
tests/features/virtual-entities/virtual-entities.sqlite.test.ts

Virtual entities don't represent any database table. Instead, they dynamically resolve to an SQL query (or an aggregation in mongo), allowing to map any kind of results onto an entity. Such entities are mean for read purposes, they don't have a primary key and therefore cannot be tracked for changes. In a sense they are similar to (currently unsupported) database views.
To define a virtual entity, provide an expression, either as a string (SQL query):
```
@Entity({
expression: 'select name, age, ' +
'(select count(*) from book b where b.author_id = a.id) as total_books, ' +
'(select group_concat(distinct t.name) from book b ' +
'join tags_ordered bt on bt.book_id = b.id ' +
'join book_tag t on t.id = bt.book_tag_id ' +
'where b.author_id = a.id ' +
'group by b.author_id) as used_tags ' + …
```

feat(core): add support for virtual entities

---

packages/postgresql/src/PostgreSqlPlatform.ts
tests/issues/GH2679.test.ts

The fix in #3037 did not cover using of double quotes which broke the insert of values

fix(postgres): fix escaping of special chars in string arrays

---

packages/knex/src/query/QueryBuilderHelper.ts
tests/QueryBuilder.test.ts

Small fix for joining table using operator `$ne`  (`$eq`) with null value.
```
em.createQueryBuilder(Table, 't').join('relation', 'r', { 'r.nullableField': { $ne: null } });
```
This should create sql ``` `r`.`nullableField` is not null ```, but created sql was  ``` `r`.`nullableField` != null ```
Closes #3412

fix(query-builder): support more operators in join conditions

---

packages/core/src/entity/EntityRepository.ts

Planning to use the multi-schema for multi-tenant but want to be able to set the schema on `create` or `assign` when using a EntityRepository.
I have noticed that `merge` method exposes its options so added an optional param for `create` and `assign` to gain access to the option so I can set the schema.
Should I be adding tests for this?

feat(knex): add options params to `create` + `assign` methods within EntityRepository

---

docs/docs/entity-generator.md
packages/core/src/utils/Configuration.ts
packages/core/src/utils/ConfigurationLoader.ts
packages/entity-generator/src/EntityGenerator.ts
packages/entity-generator/src/SourceFile.ts
tests/features/cli/CLIHelper.test.ts
tests/features/entity-generator/EntityGenerator.test.ts
tests/features/entity-generator/__snapshots__/EntityGenerator.test.ts.snap

In a generated entity, add the ability for referenced entities to be imported by a named import.
Most common case is a extension of '.js' but node does support '.cjs' and '.mjs'. Supported ESM_FILE_FORMAT can be found in the node docs https://nodejs.org/docs/latest-v16.x/api/esm.html#resolution-algorithm
Another possible approach is to check package.json for `"type": "module"` but that felt like I was being too smart as I wouldn't know for sure which supported file format the consumer would want.

feat(entity-generator): add import extension for referenced entities

---

docs/docs/configuration.md
packages/core/src/utils/ConfigurationLoader.ts

Added MIKRO_ORM_SCHEMA to the environment variables being read from .env file.

fix(core): add missing `MIKRO_ORM_SCHEMA` env var

---

packages/core/src/decorators/UseRequestContext.ts

We can customize the parameter name of `MikroORM` in `@UseRequestContext` decorator
```ts
@Injectable()
export class SomeService {
constructor(
private readonly mikroORM: MikroORM) {
}
@UseRequestContext<SomeService>(type => type.mikroORM)
public someFunction(id: number) {
// ...
}
}
```
---
Closes #3474

feat(core): allow custom ORM prop name in `@UseRequestContext()`

---

docs/docs/query-builder.md
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/SqlEntityManager.ts
packages/knex/src/query/Alias.ts
packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
tests/QueryBuilder.test.ts

| Type                  | Breaking change |
| --------------------- | --------------- |
| Feat | No          |
You can specify the table used in the `FROM` clause, replacing the current table name if one has already been specified. This is typically used to specify a sub-query expression in SQL.
```ts
const qb = em.createQueryBuilder(Book2);
qb.select('*').from(Author2).where({ id: { $gt: 2 } });
console.log(qb.getQuery());
// select `e0`.* from `author2` as `e0` where `e0`.`id` > 2;
```
You can also use sub-queries in the `FROM` like this:
```ts
const qb1 = em.createQueryBuilder(Book2).where({ id: { $lte: new Date() } }).orderBy({ id: 'DESC' }).limit(10);
const qb2 = em.createQueryBuilder(qb1.clone())
qb2.select('*').orderBy({ id: 'ASC' });
console.log(qb2.getQuery());
// select `e1`.* …
```

feat(knex): allow changing `FROM` clause using `QueryBuilder`

---

packages/entity-generator/src/SourceFile.ts
tests/features/entity-generator/EntityGenerator.test.ts
tests/features/entity-generator/__snapshots__/EntityGenerator.test.ts.snap

…ies that define a default value

feat(entity-generator): generate `OptionalProps` symbols

---

packages/core/src/utils/Configuration.ts
packages/core/src/utils/ConfigurationLoader.ts
tests/MikroORM.test.ts
tests/features/cli/CLIHelper.test.ts

If there is a `src` folder, the ORM will now automatically detect it and adjust the `seeder` and `migrations` configs to have both `path` and `pathTs` set based on that. This happens only if there are no values provided by user and the default folders don't exist.
For a fresh project, this means that if you omit the configuration, but your project has a `src` and `dist` folders existing, the ORM will automatically set the following:
- `migrations.path` to `./dist/migrations`
- `migrations.pathTs` to `./src/migrations`
- `seeder.path` to `./dist/seeders`
- `seeder.pathTs` to `./src/seeders`
In addition to this, the CLI no longer requires explicit configuration of `configPaths` in `package.json`, as long as your config is called `mikro-orm.config.js/ts` and is located in `src` or …

feat(core): automatically detect `src/dist/build` folders and adjust configuration

---

packages/better-sqlite/src/BetterSqliteMikroORM.ts
packages/better-sqlite/src/index.ts
packages/core/src/MikroORM.ts
packages/mariadb/src/MariaDbMikroORM.ts
packages/mariadb/src/index.ts
packages/mongodb/src/MongoMikroORM.ts
packages/mongodb/src/index.ts
packages/mysql/src/MySqlMikroORM.ts
packages/mysql/src/index.ts
packages/postgresql/src/PostgreSqlMikroORM.ts
packages/postgresql/src/index.ts
packages/sqlite/src/SqliteMikroORM.ts
packages/sqlite/src/index.ts
scripts/copy.mjs
tests/EntityManager.mongo.test.ts
tests/EntityManager.sqlite2.test.ts
tests/cli-config.ts
tests/features/embeddables/nested-embeddables.postgres.test.ts
tests/issues/GH1003.test.ts

Those driver specific implementations automatically fill the driver type:
Before:
```ts
import { MikroORM, Options } from '@mikro-orm/core';
import { SqliteDriver } from '@mikro-orm/sqlite';
const options: Options<SqliteDriver> = { type: 'sqlite', ... };
const orm = await MikroORM.init<SqliteDriver>(options);
```
After:
```ts
import { MikroORM, Options } from '@mikro-orm/sqlite';
// no need for `type: 'sqlite'` if we use the MikroORM class from driver package
const options: Options = { ... };
const orm = await MikroORM.init(options);
```

feat(core): add `MikroORM` and `Options` exports to each driver package

---

docs/docs/installation.md
packages/better-sqlite/src/BetterSqliteMikroORM.ts
packages/better-sqlite/src/index.ts
packages/core/src/utils/Configuration.ts
packages/mariadb/src/MariaDbMikroORM.ts
packages/mariadb/src/index.ts
packages/mongodb/src/MongoMikroORM.ts
packages/mongodb/src/index.ts
packages/mysql/src/MySqlMikroORM.ts
packages/mysql/src/index.ts
packages/postgresql/src/PostgreSqlMikroORM.ts
packages/postgresql/src/index.ts
packages/sqlite/src/SqliteMikroORM.ts
packages/sqlite/src/index.ts
tests/cli-config.ts

To have the config type-safe, we can define the options variable first, with the `Options` type:
```ts
import { Options } from '@mikro-orm/core';
const config: Options = {
// ...
};
export default config;
```
Alternatively, we can use the `defineConfig` helper that should provide intellisense even in JavaScript files, without the need for type hints via jsdoc:
```ts
import { defineConfig } from '@mikro-orm/core';
export default defineConfig({
// ...
});
```

feat(core): add `defineConfig` helper

---

docs/docs/defining-entities.md
docs/docs/schema-generator.md
packages/core/src/decorators/Property.ts
packages/core/src/typings.ts
packages/knex/src/schema/DatabaseTable.ts
packages/knex/src/schema/SchemaComparator.ts
packages/knex/src/typings.ts
tests/features/schema-generator/GH1904.test.ts

```ts
@Property({
columnType: 'timestamp',
extra: 'VIRTUAL GENERATED',
ignoreSchemaChanges: ['type', 'extra'],
})
changingField!: Date;
```
This is useful for situations such as #1904, where `knex` is unable to properly diff the column.
Fixes #1904

feat(schema): add ability to ignore specific column changes

---

docs/docs/entity-manager.md
packages/core/src/EntityManager.ts
packages/core/src/entity/EntityFactory.ts
packages/core/src/entity/EntityValidator.ts
packages/core/src/entity/wrap.ts
packages/core/src/unit-of-work/ChangeSetComputer.ts
packages/core/src/unit-of-work/ChangeSetPersister.ts
packages/core/src/unit-of-work/UnitOfWork.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.sqlite2.test.ts

Previously, only an initialized entities were considered during the change set tracking. With this change, all entities are tracked and checked for changes during the flush operation.
This unlocks one important use case - running update queries without loading the entity first. As opposed to the `em.nativeUpdate()`, this approach brings all the regular UoW features like lifecycle hooks (as well as `onUpdate` property hook).
```ts
const ref = em.getReference(Author, 123);
ref.name = 'new name';
ref.email = 'new email';
await em.flush();
```

feat(core): track changes on entity references

---

docs/docs/entity-manager.md
packages/core/src/EntityManager.ts
packages/core/src/entity/WrappedEntity.ts
tests/EntityManager.sqlite2.test.ts

Allows to synchronize the entity state with database. This is a shortcut for calling `em.findOne()` with `refresh: true` and disabled auto-flush.
> This results in loss of any changes done to that entity.
```ts
const author = await em.findOneOrFail(Author, { name: 'Jon' });
console.log(author.name); // 'Jon'
// changes to entity will be lost!
author.name = '123';
// refresh the value, ignore any changes
await em.refresh(author);
console.log(author.name); // 'Jon'
```

feat(core): add `em.refresh(entity)` method

---

docs/docs/entity-manager.md
packages/core/src/EntityManager.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/entity/EntityFactory.ts
packages/core/src/entity/EntityHelper.ts
packages/core/src/logging/DefaultLogger.ts
packages/core/src/logging/SimpleLogger.ts
packages/core/src/logging/index.ts
packages/core/src/typings.ts
packages/knex/src/AbstractSqlDriver.ts
packages/mongodb/src/MongoConnection.ts
packages/mongodb/src/MongoDriver.ts
tests/features/__snapshots__/upsert.test.ts.snap
tests/features/upsert.test.ts

We can use `em.upsert()` create or update the entity, based on whether it is already present in the database. This method performs an `insert on conflict merge` query ensuring the database is in sync, returning a managed entity instance. The method accepts either `entityName` together with the entity `data`, or just entity instance.
```ts
// insert into "author" ("age", "email") values (33, 'foo@bar.com') on conflict ("email") do update set "age" = 41
const author = await em.upsert(Author, { email: 'foo@bar.com', age: 33 });
```
The entity data needs to contain either the primary key, or any other unique property. Let's consider the following example, where `Author.email` is a unique property:
```ts
// insert into "author" ("age", "email") values (33, 'foo@bar.com') on conflict ("email") …
```

feat(core): add `em.upsert()` method

---

packages/core/src/metadata/MetadataDiscovery.ts
tests/QueryBuilder.test.ts
tests/features/composite-keys/__snapshots__/custom-pivot-entity-uni.sqlite.test.ts.snap
tests/features/composite-keys/__snapshots__/custom-pivot-entity-wrong-order.sqlite.test.ts.snap
tests/features/composite-keys/__snapshots__/custom-pivot-entity.sqlite.test.ts.snap
tests/features/default-values/__snapshots__/default-values.mysql.test.ts.snap
tests/features/default-values/default-values.mysql.test.ts
tests/features/optimistic-lock/GH2401.test.ts
tests/features/schema-generator/__snapshots__/SchemaGenerator.mysql.test.ts.snap
tests/features/schema-generator/__snapshots__/SchemaGenerator.mysql2.test.ts.snap
tests/features/schema-generator/__snapshots__/SchemaGenerator.postgres.test.ts.snap
tests/features/schema-generator/__snapshots__/SchemaGenerator.sqlite.test.ts.snap
tests/issues/__snapshots__/GH529.test.ts.snap

When a runtime default value is provided and the entity instance can be constructed without providing any parameters, the default values will be inferred automatically.
We try to create two entity instances to detect the value is stable, and compare the values by reference, this will discard things like `new Date()` or any object values in general.

feat(schema): try to infer runtime default values automatically

---

packages/cli/src/esm.ts

Shebang require add `-S` to pass parameters. See, for example, this article https://alexewerlof.medium.com/node-shebang-e1d4b02f731d#:~:text=Pass%20parameters%20to%20Node.js
Related to https://github.com/mikro-orm/mikro-orm/issues/3485#issuecomment-1265237154

fix(cli): fix using `npx --workspace` with `mikro-orm-esm`

---

packages/core/src/utils/Utils.ts
tests/Utils.test.ts

A recent update to @swc/core (since 1.3.4) causes Mikro-ORM init to fail with errors such as:
```
ERROR Entity AuthorizationTokenEntity has wrong unique definition: 'activeToken' does not exist. You need to use property name, not column name.
```
During discovery of a class, some decorators are resolving the class path fine - populating the metadata along the way - but at some point it gets to a decorator (`@Unique`, in my case) which fails to determine the path to the class (because the stack trace didn't contain a call to `__decorate()`), wiping out all the previously-populated metadata (`properties`, in my case). So while it _did_ know about the `activeToken` property, the path-lookup-failure during the processing of the `@Unique` decorator lost it, giving me that error.
It boils down …

fix(core): improve entity path detection with SWC 1.3.4+

---

packages/core/src/entity/ArrayCollection.ts
packages/core/src/entity/Collection.ts
packages/core/src/entity/EntityLoader.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite2.test.ts
tests/features/paginate-flag.postgres.test.ts
tests/issues/GH910.test.ts

Previously `Collection.add/remove` were defined with a spread parameter, which could result in perf degradation in very large collections. This change makes the first parameter accept also an array of items, skipping unnecessary copying of arrays when hydarting the collection.
This is slightly breaking on type level, as it is no longer possible to do `coll.add(...items)` with a generic array - it only works with a tuple. The solution is to do `coll.add(items)` instead, which will type check and is also more performant (no array copies).
Closes #3572

perf(core): improve support for large collections

---

packages/core/src/drivers/IDatabaseDriver.ts
tests/issues/GH3292.test.ts

Just add the possibility of using findOne with an offset in case that is needed.
This PR doesn't have breaking changes.
Closes #3292

feat(core): add the `offset` into `FindOneOptions`

---

packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/QueryBuilderHelper.ts
tests/QueryBuilder.test.ts
tests/issues/GH1626.test.ts

fix(knex): always skip virtual properties in returning clause

---

packages/core/src/entity/Collection.ts
tests/EntityManager.sqlite2.test.ts

i have found that if you load items (or initing) from m:n collection with pivot table, you will get query without filters

fix(core): respect filters when loading m:n relations

---

docs/docs/serializing.md
packages/core/src/entity/EntityHelper.ts
packages/core/src/entity/WrappedEntity.ts
packages/core/src/entity/index.ts
packages/core/src/index.ts
packages/core/src/serialization/EntitySerializer.ts
packages/core/src/serialization/EntityTransformer.ts
packages/core/src/serialization/SerializationContext.ts
packages/core/src/serialization/index.ts
packages/core/src/typings.ts
tests/EntityHelper.mongo.test.ts
tests/entities-sql/Author2.ts
tests/features/serialize.test.ts

The serialization process is normally driven by the `populate` hints. If you want to take control over this, you can use the `serialize()` helper:
```ts
import { serialize } from '@mikro-orm/core';
const dto = serialize(user); // serialize single entity
// { name: '...', books: [1, 2, 3], identity: 123 }
const dtos = serialize(users); // supports arrays as well
// [{ name: '...', books: [1, 2, 3], identity: 123 }, ...]
```
By default, every relation is considered as not populated - this will result in the foreign key values to be present. Loaded collections will be represented as arrays of the foreign keys. To control the shape of the serialized response we can use the second `options` parameter:
```ts
export interface SerializeOptions<T extends object, P extends string = never> {
/** …
```

feat(core): add `serialize()` helper for explicit serialization

---

docs/docs/configuration.md
packages/core/src/MikroORM.ts
packages/core/src/platforms/Platform.ts
packages/core/src/utils/Configuration.ts
packages/entity-generator/src/EntityGenerator.ts
packages/knex/src/AbstractSqlPlatform.ts
packages/knex/src/schema/SchemaGenerator.ts
packages/migrations-mongodb/src/Migrator.ts
packages/migrations/src/Migrator.ts
packages/mongodb/src/MongoPlatform.ts
packages/mongodb/src/MongoSchemaGenerator.ts
packages/seeder/src/SeedManager.ts
tests/EntityManager.postgre.test.ts
tests/features/embeddables/extensions.test.ts

Register your extensions in the ORM config this way:
```ts
import { defineConfig } from '@mikro-orm/postgres';
import { Migrator } from '@mikro-orm/migrations';
import { EntityGenerator } from '@mikro-orm/entity-generator';
import { SeedManager } from '@mikro-orm/seeder';
export default defineConfig({
dbName: 'test',
extensions: [Migrator, EntityGenerator, SeedManager],
});
```
This will replace the static requires we use for extensions like entity generator or seeder in v6 (right now they are still there as a fallback to the extension).
Related: #3743

feat(core): introduce ORM extensions

---

packages/cli/src/commands/GenerateCacheCommand.ts
tests/features/cli/GenerateCacheCommand.test.ts

[References](https://github.com/mikro-orm/mikro-orm/discussions/3795#discussioncomment-4253521)
Allow user to generate ts cache via CLI.

feat(cli): added option to generate cache via ts-node

---

docs/docs/entity-constructors.md
packages/core/src/entity/Reference.ts
packages/core/src/entity/wrap.ts
packages/core/src/utils/Utils.ts
tests/entities-sql/Book2.ts

```ts
@ManyToOne({ entity: () => Author })
author: Rel<Author>;
constructor(dto: { title: string; author: number }) {
this.title = dto.title;
this.author = rel(Author, dto.author);
}
```
The `rel()` helper will create entity instance that is not yet managed (as we don't pass it any `EntityManager` instance), but it will be considered as existing entity reference once it becomes managed. This is in fact an equivalent to `em.getReference()`, but without having the `EntityManager` instance at hand.
> `rel()` is a shortcut for `Reference.createNakedFromPK()`.
And if you want to be safer and use the `Reference` wrapper, the `ref()` helper also accepts this new signature: 
```ts
@ManyToOne({ entity: () => Author, ref: true })
author: Ref<Author>;
constructor(dto: { title: string; author: number …
```

feat(core): allow creating entity from PK via `rel()` and `ref()`

---

packages/core/src/unit-of-work/UnitOfWork.ts
tests/issues/GH3850-required-relation.test.ts
tests/issues/GH3850.test.ts

Fixes #3850
I'm not very familar with the code, so I'm not confident with the solution, but I think this is what is needed.
Tests added and related tests for #3614 also still pass

fix(core): propagation with nullable 1:1 relation

---

docs/docs/nested-populate.md
docs/versioned_docs/version-5.6/nested-populate.md

The populate section didn't mention how to use `populateWhere` or that there were multiple loading strategies supported, so this PR adds a bit of information on `populateWhere` then links people over to the loading strategies documentation from populate in case they're wondering how MikroORM will actually do the populate action in detail.

docs: add information about `populateWhere` and loading strategies

---

packages/entity-generator/src/EntitySchemaSourceFile.ts
tests/features/entity-generator/EntityGenerator.test.ts
tests/features/entity-generator/__snapshots__/EntityGenerator.test.ts.snap

fix(entity-generator): use table name instead of class name in `EntitySchema`

---

docs/docs/decorators.md

There seems to be some typos on docs to fix 👻.
Please check if I got them right.

docs: fix typo on decorator property docs

---

docs/docs/installation.md
packages/cli/src/CLIConfigurator.ts
packages/cli/src/commands/DebugCommand.ts
packages/core/src/utils/ConfigurationLoader.ts
packages/core/src/utils/Utils.ts
tests/features/cli/CLIHelper.test.ts

Allows to override the config path via `--config` option:
```sh
$ npx mikro-orm debug --config ./my-config.ts
```
This option will be respected also when you run your app, not just when you use the CLI.

feat(core): allow overriding ORM config path via `--config`

---

.yarnrc.yml
docs/docs/migrations.md
packages/cli/src/commands/MigrationCommandFactory.ts
packages/core/src/typings.ts
packages/migrations-mongodb/src/Migrator.ts
packages/migrations/src/Migrator.ts
tests/features/cli/CheckMigrationsCommand.test.ts

Allow checking for migrations. This would be useful for adding to git hooks to ensure that any changes to ORM entities are captured in migrations.

feat(cli): add check for migrations command

---

docs/docs/decorators.md
packages/core/src/decorators/Property.ts

Hi, 
I addded js-doc for `Property()`, but  I'm not sure it's what you meant in [the issue](https://github.com/mikro-orm/mikro-orm/issues/3893) Want to check if it is in line with your intention. 🫠
BTW, some of the options of `Property()` are [in docs](https://mikro-orm.io/docs/decorators#property) while others like `name`, `onCreation` are not. Did you selected only some of them on purpose? 
Related issues: https://github.com/mikro-orm/mikro-orm/issues/3893

docs: add jsdoc for property

---

docs/docs/deployment.md

As discussed on [MikroORM Slack](https://mikroorm.slack.com/archives/CFTFEK39D/p1676393290381249?thread_ts=1676045567.606219&cid=CFTFEK39D), adding docs around `esbuild` bundling

docs: add information to deployment guide for esbuild bundling

---

packages/postgresql/src/PostgreSqlSchemaHelper.ts
tests/SchemaHelper.test.ts

I noticed that when I was updating a column with an Enum type using an entity with a schema defined, the migration generated attempted to drop the existing constraint but failed due to a quoting issue. The migration was generated with a line like:
```sql
alter table "my_schema.test" drop constraint if exists "test_column_check";
```
instead of 
```sql
alter table "my_schema"."test" drop constraint if exists "test_column_check";
```
I've added a test that I believe exercises the functionality.

fix(postgres): use quoted schema+table name when dropping constraints

---

docs/docs/upgrading-v5-to-v6.md
packages/core/src/EntityManager.ts
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/entity/EntityFactory.ts
packages/core/src/typings.ts
packages/core/src/utils/Cursor.ts
packages/core/src/utils/Utils.ts
packages/knex/src/AbstractSqlDriver.ts
packages/mongodb/src/MongoDriver.ts
tests/DatabaseDriver.test.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mongo2.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/features/auto-refreshing.postgre.test.ts
tests/features/embeddables/embedded-entities.postgres.test.ts
tests/features/embeddables/nested-embeddables.postgres.test.ts
tests/features/partial-loading/partial-loading.mongo.test.ts
tests/features/partial-loading/partial-loading.mysql.test.ts
tests/types.test.ts

The `Loaded` type is now improved to support the partial loading hints (`fields` option). When used, the returned type will only allow accessing selected properties. Primary keys are automatically selected.
```ts
// book is typed to `Selected<Book, 'author', 'title' | 'author.email'>`
const book = await em.findOneOrFail(Book, 1, {
fields: ['title', 'author.email'],
populate: ['author'],
});
const id = book.id; // ok, PK is selected automatically
const title = book.title; // ok, title is selected
const publisher = book.publisher; // fail, not selected
const author = book.author.id; // ok, PK is selected automatically
const email = book.author.email; // ok, selected
const name = book.author.name; // fail, not selected
```
`FindOptions.fields` now accepts only array of …

feat(core): strict partial loading

---

docs/docs/defining-entities.md
docs/versioned_docs/version-4.5/defining-entities.md
docs/versioned_docs/version-5.4/defining-entities.md
docs/versioned_docs/version-5.5/defining-entities.md
docs/versioned_docs/version-5.6/defining-entities.md

I believe `uuid-osp` is a typo of `uuid-ossp`, so fixed it.

docs: fix typo `uuid-osp` -> `uuid-ossp`

---

packages/knex/src/schema/SchemaGenerator.ts
packages/knex/src/schema/SchemaHelper.ts
packages/mariadb/src/MariaDbSchemaHelper.ts
packages/mysql/src/MySqlSchemaHelper.ts
packages/postgresql/src/PostgreSqlSchemaHelper.ts
tests/features/schema-generator/__snapshots__/comment-diffing.postgres.test.ts.snap
tests/features/schema-generator/comment-diffing.postgres.test.ts

fix(postgres): use explicit schema in table identifier when altering comments

---

packages/core/src/metadata/MetadataDiscovery.ts
tests/features/schema-generator/signed-primary-key.test.ts

Users don't necessarily want all numeric primary key columns to be unsigned.
Alternatively, we can change the behavior such that _only_ autoincrement pkeys are unsigned and just let numeric pkeys be signed by default, but that seems like a more major behavior change.

fix(core): respect explicit `unsigned` option

---

docs/docs/entity-manager.md
docs/docs/filters.md
docs/docs/query-builder.md
docs/docs/upgrading-v5-to-v6.md
package.json
packages/core/src/typings.ts
packages/core/src/unit-of-work/ChangeSetPersister.ts
packages/core/src/utils/QueryHelper.ts
packages/core/src/utils/Utils.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/AbstractSqlPlatform.ts
packages/knex/src/SqlEntityManager.ts
packages/knex/src/query/CriteriaNodeFactory.ts
packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/QueryBuilder.test.ts
tests/features/composite-keys/GH1079.test.ts
tests/features/filters/filters.postgres.test.ts
tests/features/multiple-schemas/GH3177.test.ts
tests/features/multiple-schemas/multiple-schemas.postgres.test.ts
tests/features/upsert/GH3787-2.test.ts
tests/features/upsert/GH4020.test.ts
tests/issues/GH3810.test.ts
tests/issues/GH3988.test.ts
tests/issues/GH4027.test.ts
tests/issues/GH482.test.ts

When you want to issue an atomic update query via flush, you can use the static `raw()` helper:
```ts
const ref = em.getReference(Author, 123);
ref.age = raw(`age * 2`);
await em.flush();
console.log(ref.age); // real value is available after flush
```
The `raw()` helper returns special raw query fragment object. It disallows serialization (via `toJSON`) as well as working with the value (via [`valueOf()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf)). Only single use of this value is allowed, if you try to reassign it to another entity, an error will be thrown to protect you from mistakes like this:
```ts
order.number = raw(`(select max(num) + 1 from orders)`);
user.lastOrderNumber = order.number; // throws, it could resolve to a …
```

feat(core): support atomic updates via `raw()` helper

---

docs/docs/deployment.md
packages/cli/src/commands/GenerateCacheCommand.ts
packages/core/src/cache/CacheAdapter.ts
packages/core/src/cache/FileCacheAdapter.ts
packages/core/src/cache/GeneratedCacheAdapter.ts
packages/core/src/cache/index.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/utils/Configuration.ts
tests/features/cli/GenerateCacheCommand.test.ts
tests/features/reflection/TsMorphMetadataProvider.test.ts
tests/features/reflection/production-cache/.gitignore
tests/features/reflection/production-cache/production-cache.test.ts

MikroORM now lets you generate production cache bundle into a single JSON file via CLI:
```bash
npx mikro-orm cache:generate --combined
```
This will create `./temp/metadata.json` file which can be used together with `GeneratedCacheAdapter` in your production configuration:
```ts
import { GeneratedCacheAdapter, MikroORM } from '@mikro-orm/core';
await MikroORM.init({
metadataCache: {
enabled: true,
adapter: GeneratedCacheAdapter, 
options: { data: require('./temp/metadata.json') },
},
// ...
});
```
This way you can keep the `@mikro-orm/reflection` package as a development dependency only, use the CLI to create the cache bundle, and depend only on that in your production build.
> The cache bundle can be statically imported, which is handy in case you are using some bundler.
Closes #4164

feat(core): add `GeneratedCacheAdapter` for production usage

---

packages/core/src/utils/Configuration.ts
packages/migrations-mongodb/src/Migrator.ts
packages/migrations/src/Migrator.ts

This provides an option to make the migration logs silent.
Closes #4124

feat(migrator): allow disabling logging via `migrations.silent`

---

packages/core/src/entity/EntityFactory.ts
packages/core/src/hydration/Hydrator.ts
packages/core/src/hydration/ObjectHydrator.ts
packages/core/src/platforms/Platform.ts
packages/core/src/types/JsonType.ts
packages/core/src/types/Type.ts
packages/core/src/types/index.ts
packages/core/src/utils/EntityComparator.ts
packages/core/src/utils/Utils.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/QueryBuilderHelper.ts
packages/mongodb/src/MongoPlatform.ts
packages/mysql/src/MySqlPlatform.ts
packages/postgresql/src/PostgreSqlConnection.ts
tests/EntityManager.mariadb.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/features/custom-types/GH4193.test.ts
tests/features/custom-types/json-hydration.postgres.test.ts
tests/features/custom-types/json-properties.test.ts
tests/features/embeddables/__snapshots__/polymorphic-embedded-entities.sqlite.test.ts.snap

Every driver behaves a bit differently when it comes to handling JSON columns. While SQLite is not processing then anyhow, and MongoDB supports them natively, all the others have rather quirky and not very configurable JSON parsing and stringification implemented. It is crucial to have the JSON values properly parsed, as well as normalized in the entity snapshot, so we can correctly detect updates. 
This PR makes the JSON parsing fail-safe, returning the value directly if it is not a valid JSON string, and ensures the entity data are in the right shape. 
Closes #4193

fix(core): rework JSON value processing

---

packages/core/src/typings.ts
tests/types.test.ts

This commit fixes an issue where properties with tuple type were being converted to array
when entities were serialized. The fix ensures that tuple type properties are correctly
preserved during the serialization process.

fix(core): prevent tuple type properties from being converted to array when serializing entities

---

docs/docs/events.md
docs/versioned_docs/version-4.5/lifecycle-hooks.md
docs/versioned_docs/version-5.6/events.md

Updated `docs/docs/events.md` and `docs/versioned_docs/version-5.6/events.md` to indicate an issue when using the `@Subscriber()` decorator in addition to instantiating a subscriber class in the configuration.
Related: #4231

docs(core): updated lifecycle docs to indicate subscriber error

---

docs/docs/migrations.md
packages/cli/src/commands/MigrationCommandFactory.ts
packages/core/src/typings.ts
packages/core/src/utils/Configuration.ts
packages/migrations/src/MigrationGenerator.ts
packages/migrations/src/Migrator.ts
tests/features/migrations/Migrator.postgres.test.ts
tests/features/migrations/__snapshots__/Migrator.postgres.test.ts.snap

This PR adds a new option to the `migrations:create` command that allows developers to specify custom names for migration files. Previously, the migration files were automatically named based on the current timestamp, but with this new option, developers can now give the migration file a more descriptive name that is easier to understand and manage.
This feature was inspired by the functionality in Laravel and Ruby on Rails, and I believe it will bring many benefits, including improved readability and organization of migration files.
I created a discussion before on this: https://github.com/mikro-orm/mikro-orm/discussions/3987

feat(migrations): add support for custom migration names

---

docs/docs/decorators.md
docs/docs/defining-entities.md
docs/docs/entity-helper.md
docs/docs/type-safe-relations.md
docs/docs/upgrading-v5-to-v6.md

- Adding a warning icon to the upgrade notes about typescript
- Separating `.load` into a dedicated section for clarity
- Removing stale references to `BaseEntity`

v6 docs updates

---

packages/core/src/entity/EntityRepository.ts
packages/knex/src/SqlEntityRepository.ts
packages/mongodb/src/MongoEntityRepository.ts

Both persist and flush are tied to the EM instance, we have the repository shortcuts, but they feel confusing, as they might give users false sense that they do something only with that given entity type. Maybe we should remove them and make the em getter public instead, to preserve easy access to the functionality.
In preparation for removal of those methods in v6, all the following `EntityRepository` methods are now deprecated:
- persist
- persistAndFlush
- remove
- removeAndFlush
- flush
Additionally, there is a new public `repo.getEntityManager()` method available.
Related: #3989

feat(core): deprecate `persist/flush/remove` methods from `EntityRepository`

---

docs/docs/transactions.md
packages/core/src/EntityManager.ts
packages/core/src/enums.ts
packages/core/src/platforms/Platform.ts
packages/core/src/utils/Configuration.ts
packages/mongodb/src/MongoEntityManager.ts
tests/features/disable-transactions/disable-nested-transactions.test.ts
tests/features/disable-transactions/disable-transactions.test.ts

Is it now possible to disable transactions, either globally via `disableTransactions` config option, or locally when using `em.transactional()`.
```ts
// only the outer transaction will be opened
await orm.em.transactional(async em => {
// but the inner calls to both em.transactional and em.begin will be no-op
await em.transactional(...);
}, { disableTransactions: true });
```
Alternatively, you can disable transactions when creating new forks:
```ts
const em = await orm.em.fork({ disableTransactions: true });
await em.transactional(...); // no-op
await em.begin(...); // no-op
await em.commit(...); // commit still calls `flush`
```
Closes #3747
Closes #3992

feat(core): allow disabling transactions

---

packages/cli/src/esm.ts

Related to https://github.com/mikro-orm/mikro-orm/issues/4265
https://github.com/mikro-orm/mikro-orm/commit/37574723d0ce37a8d0d3284124d836a517f451a7 did fix the call in `cli.ts` but forgot to update `esm.ts`.

fix(cli): await the yargs.parse call in esm.ts

---

docs/docs/repositories.md
docs/docs/upgrading-v5-to-v6.md
packages/core/src/entity/EntityRepository.ts
packages/knex/src/SqlEntityRepository.ts
packages/mongodb/src/MongoEntityRepository.ts
tests/EntityManager.mariadb.test.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite.test.ts
tests/EntityManager.sqlite2.test.ts
tests/EntityManager.sqlite3.test.ts
tests/EntityRepository.test.ts
tests/features/events/events.mysql.test.ts
tests/features/fulltext/full-text-search-tsvector.postgres.test.ts
tests/issues/GH1902.test.ts
tests/issues/GH3988.test.ts
tests/issues/GH4057.test.ts

Following methods are no longer available on the `EntityRepository` instance.
- `persist`
- `persistAndFlush`
- `remove`
- `removeAndFlush`
- `flush`
They were confusing as they gave a false sense of working with a scoped context (e.g. only with a `User` type), while in fact, they were only shortcuts for the same methods of underlying `EntityManager`. You should work with the `EntityManager` directly instead of using a repository when it comes to entity persistence, repositories should be treated as an extension point for custom logic (e.g. wrapping query builder usage).
```diff
-userRepository.persist(user);
-await userRepository.flush();
+em.persist(user);
+await em.flush();
```
> Alternatively, you can use the `repository.getEntityManager()` method to access those methods directly on …

refactor(core): remove `persist/remove/flush` methods from `EntityRepository`

---

packages/core/src/naming-strategy/AbstractNamingStrategy.ts
packages/core/src/naming-strategy/NamingStrategy.ts
packages/migrations-mongodb/src/MigrationGenerator.ts
packages/migrations-mongodb/src/Migrator.ts
packages/migrations/src/MigrationGenerator.ts
tests/features/migrations/Migrator.mongo.test.ts
tests/features/migrations/__snapshots__/Migrator.mongo.test.ts.snap
tests/features/migrations/__snapshots__/Migrator.postgres.test.ts.snap

Fixes:
- Custom migration name was not used in the migration class name for SQL drivers.
- Custom migration name was not used in the migration file name or class name for the Mongo driver.
I am having some trouble running the Mongo tests on Ubuntu 22.04. Getting an error because libcrypto 1.1 is not found.
I manually updated the Mongo snapshot to what I think the correct value is. We'll have to see if that test passes in CI.

fix(migrations): respect custom migration name in migration class names

---

docs/docs/defining-entities.md
packages/core/src/decorators/Enum.ts
packages/core/src/metadata/EntitySchema.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/platforms/Platform.ts
packages/core/src/typings.ts
packages/knex/src/schema/DatabaseSchema.ts
packages/knex/src/schema/DatabaseTable.ts
packages/knex/src/schema/SchemaHelper.ts
packages/knex/src/schema/SqlSchemaGenerator.ts
packages/knex/src/typings.ts
packages/postgresql/src/PostgreSqlConnection.ts
packages/postgresql/src/PostgreSqlPlatform.ts
packages/postgresql/src/PostgreSqlSchemaHelper.ts
tests/SchemaHelper.test.ts
tests/features/schema-generator/__snapshots__/native-enums.postgres.test.ts.snap
tests/features/schema-generator/native-enums.postgres.test.ts

By default, the PostgreSQL driver, represents enums as a text columns with check constraints. Since v6, you can opt-in for a native enums by setting the `nativeEnumName` option.
```ts
@Entity()
export class User {
@Enum({ items: () => UserRole, nativeEnumName: 'user_role' })
role!: UserRole;
}
export enum UserRole {
ADMIN = 'admin',
MODERATOR = 'moderator',
USER = 'user',
}
```
Closes #2764

feat(postgres): add support for native enums

---

packages/mongodb/src/MongoDriver.ts
tests/issues/GH4313.test.ts

Fixes #4313 
I propose to apply `this.renameFields` to `options.orderBy` the same way it is used for `where`

fix(mongo): sorting with UnderscoreNamingStrategy

---

docs/docs/query-conditions.md
docs/versioned_docs/version-5.4/query-conditions.md
docs/versioned_docs/version-5.5/query-conditions.md
docs/versioned_docs/version-5.6/query-conditions.md
docs/versioned_docs/version-5.7/query-conditions.md
packages/postgresql/src/PostgreSqlPlatform.ts
packages/postgresql/src/types/FullTextType.ts
tests/features/fulltext/full-text-search-tsvector.postgres.test.ts

Adds support for a custom regconfig and weighted tsvectors as requested by https://github.com/mikro-orm/mikro-orm/pull/3317#issuecomment-1330035868. 
For more context, see https://github.com/mikro-orm/mikro-orm/pull/3317#issuecomment-1330555809.
Docs: also (hopefully) fixed the tabs which caused the confusion as seen here: https://github.com/mikro-orm/mikro-orm/pull/3317#issuecomment-1279882693.

feat(postgres): add support for weighted tsvectors and a custom regconfig

---

docs/yarn.lock
package.json
packages/better-sqlite/package.json
packages/cli/package.json
packages/core/package.json
packages/entity-generator/package.json
packages/knex/package.json
packages/mariadb/package.json
packages/migrations-mongodb/package.json
packages/migrations/package.json
packages/mikro-orm/package.json
packages/mongodb/package.json
packages/mysql/package.json
packages/postgresql/package.json
packages/reflection/package.json
packages/seeder/package.json
packages/sqlite/package.json
yarn.lock

Please note that I had to change the top level build and clean scripts to build-all and clean-all, otherwise the workspace-tools plugin would call the top level build script as well. This might break CI, so please let me know if/what scripts I have to update.
Instead of installing the workspace-tools plugin we might as well upgrade to yarn v4 (`yarn set version canary`) where it is built-in. The advantage would be that the newer plugin is better (has progress output, parallel builds, etc..) but I guess we will have to bundle a copy of yarn v4 instead of relying on corepack to provide it.

build: use `yarn` instead of `lerna` as a task runner

---

docs/docs/defining-entities.md
docs/docs/type-safe-relations.md
packages/core/src/EntityManager.ts
packages/core/src/decorators/Property.ts
packages/core/src/entity/EntityLoader.ts
packages/core/src/entity/EntityRepository.ts
packages/core/src/entity/Reference.ts
packages/core/src/entity/wrap.ts
packages/core/src/hydration/ObjectHydrator.ts
packages/core/src/serialization/EntitySerializer.ts
packages/core/src/serialization/EntityTransformer.ts
packages/core/src/typings.ts
packages/core/src/utils/EntityComparator.ts
packages/core/src/utils/Utils.ts
tests/EntityManager.mysql.test.ts
tests/entities-sql/Book2.ts
tests/features/auto-flush.postgre.test.ts
tests/features/auto-refreshing.postgre.test.ts
tests/features/embeddables/__snapshots__/entities-in-embeddables.mongo.test.ts.snap
tests/features/embeddables/__snapshots__/entities-in-embeddables.postgres.test.ts.snap
tests/features/embeddables/__snapshots__/polymorphic-embedded-entities.sqlite.test.ts.snap
tests/features/lazy-scalar-properties/lazy-scalar-properties.mysql.test.ts

Similarly to the `Reference` wrapper, we can also wrap scalars with `Ref` into a `ScalarReference` object. This is handy for lazy scalar properties.
```ts
@Property({ lazy: true, ref: true })
passwordHash!: Ref<string>;
```
The `Ref` type automatically resolves to `ScalarReference` for non-object types. You can use it explicitly if you want to wrap an object scalar property (e.g. JSON value).
```ts
const user = await em.findOne(User, 1);
const passwordHash = await user.passwordHash.load();
```

feat(core): allow using `Ref` wrapper on scalar properties

---

docs/docs/entity-manager.md
docs/docs/query-builder.md
docs/docs/raw-queries.md
docs/docs/upgrading-v5-to-v6.md
packages/core/src/utils/RawQueryFragment.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/AbstractSqlPlatform.ts
packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
packages/knex/src/typings.ts
tests/QueryBuilder.test.ts
tests/features/filters/filters.postgres.test.ts
tests/features/schema-generator/native-enums.postgres.test.ts

feat(core): add `sql.ref()` helper

---

docs/docs/defining-entities.md
docs/versioned_docs/version-4.5/defining-entities.md
docs/versioned_docs/version-5.4/defining-entities.md
docs/versioned_docs/version-5.5/defining-entities.md
docs/versioned_docs/version-5.6/defining-entities.md
docs/versioned_docs/version-5.7/defining-entities.md

Following https://github.com/mikro-orm/mikro-orm/discussions/4403
Since Postgres 13 no additional module is necessary to use 'gen_random_uuid' function.

docs: postgres >= 13 has built-in  uuid function "get_random_uuid"

---

packages/core/src/entity/EntityLoader.ts
packages/core/src/entity/WrappedEntity.ts
packages/core/src/typings.ts
tests/issues/GH4343.test.ts

This reworks the fix for #4213 which broke populating in parallel.
Closes #4343

fix(core): fix populating relations in parallel via `Promise.all`

---

packages/knex/src/AbstractSqlDriver.ts
tests/features/upsert/upsert.test.ts

…hen upserting with embeddables
Currently, when you run upsert on an entity with an embeddable, the name of the embeddable is included in the returning statement and causing `InvalidFieldNameException`.
The produced query without the change:
``` 
insert into `foo_bar_with_embeddable` (`_id`) values (1) on conflict (`_id`) do nothing returning `fooBarEmbeddable`, `foo_bar_embeddable_name`;
````

fix(core): fix returning clause for upsert with embeddables

---

docs/docs/custom-types.md
packages/core/src/platforms/Platform.ts
packages/core/src/types/BlobType.ts
packages/core/src/types/Uint8ArrayType.ts
packages/core/src/types/index.ts
packages/core/src/typings.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite2.test.ts
tests/entities-schema/FooBar4.ts
tests/entities-sql/FooBar2.ts
tests/entities/FooBar.ts

The goal is to work properly with entities that have properties of type Uint8Array. Those properties should automatically be stored as binary data and converted back to Uint8Array without specifying a type (analogous to Buffer).
Also when converting entities to DTOs Uint8Array types should be kept unchanged.
Closes #4418

feat(core): support Uint8Array

---

packages/core/src/utils/Configuration.ts

As documented [here](https://mikro-orm.io/docs/configuration#connection) it's possible to use `clientUrl` to pass database options in one string.
However it's broken for SQLite when connection string doesn't contain some options (such as host): library throws an error
```
✖ The "path" argument must be of type string. Received undefined
stack: >
SqliteConnection.connect
(node_modules/@mikro-orm/sqlite/SqliteConnection.js:10:60)
SqliteDriver.connect (node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:53:31)
MikroORM.connect (node_modules/@mikro-orm/core/MikroORM.js:70:46)
Function.init (node_modules/@mikro-orm/core/MikroORM.js:39:23)
```
Example:
```js
MikroORM.init({
type: 'sqlite',
clientUrl: 'sqlite:///:memory:',
})
```
Workaround:
```js
MikroORM.init({
type: 'sqlite',
clientUrl: …
```

fix(sqlite): allow using `clientUrl` without a `host`

---

docs/docs/upgrading-v5-to-v6.md
packages/core/src/serialization/EntitySerializer.ts
packages/core/src/typings.ts
tests/EntityHelper.mongo.test.ts
tests/features/serialization/GH3788.test.ts
tests/features/serialization/GH4263.test.ts
tests/features/serialization/explicit-serialization.test.ts

This pull request aims to fix the intellisense issue with `serialize` in V5 while keeping the v5 API.
related: https://github.com/mikro-orm/mikro-orm/blob/v6/docs/docs/upgrading-v5-to-v6.md#serialize-helper-always-returns-array
What do you think about this ? 
Also should this pull request be applied to master ?

refactor(core): keep v5 `serialize` api

---

packages/core/src/typings.ts
packages/seeder/src/Seeder.ts

I noticed the `Seeder#run` method only allows returning a `Promise<void>`, although it is completely possible for it to return only `void`, without being async.
This isn't anything major, but I have ESLint rules that forbid me to have an `async` function if it isn't really async, and i'd like to stick by it. It'd be great if the signature of the function didn't force us to have it `async`.
Thank you!

fix(seeder): allow run method to return without promise

---

packages/core/src/entity/ArrayCollection.ts
packages/core/src/entity/Collection.ts
packages/core/src/entity/EntityLoader.ts
packages/knex/src/AbstractSqlDriver.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mongo2.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite2.test.ts
tests/entities/Author.ts
tests/entities/Book.ts
tests/features/cursor-based-pagination/__snapshots__/complex-cursor.test.ts.snap
tests/features/custom-order/custom-order.mysql.test.ts
tests/features/custom-order/custom-order.postgres.test.ts
tests/features/custom-order/custom-order.sqlite.test.ts
tests/features/embeddables/entities-in-embeddables.mongo.test.ts
tests/features/embeddables/entities-in-embeddables.postgres.test.ts
tests/features/joined-strategy.postgre.test.ts
tests/features/lazy-scalar-properties/lazy-scalar-properties.mongo.test.ts
tests/features/lazy-scalar-properties/lazy-scalar-properties.mysql.test.ts
tests/features/multiple-schemas/GH3177.test.ts
tests/features/multiple-schemas/multiple-schemas.postgres.test.ts
tests/features/partial-loading/partial-loading.mongo.test.ts
tests/features/partial-loading/partial-loading.mysql.test.ts
tests/features/serialization/GH4464.test.ts
tests/issues/GH1657.test.ts
tests/issues/GH1882.test.ts
tests/issues/GH2784.test.ts

This unifies the population mechanism for to-many relations by using the `em.populate()` internally.
Previously, the `Collection.init` (and methods using it, e.g. `loadItems`) were using custom implementation, which in some cases resulting in different results as opposed to `em.populate()`. With this PR, the `init` method is also using `em.populate`, yielding the same results as if you would populate the relation.
Closes #4464

fix(core): rework `Collection` initialization to use `em.populate()`

---

packages/better-sqlite/src/BetterSqlitePlatform.ts
packages/core/src/entity/WrappedEntity.ts
packages/core/src/platforms/Platform.ts
packages/core/src/types/JsonType.ts
packages/core/src/utils/EntityComparator.ts
packages/core/src/utils/Utils.ts
packages/mariadb/src/MariaDbConnection.ts
packages/mysql/src/MySqlConnection.ts
packages/postgresql/src/PostgreSqlConnection.ts
packages/sqlite/src/SqlitePlatform.ts
tests/EntityManager.mysql.test.ts
tests/bootstrap.ts
tests/features/custom-types/json-properties.test.ts
tests/features/embeddables/__snapshots__/entities-in-embeddables.postgres.test.ts.snap
tests/features/migrations/Migrator.postgres.test.ts
tests/features/migrations/Migrator.sqlite.test.ts
tests/features/schema-generator/SchemaGenerator.mysql.test.ts
tests/features/schema-generator/SchemaGenerator.mysql2.test.ts
tests/features/schema-generator/SchemaGenerator.postgres.test.ts

The JSON properties are no longer mapped automatically on the driver level. The mapping from JSON strings is now implemented in the result mapping layer
The motivation behind this change was to support property mapping of numeric values and finally put an end to the JSON mapping bugs, which were mostly originating from small differences and bugs in how the underlying libraries were trying to do it on their own.
Closes #4476

fix(core): rework JSON property hydration

---

packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/metadata/MetadataValidator.ts
packages/core/src/utils/Configuration.ts
tests/MetadataValidator.test.ts
tests/MikroORM.test.ts

This PR adds a new option to the `discovery` object called `checkDuplicateEntities`. This new option aims to allow the client code to control the behavior regarding duplicated entities discovered. There might be situations where we just want to ignore the duplicates.
Closes https://github.com/mikro-orm/nestjs/issues/132

feat(core): allow disabling duplicate entities discovery validation

---

packages/core/src/utils/ConfigurationLoader.ts
tests/features/cli/CLIHelper.test.ts

Fixes #4679. See the linked issue for the full context of this PR.

fix(core): default baseUrl value to '.' when registering ts-node

---

docs/docs/entity-manager.md
package.json
packages/core/src/EntityManager.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/unit-of-work/ChangeSetPersister.ts
packages/core/src/utils/index.ts
packages/core/src/utils/upsert-utils.ts
packages/knex/src/AbstractSqlDriver.ts
packages/mongodb/src/MongoConnection.ts
packages/mongodb/src/MongoDriver.ts
tests/features/upsert/GH4242-2.test.ts
tests/features/upsert/GH4242.test.ts
tests/features/upsert/__snapshots__/upsert.test.ts.snap
tests/features/upsert/upsert.test.ts
yarn.lock

Adds 4 new options to `em.upsert()`:
- `onConflictFields?: (keyof T)[]` to control the conflict clause
- `onConflictAction?: 'ignore' | 'merge'` used ignore and merge as that is how the QB methods are called
- `onConflictMergeFields?: (keyof T)[]` to control the merge clause
- `onConflictExcludeFields?: (keyof T)[]` to omit fields from the merge clause
Closes #4325
Closes #4602

feat(core): allow fine-grained control over `em.upsert()`

---

packages/knex/src/query/QueryBuilder.ts
packages/knex/src/typings.ts
tests/features/paginate-flag.postgres.test.ts
tests/issues/GH3871.test.ts

When using joined strategy, the `populateWhere` condition is now applied to the joins via `on` conditions instead of using a `where` condition. This aligns how the two loading strategies work, as the `populateWhere` will affect only what gets joined, but not the root entity query.
Closes #3871

fix(core): use join on conditions for `populateWhere`

---

packages/core/src/EntityManager.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/QueryBuilder.ts
tests/features/filters/filters.postgres.test.ts
tests/features/joined-strategy.postgre.test.ts

Previously, the filters were applied only when using the select-in strategy, as part of the `where` condition. With this change, when using the joined strategy, filters will be also applied to the query, via `join on` conditions.
Closes #704
Closes #2440

fix(core): respect filters with joined loading strategy

---

docs/docs/installation.md
packages/core/src/utils/ConfigurationLoader.ts
tests/features/cli/CLIHelper.test.ts

This PR introduces two new options to allow `.ts` files as configs when `ts-node` is not enabled:
- `alwaysAllowTs` flag in `mikro-orm` section of `package.json`
- `MIKRO_ORM_CLI_ALWAYS_ALLOW_TS` environment variable
Fixes #4701

feat(core): Allow to use `.ts` files as configuration without `ts-node`

---

packages/core/src/utils/QueryHelper.ts
tests/EntityManager.mongo.test.ts
tests/SmartQueryHelper.test.ts

Fix case of `processWhere` returning empty object when the where clause is an entity with an int pk of 0

fix(core): fix query processing when PK is falsy

---

docs/docs/custom-types.md
docs/docs/defining-entities.md
docs/docs/upgrading-v5-to-v6.md
docs/docs/using-bigint-pks.md
packages/core/src/serialization/EntityTransformer.ts
packages/core/src/types/BigIntType.ts
packages/core/src/typings.ts
packages/core/src/utils/EntityComparator.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/entities-sql/BookTag2.ts
tests/features/custom-types/GH4249.test.ts
tests/features/embeddables/nested-embeddables-order-of-discovery.test.ts
tests/features/entity-generator/__snapshots__/EntityGenerator.test.ts.snap
tests/features/find-one-or-fail-strict.test.ts
tests/features/single-table-inheritance/GH2364.test.ts
tests/features/virtual-entities/virtual-entities.postgres.test.ts
tests/issues/GH1038.test.ts
tests/issues/GH1538.test.ts
tests/issues/GH1882.test.ts
tests/issues/GH1968.test.ts
tests/issues/GH2379.test.ts
tests/issues/GH2410.test.ts
tests/issues/GH3739.test.ts
tests/issues/GH4227.test.ts
tests/issues/GH482.test.ts
tests/issues/GH940.test.ts
tests/types.test.ts

The default mapping of `bigint` columns is now using the native JavaScript `BigInt`, and is configurable, so it can also map to numbers or strings:
```ts
@PrimaryKey()
id0: bigint; // type is inferred
@PrimaryKey({ type: new BigIntType('bigint') })
id1: bigint; // same as `id0`
@PrimaryKey({ type: new BigIntType('string') })
id2: string;
@PrimaryKey({ type: new BigIntType('number') })
id3: number;
```

feat(core): native `BigInt` support

---

docs/docs/json-properties.md
packages/better-sqlite/src/BetterSqliteSchemaHelper.ts
packages/core/src/metadata/MetadataValidator.ts
packages/core/src/naming-strategy/AbstractNamingStrategy.ts
packages/core/src/platforms/Platform.ts
packages/knex/src/AbstractSqlPlatform.ts
packages/knex/src/schema/DatabaseTable.ts
packages/knex/src/schema/SqlSchemaGenerator.ts
packages/knex/src/typings.ts
packages/mariadb/src/MariaDbSchemaHelper.ts
packages/mysql/src/MySqlPlatform.ts
packages/mysql/src/MySqlSchemaHelper.ts
packages/postgresql/src/PostgreSqlPlatform.ts
packages/postgresql/src/PostgreSqlSchemaHelper.ts
packages/sqlite/src/SqliteSchemaHelper.ts
tests/features/schema-generator/__snapshots__/index-diffing.mysql.test.ts.snap
tests/features/schema-generator/__snapshots__/index-diffing.postgres.test.ts.snap
tests/features/schema-generator/__snapshots__/index-diffing.sqlite.test.ts.snap
tests/features/schema-generator/index-diffing.mysql.test.ts
tests/features/schema-generator/index-diffing.postgres.test.ts
tests/features/schema-generator/index-diffing.sqlite.test.ts

To create an index on a JSON property, use an entity-level `@Index()` decorator with a dot path:
```ts
@Entity()
@Index({ properties: 'metaData.foo' })
@Index({ properties: ['metaData.foo', 'metaData.bar'] }) // compound index
export class Book {
@Property({ type: 'json', nullable: true })
metaData?: { foo: string; bar: number };
}
```
In PostgreSQL, this will generate a query like the following:
```sql
create index "book_meta_data_foo_index" on "book" (("meta_data"->>'foo'));
```
To create a unique index, use the `@Unique()` decorator:
```ts
@Entity()
@Unique({ properties: 'metaData.foo' })
@Unique({ properties: ['metaData.foo', 'metaData.bar'] }) // compound unique index
export class Book {
@Property({ type: 'json', nullable: true })
metaData?: { foo: string; bar: number };
}
```
In …

feat(core): add support for indexes on JSON properties

---

packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/typings.ts
packages/knex/src/AbstractSqlDriver.ts
tests/features/virtual-entities/virtual-entities.sqlite.test.ts

fix(knex): allow using knex query builder as virtual entity expression

---

docs/docs/multiple-schemas.md
docs/versioned_docs/version-5.8/multiple-schemas.md
packages/core/src/EntityManager.ts
packages/core/src/unit-of-work/UnitOfWork.ts
packages/core/src/utils/RequestContext.ts
tests/EntityManager.mongo.test.ts
tests/features/multiple-schemas-entity-manager/multiple-schemas-entity-manager.postgres.test.ts

Hi,
I want to start with thanking you all for this great ORM that is so actively maintained and offer so many great features. One thing that really catches my eye is the per request (shell)EntityManager that I think will make this ORM a winner when it comes to multi tenancy. Almost all of the other big ORM libraries are based on a global concept. 
My aim with this PR is to make a shoot at implementing schema based multi tenancy support with help of the per request EntityManager. With this PR it's possible to set a schema when forking the EntityManager. That schema will be applied as a default schema if no other schema is present. It makes use of the schema options introduced in: https://github.com/mikro-orm/mikro-orm/pull/2296 
If this seems like an approach to pursue there is some more …

feat(core): allow setting default `schema` on `EntityManager`

---

docs/docs/query-builder.md
docs/docs/upgrading-v5-to-v6.md
packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
packages/knex/src/typings.ts
tests/QueryBuilder.test.ts

Sometimes you might want to join a relation, but want to have more control over the query. The ORM allows you to override the join target with a sub-query, while keeping the original metadata for hydration:
```ts
// subquery can be a knex query builder as well
const subquery = await em.createQueryBuilder(Book, 'b')
.where({ ... })
.orderBy({ title: 'asc' }).limit(1);
const authors = await em.createQueryBuilder(Author, 'a')
.select('*')
// pass in both the property path and the subquery into the first argument as a tuple
.leftJoinAndSelect(['a.books', subquery], 'b')
// you can join more relations on top of the subquery join
.leftJoinAndSelect('b.tags', 't')
.getResultList();
```
This will produce query similar to the following:
```sql
select `a`.*,
`b`.`id` as `b__id`, `b`.`title` as …
```

feat(query-builder): allow joining sub-queries

---

packages/core/src/EntityManager.ts
packages/core/src/entity/EntityRepository.ts
packages/core/src/typings.ts
tests/EntityManager.postgre.test.ts
tests/entities-sql/Book2.ts
tests/features/optimistic-lock/GH3209.test.ts
tests/issues/GH1592.test.ts
tests/issues/GH3429.test.ts
tests/issues/GH3738.test.ts
tests/issues/GH3812.test.ts
tests/issues/GH3941.test.ts
tests/issues/GH4323.test.ts
tests/perf/creating-large-collections.test.ts

When using `em.create()`, we can create the entity graph in one step, including relations. This commit makes the typing strict for the relations too, requiring their mandatory props to be present
There is one common issue with this - the `em.create` automatically propagates things to inverse sides, in other words, doing this is completely fine, as the author will be propagated to the new books:
```ts
em.create(Author, {
name: '...',
books: [{ title: 'foo' }], // Book.author is required, but will be propagated from the upper scope
});
```
To get around it, the child properties matching their parent type are automatically considered as optional - in other words, since we are processing contents of `Author.books`, we will make all properties of type `Author` in the `Author.books` as …

fix(core): make `em.create` strictly typed for relations too

---

docs/docs/property-validation.md
docs/src/css/custom.css
packages/core/src/index.ts
packages/core/src/typings.ts
tests/entities-sql/Author2.ts
tests/entities-sql/BaseEntity2.ts
tests/entities-sql/Publisher2.ts
tests/features/composite-keys/GH1079.test.ts

```ts
import { Opt, Entity, PrimaryKey, Property } from '@mikro-orm/core';
@Entity()
class User {
@PrimaryKey()
id!: number;
@Property()
firstName!: string;
@Property()
middleName: string & Opt = '';
@Property()
lastName!: string;
@Property({ persist: false })
get fullName(): string & Opt {
return `${this.firstName} ${this.middleName} ${this.lastName}`;
}
}
```

feat(core): add `Opt` type as an alternative to `OptionalProps` symbol

---

packages/postgresql/src/PostgreSqlPlatform.ts
tests/issues/GH4796.test.ts

fix(postgres): escape array literal values containing backslash

---

packages/core/src/EntityManager.ts
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/entity/ArrayCollection.ts
packages/core/src/entity/Collection.ts
packages/core/src/unit-of-work/ChangeSetComputer.ts
packages/core/src/unit-of-work/UnitOfWork.ts
packages/core/src/utils/Utils.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/PivotCollectionPersister.ts
packages/knex/src/query/QueryBuilder.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite.test.ts
tests/EntityManager.sqlite2.test.ts
tests/features/composite-keys/composite-keys.mysql.test.ts
tests/features/composite-keys/composite-keys.sqlite.test.ts
tests/features/composite-keys/custom-pivot-entity-auto-discovery.sqlite.test.ts
tests/features/composite-keys/custom-pivot-entity-wrong-order.sqlite.test.ts
tests/features/composite-keys/custom-pivot-entity.sqlite.test.ts
tests/features/entity-assigner/GH1811.test.ts
tests/features/filters/filters.postgres.test.ts
tests/features/multiple-schemas-entity-manager/multiple-schemas-entity-manager.postgres.test.ts
tests/features/multiple-schemas/GH3177.test.ts
tests/features/multiple-schemas/multiple-schemas.postgres.test.ts
tests/features/result-cache/result-cache.postgre.test.ts
tests/features/sharing-column-in-composite-pk-fk.test.ts
tests/issues/GH1041.test.ts
tests/issues/GH4027.test.ts

Implements diffing for inverse sides of M:N relations (for SQL drivers). This was previously working only if the items were initialized.
```ts
const tag = await em.findOne(BookTag, 1);
// tag.books in an inverse side
tag.books.add(em.getReference(Book, 123));
await em.flush();
```
The M:N updates are now also batched.
Closes #4564

feat(core): respect updates to M:N inverse sides and batch them

---

docs/docs/configuration.md
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/metadata/MetadataStorage.ts
packages/core/src/typings.ts
packages/core/src/utils/Configuration.ts
tests/features/multiple-schemas/__snapshots__/discovery-hooks.test.ts.snap
tests/features/multiple-schemas/discovery-hooks.test.ts

Sometimes you might want to alter some behavior of the ORM on metadata level. You can use the `onMetadata` hook to modify the metadata. Let's say you want to use your entities with different drivers, and you want to use some driver specific feature. Using the `onMetadata` hook, you can modify the metadata dynamically to fit the drivers requirements.
The hook will be executed before the internal process of filling defaults, so you can think of it as modifying the property options in your entity definitions, they will be respected e.g. when inferring the column type.
> The hook can be async, but it will be awaited only if you use the async `MikroORM.init()` method, not with the `MikroORM.initSync()`.
```ts
import { EntityMetadata, MikroORM, Platform } from '@mikro-orm/sqlite';
const orm = …
```

feat(core): add discovery hooks `onMetadata` and `afterDiscovered`

---

packages/core/src/utils/Utils.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/QueryBuilder.ts
tests/EntityManager.mysql.test.ts
tests/issues/GH4741.test.ts
tests/issues/GH4816.test.ts

Previously, the `qb.execute()` method returned cartesian product when joining to-many relations. Now the results will be automatically merged, as if you would map the results via `qb.getResult()`.
Closes #4816
Related #4741

fix(query-builder): merge raw join results in `qb.execute()`

---

packages/core/src/utils/Utils.ts
packages/reflection/src/TsMorphMetadataProvider.ts
tests/Utils.test.ts

This PR addresses an issue where relative paths with leading slashes and dots were not being stripped correctly. The problem arises when the 'path' contains multiple leading slashes like `../../`, as the current logic strips it to `/../`, which is incorrect and prevents the entity from being discovered.
This code modification ensures that any dots followed by slashes are stripped to provide the full path without any dots and slashes at the beginning.
**Please note:** that the current behavior is such that if you pass `./my/path` the result is `/my/path` However, with the updated code, the result will be `my/path` This change is made because, in the end, we use the resulting path to check if the `source` contains the path using `endsWith`, and the leading slash is unnecessary for this …

fix(reflection): ensure complete stripping of relative paths with multiple leading slashes

---

packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
tests/features/multiple-schemas-entity-manager/multiple-schemas-e-manager-q-builder.test.ts

- QueryBuilder will inherit schema from EntityManager (if set)
- QueryBuilder can now join entities that belong in a different schema than the main entity.
Previously if you had an entity that belongs to schema n2 which have a FK to an entity that does not exist in n2 the query will fail since it will use `n2.SubDomain`. If you used `withSchema('n5')`, then it will fail since `n5.Domain` does not exist.
```
@Entity({ schema: 'n2' })
class Domain {
@PrimaryKey()
id!: number;
@OneToMany(() => SubDomain, e => e.domain)
subDomain = new Collection<SubDomain>(this);
}
@Entity({ schema: '*' })
class SubDomain {
@PrimaryKey()
id!: number;
@ManyToOne(() => Domain, { nullable: true })
domain?: Domain;
}
```
Im wondering what you think about this approach. One thing I'm a bit divided about is the …

feat(query-builder): respect `EntityManager` schema

---

docs/docs/configuration.md
packages/core/src/utils/Configuration.ts
packages/core/src/utils/QueryHelper.ts
packages/core/src/utils/Utils.ts
packages/knex/src/query/QueryBuilderHelper.ts
tests/EntityManager.sqlite.test.ts
tests/QueryBuilder.test.ts
tests/bootstrap.ts

The ORM will treat explicitly defined `undefined` values in your `em.find()` queries as `null`s. If you want to ignore them instead, use `ignoreUndefinedInQuery` option:
```ts
MikroORM.init({
ignoreUndefinedInQuery: true,
});
// resolves to `em.find(User, {})`
await em.find(User, { email: undefined, { profiles: { foo: undefined } } });
```
Closes #4873

feat(core): allow ignoring `undefined` values in `em.find` queries

---

docs/docs/unit-of-work.md
packages/core/src/EntityManager.ts
packages/core/src/entity/EntityAssigner.ts
packages/core/src/unit-of-work/UnitOfWork.ts
tests/features/multiple-schemas/GH3177.test.ts
tests/features/unit-of-work/GH4905.test.ts
tests/features/unit-of-work/UnitOfWork.test.ts
tests/issues/GH811.test.ts

When you `em.persist()` a new entity which has the primary key value, it will be automatically added to the identity map. This means that a following call to `em.findOne()` based on its primary key will just return the same unmanaged entity instance instead of querying the database.
> Such entity is added to the identity map, but still remains unmanaged - it does not have a reference to the `EntityManager` yet.
```ts
// primary key value provided, will be added to the identity map
const jon = em.create(Author, {
id: 1,
name: 'Jon',
email: 'foo@bar.com',
});
// this will not query the database
const jon2 = await em.findOne(Author, 1);
console.log(jon === jon2); // true
await em.flush(); // this inserts the entity
```
If you called `em.persist()` an entity without the primary key value, the …

feat(core): add entity to identity map on `em.persist()`

---

tests/features/seeder/seed-manager.test.ts

The test suite still doesn't fully pass on Windows, even with this, but this test is an easy win in that direction.
Remaining test failures on windows are mostly due to mocks and/or interaction with ts-node on Windows vs. Linux/WSL.

fix(test): fixed seed-manager.test.js on windows

---

.eslintrc.js
packages/cli/package.json
scripts/copy.mjs
tests/MikroORM.test.ts
tests/features/cli/CLIHelper.test.ts

In order to do so without breaking Unix compatibility, and still respect Jest's mock rules (namely, no imports for mocked module names), additional mocks are added where the path's slashes are replaced.
Utils.normalizePath() or path.resolve() is used in other places, based on the expected value.
Also fixed building on Windows, by making copy.mjs be responsible for copying esm.cmd.

test: all tests can now run on Windows

---

docs/docs/virtual-entities.md
packages/core/src/EntityManager.ts
packages/core/src/metadata/MetadataValidator.ts
tests/MetadataValidator.test.ts
tests/features/virtual-entities/virtual-entities.postgres.test.ts

Virtual entities can now contain also to-one relations (M:1 and 1:1 owners).
Such relations are always populated via `select-in` strategy.

feat(core): allow M:1 and 1:1 relations in virtual entities

---

docs/docs/entity-generator.md
packages/core/src/utils/Configuration.ts
packages/entity-generator/src/EntityGenerator.ts
packages/entity-generator/src/SourceFile.ts
tests/features/entity-generator/TypesForScalarDecorators.test.ts
tests/features/entity-generator/__snapshots__/TypesForScalarDecorators.test.ts.snap

I tried to run the tests with `@swc/jest` (yes, I did saw #3200, but I thought I take a fresh crack at it, since that branch is over a year old...), and an interesting error that popped up was the inability to discover the entity type.
Featuring the type is one way to avoid this... another way is to not use SWC or to use `EntitySchema` (which is the solution I intend to use for my projects personally...).
So... for users who intend to use SWC, and would like to use decorators, I think it would be very beneficial to be able to generate the "type" option. For everyone else, it would just provide a minor boost in startup performance of a project using generated entities with decorators.
Being a very limited option in scope, implementation was easy. Honestly, whether this should be an option …

feat(entity-generator): added ability to output type option in decorator

---

docs/docs/dataloaders.md

I released [mikro-orm-find-dataloader](https://github.com/darkbasic/mikro-orm-dataloaders) as a separate package so that it can get more testing before deciding if we are going to merge it in the next cycle or not. The package has CI configured and working but the tests and the examples are minimal yet, mostly to test the continuous integration and catch major regressions. The lion's share of the testing is still done via existing tests in my own application, but I plan to gradually port them into `mikro-orm-find-dataloader` while also improving the codebase to eventually merge it. I already updated my app to use `mikro-orm-find-dataloader`.

docs: link mikro-orm-find-dataloader

---

packages/core/src/EntityManager.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/entity/EntityLoader.ts
packages/core/src/utils/Cursor.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/ArrayCriteriaNode.ts
packages/knex/src/query/CriteriaNode.ts
packages/knex/src/query/ObjectCriteriaNode.ts
packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
packages/knex/src/query/ScalarCriteriaNode.ts
packages/knex/src/typings.ts
packages/sqlite/src/SqlitePlatform.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/QueryBuilder.test.ts
tests/features/composite-keys/composite-keys.mysql.test.ts
tests/features/custom-types/custom-types.mysql.test.ts
tests/features/filters/filters.postgres.test.ts
tests/features/joined-strategy.postgre.test.ts
tests/features/multiple-schemas-entity-manager/multiple-schemas-e-manager-q-builder.test.ts
tests/features/partial-loading/partial-loading.mysql.test.ts
tests/issues/GH1041.test.ts
tests/issues/GH1126.test.ts
tests/issues/GH1657.test.ts

The joined strategy now supports `populateWhere: 'all'`, which is the default behavior, and means "populate the full relations regardless of the where condition". This was previouly not working with the joined strategy, as it was reusing the same join clauses as the where clause. With this PR, the joined strategy will use a separate join branch for the populated relations.
**This aligns the behavior between the strategies.**
The `order by` clause is shared for both the join branches and a new `populateOrderBy` option is added to allow control of the order of populated relations separately.

feat(sql): rework joined strategy to support the default `populateWhere: 'all'`

---

docs/docs/entity-generator.md

Reorganized the config options into a table,
and documented the generate() options in a separate table.
Also added a note about the entity-generator needing to be installed, be aligned with the database driver, and the lack of support for MongoDB.

docs(entity-generator): install note and option reorganization

---

docs/docs/entity-generator.md
docs/docs/upgrading-v5-to-v6.md
packages/cli/src/commands/GenerateEntitiesCommand.ts
packages/core/src/typings.ts
packages/core/src/utils/Configuration.ts
packages/entity-generator/src/EntityGenerator.ts
packages/knex/src/schema/DatabaseTable.ts
tests/features/entity-generator/EntityGenerator.mysql.test.ts
tests/features/entity-generator/EntityGenerator.postgres.test.ts
tests/features/entity-generator/EntityGenerator.test.ts
tests/features/entity-generator/ScalarPropsForFks.mysql.test.ts

Add support for all the options both via ORM config and `GenerateOptions`.
Also renames the `baseDir` option to `path` to match how it's called in the CLI command.

feat(entity-generator): allow local and global configuration of all options

---

docs/docs/upgrading-v5-to-v6.md
packages/core/src/MikroORM.ts
packages/core/src/errors.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/metadata/MetadataValidator.ts
packages/core/src/utils/Configuration.ts
tests/MetadataValidator.test.ts

When you use the same `fieldName` for two properties in one entity, error will be thrown:
```ts
@Entity()
class User {
@PrimaryKey()
id!: number;
@Property({ name: 'custom_name' })
name!: number;
@Property({ name: 'custom_name' })
age!: number;
}
```
This does not apply to virtual properties:
```ts
@Entity()
class User {
@PrimaryKey()
id!: number;
@ManyToOne(() => User, { name: 'parent_id' })
parent!: User;
@Property({ name: 'parent_id',  })
parentId!: number;
}
```
> This validation can be disabled via `discovery.checkDuplicateFieldNames` ORM config option.
Closes #4359

feat(core): validate duplicate field names

---

docs/docs/configuration.md
docs/docs/migrations.md
docs/docs/quick-start.md
docs/docs/schema-generator.md
docs/docs/upgrading-v5-to-v6.md
packages/cli/src/CLIHelper.ts
packages/core/src/utils/ConfigurationLoader.ts
tests/MikroORM.test.ts
tests/features/cli/CLIHelper.test.ts

Also renames `MIKRO_ORM_VERBOSE` to `MIKRO_ORM_CLI_VERBOSE` and adds it to the CLI settings interface so it can be set in the package.json settings.
BREAKING CHANGE

refactor: rename `MIKRO_ORM_CLI` to `MIKRO_ORM_CLI_CONFIG`

---

docs/docs/serializing.md
packages/core/src/index.ts
packages/core/src/typings.ts
tests/entities-sql/Author2.ts
tests/features/result-cache/GH3294.test.ts
tests/issues/GH3429.test.ts

`Hidden` type is an alternative to the `HiddenProps` symbol. It works the same as the `Opt` type (an alternative for `OptionalProps` symbol), and can be used in two ways:
- with generics: `hiddenField?: Hidden<string>;`
- with intersections: `hiddenField?: string & Hidden;`
Both will work the same, and can be combined with the `HiddenProps` symbol approach.
```ts
@Entity()
class Book {
@Property({ hidden: true })
hiddenField: Hidden<Date> = Date.now();
@Property({ hidden: true, nullable: true })
otherHiddenField?: string & Hidden;
}
```

feat(core): add `Hidden`type as an alternative to `HiddenProps` symbol

---

packages/core/src/index.ts

Exports `FilterValue` from typings
closes https://github.com/mikro-orm/mikro-orm/issues/5011

chore: expose `FilterValue` type

---

docs/docs/upgrading-v5-to-v6.md
packages/core/src/entity/Reference.ts
tests/EntityManager.mongo.test.ts
tests/issues/GH5003.test.ts

`Reference` wrapper holds an identity—this means its instance is bound to the underlying entity. This imposes a problem when you try to change the wrapped entity, as the same instance of the `Reference` wrapper can be present on other places in the entity graph. For this reason, the `set` method is no longer public, as replacing the reference instance should be always preferred.
```diff
-book.author.set(other);
+book.author = ref(other);
```
Closes #5003

fix(core): mark `Reference.set()` as private

---

packages/core/src/connections/Connection.ts

Closes #4997 
This allows for developers to select the database schema they want to use inside the clientUrl instead of having to manually pass down the "schema" property.
So basically this:
`
defineConfig({
clientUrl: "postgres://localhost:5432/mydb?schema=otherschema",
}),
`
instead of this:
`
defineConfig({
clientUrl: "postgres://localhost:5432/mydb?schema=thisisirrelevant",
schema: "otherschema",
}),
`

feat(core): respect `schema` parameter in `clientUrl`

---

docs/docs/logging.md
packages/core/src/EntityManager.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/enums.ts
packages/core/src/logging/Logger.ts
packages/core/src/utils/RequestContext.ts
packages/knex/src/AbstractSqlConnection.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/SqlEntityManager.ts
packages/knex/src/query/QueryBuilder.ts
packages/mongodb/src/MongoConnection.ts
tests/EntityManager.postgre.test.ts
tests/features/logging/logging.test.ts

The logger context can now be also set on `EntityManager` level, e.g. via `em.fork()`:
```ts
const fork = em.fork({
loggerContext: { meaningOfLife: 42 },
});
const res = await fork.findAll(Author);
```
Closes #5022

feat(core): allow setting logger context on EM level

---

docs/docs/entity-manager.md
packages/core/src/EntityManager.ts
packages/core/src/decorators/Entity.ts
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/entity/EntityLoader.ts
packages/core/src/entity/EntityRepository.ts
packages/core/src/index.ts
packages/core/src/platforms/Platform.ts
packages/core/src/serialization/EntitySerializer.ts
packages/core/src/serialization/EntityTransformer.ts
packages/core/src/serialization/SerializationContext.ts
packages/core/src/typings.ts
packages/core/src/utils/Cursor.ts
packages/core/src/utils/Utils.ts
packages/knex/src/AbstractSqlDriver.ts
packages/mongodb/src/MongoDriver.ts
packages/mongodb/src/MongoPlatform.ts
tests/DatabaseDriver.test.ts
tests/EntityManager.sqlite2.test.ts
tests/features/cursor-based-pagination/simple-cursor.test.ts
tests/features/partial-loading/partial-loading-exclude.mysql.test.ts
tests/features/partial-loading/partial-loading.mysql.test.ts
tests/repositories/AuthorRepository.ts

Adds the `exclude` option, which will omit the provided properties and select everything else:
```ts
const author = await em.findOne(Author, '...', {
exclude: ['email', 'books.price'],
populate: ['books'], // unlike with `fields`, you need to explicitly populate the relation here
});
```

feat(core): add `FindOptions.exclude`

---

docs/docs/upgrading-v5-to-v6.md
packages/core/src/entity/BaseEntity.ts
packages/core/src/entity/Collection.ts
packages/core/src/entity/EntityFactory.ts
packages/core/src/entity/EntityHelper.ts
packages/core/src/entity/Reference.ts
packages/core/src/entity/WrappedEntity.ts
packages/core/src/entity/wrap.ts
packages/core/src/serialization/EntityTransformer.ts
packages/core/src/typings.ts
packages/core/src/utils/DataloaderUtils.ts
tests/EntityHelper.mongo.test.ts
tests/EntityManager.mongo.test.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite2.test.ts
tests/features/dataloader.test.ts
tests/features/filters/filters.postgres.test.ts
tests/types.test.ts

`Reference.load()` (and other methods that are using `WrappedEntity.init()` under the hood) now return `null` when the target entity is not found instead of resolving to unloaded entity. This can happen either because it was removed in the meantime, or it is not compatible with the currently enabled filters. A new method called `loadOrFail()` is added to the `Reference` class which always returns a value or throws otherwise, just like `em.findOneOrFail`.
This PR also adds more options to both `Reference.load` and `Collection.load`, aligning them with the underlying methods used (`em.findOne` and `em.populate` respectively).
BREAKING CHANGE
Closes #4975

feat(core): allow configuring filters in `Reference.load()` and `Collection.load()`

---

docs/docs/raw-queries.md
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/platforms/Platform.ts
packages/core/src/utils/RawQueryFragment.ts
packages/knex/src/AbstractSqlPlatform.ts
packages/knex/src/query/QueryBuilderHelper.ts
packages/knex/src/schema/SchemaHelper.ts
packages/postgresql/src/PostgreSqlSchemaHelper.ts
packages/reflection/src/TsMorphMetadataProvider.ts
tests/EntityManager.postgre.test.ts
tests/QueryBuilder.test.ts
tests/entities-sql/Author2.ts
tests/entities-sql/Book2.ts
tests/features/custom-types/GH725.test.ts
tests/features/embeddables/GH3887.mysql.test.ts
tests/features/embeddables/GH3887.sqlite.test.ts
tests/features/schema-generator/GH4782.test.ts
tests/features/schema-generator/__snapshots__/diffing-default-values.test.ts.snap
tests/features/schema-generator/diffing-default-values.test.ts
tests/features/upsert/GH4020.test.ts
tests/features/upsert/GH4242-2.test.ts
tests/features/upsert/GH4242.test.ts
tests/features/upsert/GH4786.test.ts
tests/issues/GH3965.test.ts
tests/issues/GH4062.test.ts
tests/issues/GH4377.test.ts
tests/issues/GH4988.test.ts

When you want to define a default value for a datetime column, you can use the `sql.now()` function. It resolves to `current_timestamp` SQL function, and accepts a `length` parameter.
```ts
@Property({ default: sql.now() })
createdAt: Date & Opt;
```
To convert a key to lowercase or uppercase, you can use the `sql.lower()` and `sql.upper()` functions
```ts
const books = await orm.em.find(Book, {
[sql.upper('title')]: 'TITLE',
});
```

feat(core): add `sql.now()`, `sql.lower()` and `sql.upper()` functions

---

docs/docs/serializing.md
packages/core/src/index.ts
packages/core/src/serialization/EntitySerializer.ts
packages/core/src/typings.ts
tests/entities/Book.ts
tests/features/serialization/explicit-serialization.test.ts
tests/features/serialization/force-object.test.ts

For strict typings to respect the global config option, you need to define it on your entity class via `Config` symbol:
```ts
import { Config, Entity, ManyToOne, PrimaryKey, Ref, wrap } from '@mikro-orm/core';
@Entity()
class Book {
[Config]?: DefineConfig<{ forceObject: true }>;
@PrimaryKey()
id!: number;
@ManyToOne(() => User, { ref: true })
author!: Ref<User>;
}
const book = await em.findOneOrFail(Book, 1);
const dto = wrap(book).toObject();
const identityId = dto.author.id; // without the Config symbol, `dto.identity` would resolve to number
```

feat(core): allow defining `serialization.forceObject: true` on type level

---

packages/entity-generator/src/EntityGenerator.ts
packages/migrations-mongodb/src/MigrationGenerator.ts
packages/migrations/src/MigrationGenerator.ts
packages/seeder/src/SeedManager.ts
scripts/copy.mjs

In all places of the code, fs-extra's writeFile is used. This package however is actually a re-export of the callback version of node:fs' writeFile.
Meanwhile, all packages seem to assume this is the version from node:fs/promises.
This fix in turn fixes tests that can sometimes be flaky, due to assuming file operations are done, when that isn't necessarily true.
Also reordered imports in the affected files alphabetically.
---
I noticed this while running tests locally. Random tests sometimes fail, and all they had in common was the fact that they were checking for a file's existence. I thought it's maybe an fs-extra specific issue with Windows, but then discovered it's not re-exporting the promise, hence this PR.

refactor: use `flush` option with `writeFile`

---

docs/docs/configuration.md
docs/docs/filters.md
packages/core/src/EntityManager.ts
packages/core/src/entity/EntityLoader.ts
packages/core/src/entity/Reference.ts
packages/core/src/typings.ts
packages/core/src/utils/Configuration.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
tests/EntityManager.mysql.test.ts
tests/EntityManager.postgre.test.ts
tests/bootstrap.ts
tests/features/__snapshots__/dataloader.test.ts.snap
tests/features/dataloader.test.ts
tests/features/filters/filters.postgres.test.ts
tests/features/joined-strategy.postgre.test.ts
tests/features/virtual-entities/virtual-entities.postgres.test.ts

Filters are applied to the relations too, as part of `JOIN ON` condition. If a filter exists on a M:1 or 1:1 relation target, such an entity will be automatically joined, and when the foreign key is defined as `NOT NULL`, it will result in an `INNER JOIN` rather than `LEFT JOIN`. This is especially important for implementing soft deletes via filters, as the foreign key might point to a soft-deleted entity. When this happens, the automatic `INNER JOIN` will result in such a record not being returned at all.
You can disable this behavior via `autoJoinRefsForFilters` ORM option.
Related: #4975

feat(core): auto-join M:1 and 1:1 relations with filters

---

docs/docs/entity-manager.md
packages/better-sqlite/src/BetterSqliteMikroORM.ts
packages/core/src/MikroORM.ts
packages/core/src/drivers/DatabaseDriver.ts
packages/core/src/utils/Configuration.ts
packages/core/src/utils/ConfigurationLoader.ts
packages/knex/src/AbstractSqlDriver.ts
packages/mariadb/src/MariaDbMikroORM.ts
packages/mongodb/src/MongoDriver.ts
packages/mongodb/src/MongoMikroORM.ts
packages/mysql/src/MySqlMikroORM.ts
packages/postgresql/src/PostgreSqlMikroORM.ts
packages/sqlite/src/SqliteMikroORM.ts
tests/features/custom-entity-manager.test.ts

To extend the EntityManager with your own custom methods, you can use the `entityManager` ORM option:
```ts
import { MikroORM, EntityManager } from '@mikro-orm/sqlite';
class MyEntityManager extends EntityManager {
myCustomMethod(base: number): number {
return base * Math.random();
}
}
const orm = await MikroORM.init({
entities: [...],
dbName: ':memory:',
entityManager: MyEntityManager,
});
console.log(orm.em instanceof MyEntityManager); // true
const res = orm.em.myCustomMethod(123);
```

feat(core): allow extending `EntityManager`

---

packages/postgresql/package.json
packages/postgresql/src/PostgreSqlConnection.ts
tests/features/schema-generator/timestamp.postgres.test.ts
yarn.lock

Parsing a timestamp column in postgresql with a date less than year 1000 will create an invalid Date when using the `forceUtcTimezone` set to `true`.
Created test for reproduction, run without the fix to `PostgresSqlConnection.ts`.
Use the date parsing function from `postgres-date` that is used by default in `pg` for parsing dates but add the `Z` to force the utc timezone. `new Date('0022-01-01 09:17:58.000Z')` when parsing the timestamp column str creates an invalid date in js.

fix(postgres): parse timestamp dates less than year 1000

---

README.md

I've prepared a simple example which covers both REST and GraphQL authentication with Accounts.js. I would be glad if you could mention it in the blog post :)

docs: add Accounts.js example

---

docs/versioned_docs/version-5.9/installation.md

A couple of notes here:
* I do not know how this is important since it is for v5.9
* Accordingly to [stackexchange](https://english.stackexchange.com/questions/385508/) it should be without a `-`. But feel free to change it if required

docs: correct a typo in documentation

---

docs/docs/defining-entities.md
docs/versioned_docs/version-4.5/defining-entities.md
docs/versioned_docs/version-5.9/defining-entities.md
docs/versioned_docs/version-6.0/defining-entities.md

Since https://github.com/mikro-orm/mikro-orm/pull/4408 the docs have been in a weird inconsistent state regarding the uuid functions, recommending one in the section header but then using another one in the example code.
`uuid_generate_v4()` is still used in a few tests but I am not updating that here.

docs: update remaining `uuid_generate_v4()` calls to `gen_random_uuid()`

---

tests/EntityManager.postgre.test.ts

Fix by explicitly checking on every tick if the entity with the previous ID is loaded into the entity manager.
Thus, while the promises are technically all started at the same time, they are resolved in a forced order, making the actual output of the query log consistent.
---
A potential solution to the situation described [here](https://github.com/mikro-orm/mikro-orm/pull/5113#issuecomment-1890953639).

test: try to fix flaky `Promise.all()` test

---

tests/EntityManager.postgre.test.ts
tests/EntityManager.sqlite.test.ts
tests/EntityManager.sqlite2.test.ts
tests/entities-js/Author3.js
tests/entities-schema/BaseEntity5.ts
tests/features/cache-adapters/FileCacheAdapter.test.ts
tests/features/cache-adapters/MemoryCacheAdapter.test.ts
tests/features/embeddables/GH2391-2.test.ts
tests/features/result-cache/result-cache.mongo.test.ts
tests/features/result-cache/result-cache.postgre.test.ts

Also tweaked the test entities-js/Author3.js and entities-schema/BaseEntity5.ts to derive the update out of the create or (in the case of the entity schema) vice-versa. This refactor, combined with fake timers in the affected tests, means that no tolerance is required for those columns - they start off as equal, always.

test(timers): replaced all timeouts with fake timers, or remove them as appropriate

---

CONTRIBUTING.md
package.json

Also fixed some typos in CONTRIBUTING.md.
----
Technically, the command
```
docker compose down -v
```
is sufficient to clean up docker, but I thought I future proof the command in CONTRIBUTING.md, just in case some custom image is added, dropped, or support for a DB (and thus its container) is dropped, etc. etc.

docs: improve contributing guide and tests setup

---

docs/docs/usage-with-jest.md
docs/sidebars.js
docs/versioned_docs/version-6.0/usage-with-jest.md
docs/versioned_sidebars/version-6.0-sidebars.json

Closes #4994.
---
I know what I said before about `glob` on init, but... I tried to locate the exact source, and couldn't find it now... I'm guessing maybe they changed in some recent versions, and maybe I was looking at an outdated one at the time. Anyhow, I haven't included it in the docs due to that.
The code shown for a workaround is a more polished version of what I showed in #4994, and after some research, I found a workaround for Mongo that I also included.
---
EDIT: Workaround provided is probably a bit too hacky... I'm researching something more elegant and less memory leak-y.
---
EDIT2: OK, I think I have a better workarounds for each driver now, targeting specifically the things that absolutely need a real `process.nextTick()` and nothing else.

docs(fake-timers): added a page for using MikroORM with Jest, with fake timers info

---

docs/docs/custom-types.md
docs/versioned_docs/version-6.0/custom-types.md
packages/core/src/types/ArrayType.ts
packages/postgresql/src/PostgreSqlConnection.ts
tests/features/custom-types/GH5188.test.ts

`ArrayType` can be now also used to map the array items to more complex types like objects. Consider the following example of mapping a `date[]` column to array of objects with `date` string property:
```ts
import { ArrayType } from '@mikro-orm/core';
export class CalendarDateArrayType extends ArrayType<CalendarDate> {
constructor() {
super(
date => ({ date }), // to JS
d => d.date, // to DB
);
}
getColumnType(): string {
return 'date[]';
}
}
```
This PR also disables the automatic conversion of arrays of datetime values (and similar, e.g. date or interval) to arrays of Date objects. This was disabled only for the scalar types, but it had to be disabled explicitly for their array variants to get consistent behavior.
Closes #5188

feat(core): allow mapping array columns to arrays of objects via `ArrayType`

---

docs/docs/collections.md
packages/core/src/decorators/ManyToMany.ts
packages/core/src/decorators/OneToMany.ts
packages/core/src/entity/EntityLoader.ts
packages/core/src/typings.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/QueryBuilderHelper.ts
tests/features/collection/partial-collections.test.ts

Collections can also represent only a subset of the target entities:
```ts
@Entity()
class Author {
@OneToMany(() => Book, b => b.author)
books = new Collection<Book>(this);
@OneToMany(() => Book, b => b.author, { where: { favorite: true } })
favoriteBooks = new Collection<Book>(this);
}
```
This works also for M:N relations. Note that if you want to declare more relations mapping to the same pivot table, you need to explicitly specify its name (or use the same pivot entity):
```ts
@Entity()
class Book {
@ManyToMany(() => BookTag)
tags = new Collection<BookTag>(this);
@ManyToMany({
entity: () => BookTag, 
pivotTable: 'book_tags',
where: { popular: true },
})
popularTags = new Collection<BookTag>(this);
}
```
Closes #4963

feat(core): allow declarative partial loading of collection items

---

packages/entity-generator/src/EntitySchemaSourceFile.ts
packages/entity-generator/src/SourceFile.ts
tests/features/entity-generator/MetadataHooks.mysql.test.ts
tests/features/entity-generator/__snapshots__/EntityGenerator.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/EntityGenerator.postgres.test.ts.snap
tests/features/entity-generator/__snapshots__/EntityGenerator.test.ts.snap
tests/features/entity-generator/__snapshots__/ManyToManyRelations.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/MetadataHooks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/NullableFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/OverlapFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/ScalarPropsForFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/TypesForScalarDecorators.mysql.test.ts.snap

As mentioned we should do in #5113 , but left it for a separate PR due to the increase in scope.
Pretty much all entity generator snapshots are affected, since most schemas have some form of an optional property involved.
I also adjusted the meta data post processing test to have one property that is both hidden and optional, to ensure the combination of the two is outputted fine too.

refactor(entity-generator): emit `Opt` and `Hidden` prop types instead of the symbols

---

packages/entity-generator/src/EntitySchemaSourceFile.ts
packages/entity-generator/src/SourceFile.ts
tests/features/entity-generator/MetadataHooks.mysql.test.ts
tests/features/entity-generator/__snapshots__/MetadataHooks.mysql.test.ts.snap

If a function is provided, its toString() representation (its source) will be put in the generated file.
Support spots for functions include
- onCreate
- onUpdate
- serializer
- expression in virtual entities
Also added support for the `@Formula` decorator (used whenever a "formula" option is included).
Simplified meta data edits to not use quotes in places where only string types are expected, such as comment, expression (as string) and STI values.

feat(entity-generator): support functions in extension hooks

---

.github/workflows/tests.yml
docs/docusaurus.config.js
docs/src/pages/versions.js

Only build the earliest and latest versions, plus the current docs, and any version mentioned in the footer (currently 5.9).
This shaves off around 2 minutes from any build,
while still ensuring that no breaking changes are accidentally introduced.
Full deploys of the docs (the docs workflow) still builds all versions, as would any local build without the newly introduced "MIKRO_ORM_DOCS_TESTING" environment variable.
---
I wasn't sure whether to include this in my last PR, so here it is separately. IMO, the trade off of not building all versions is worth it.

test(docs): made the tests workflow build a more restricted set of versions

---

packages/entity-generator/src/SourceFile.ts
packages/knex/src/schema/DatabaseTable.ts
tests/features/entity-generator/MetadataHooks.mysql.test.ts
tests/features/entity-generator/__snapshots__/MetadataHooks.mysql.test.ts.snap

As a nice side effect, relations in metadata hooks now feature information about the types of the columns involved in FKs.

feat(entity-generator): support `mapToPk` option

---

docs/docusaurus.config.js
docs/package.json
docs/yarn.lock

Also, now that no broken links are reported, modified the config to throw if any are introduced.
Note that the version of @mdx-js/react is fixed to 3.0.0, as 3.0.1 seems to break the anchor collection in docusaurus' mdx-loader. Not sure if docusaurus is interacting with it erroniously or if @mdx-js/react unintentionally broke what used to work, or if maybe one of @mdx-js/react's dependencies broke something, so I haven't reported this to either repo yet.
----
Not sure why renovate still didn't pick up the new plugin version. My best guess is because it's not part of the root's workspace. If successfully enabled, it might try to update @mdx-js/react, and right now, it will probably fail due to the new version introducing broken anchors.

docs: updated dependencies

---

packages/entity-generator/src/SourceFile.ts
packages/knex/src/schema/DatabaseTable.ts
packages/mariadb/src/MariaDbSchemaHelper.ts
packages/mysql/src/MySqlSchemaHelper.ts
tests/features/entity-generator/EntityGenerator.postgres.test.ts
tests/features/entity-generator/__snapshots__/CustomBase.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/EntityGenerator.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/EntityGenerator.postgres.test.ts.snap
tests/features/entity-generator/__snapshots__/EntityGenerator.test.ts.snap
tests/features/entity-generator/__snapshots__/GeneratedColumns.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/GeneratedColumns.postgresql.test.ts.snap
tests/features/entity-generator/__snapshots__/ManyToManyRelations.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/MetadataHooks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/NullableFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/OverlapFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/ScalarPropsForFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/TypesForScalarDecorators.mysql.test.ts.snap

The "default" option is no longer emitted into the decorator, in favor of it being specified in the property's declaration at the entity class. The "defaultRaw" option is still used in cases where the SQL expression does not unambiguously map to the "default" option's value.
The MySQL schema helper translates TINYINT(1) with a value of 0 to "false". This ensures behavior consistent with other drivers. And if this value accidentally finds its way back in a query, it is also OK, as MySQL treats this literal as "0".
The "optional" option is now added early, in the DatabaseTable stage. This has also unlocked some ManyToMany relations that were previously not detected.
Closes #5260

fix(entity-generator): optional and hidden properties get type option + string defaults

---

packages/mariadb/src/MariaDbDriver.ts
packages/mysql/src/MySqlDriver.ts
tests/issues/GH5278.test.ts
tests/issues/GH5279.test.ts

fix(mysql): apply current context when fetching `auto_increment_increment`

---

packages/entity-generator/src/EntitySchemaSourceFile.ts
packages/entity-generator/src/SourceFile.ts
tests/features/entity-generator/__snapshots__/AmbiguousFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/CustomBase.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/FkIndexSelection.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/FkSharedWithColumn.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/GeneratedColumns.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/GeneratedColumns.postgresql.test.ts.snap
tests/features/entity-generator/__snapshots__/ManyToManyRelations.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/MetadataHooks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/NonCompositeAmbiguousFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/NullableFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/OverlapFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/multple-schemas.postgres.test.ts.snap

Also fixed extra imports when the mapToPk option is set.
Also removed the usage of getEntityName() in SourceFile, thus ensuring that adjustments made by the de-duplication are honored.

fix(entity-generator): emit missing imports in `EntitySchema` generated files

---

packages/migrations/src/Migration.ts

When generator create migration addSql in up or down doesnt need to be promisse.

fix(migrator): allow `up` and `down` methods to be synchronous

---

packages/entity-generator/src/CoreImportsHelper.ts
packages/entity-generator/src/SourceFile.ts
tests/features/entity-generator/__snapshots__/AmbiguousFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/CustomBase.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/EntityGenerator.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/EntityGenerator.postgres.test.ts.snap
tests/features/entity-generator/__snapshots__/EntityGenerator.test.ts.snap
tests/features/entity-generator/__snapshots__/FkIndexSelection.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/FkSharedWithColumn.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/GeneratedColumns.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/GeneratedColumns.postgresql.test.ts.snap
tests/features/entity-generator/__snapshots__/ManyToManyRelations.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/MetadataHooks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/NonCompositeAmbiguousFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/NullableFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/OverlapFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/ScalarPropsForFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/TypesForScalarDecorators.mysql.test.ts.snap

Helps transpilers and bundlers to more efficiently strip out types.

fix(entity-generator): output type import statements for type only core imports

---

packages/core/src/entity/EntityAssigner.ts
tests/features/entity-assigner/EntityAssigner.mongo.test.ts

add option, ignore entities but allow primary keys
Closes #5327

feat(core): add `onlyOwnProperties` option to `assign` helper

---

packages/core/src/utils/Utils.ts

When using mikroorm in typescript ESM project and using cli, `.ts` config and `entitiesTs` are not taken into account. This is because ts-node is not detected for node > 16.20 when using `ts-node/esm` loader as node option https://github.com/TypeStrong/ts-node?tab=readme-ov-file#node-flags-and-other-tools (directly or using `mikro-orm-esm` binary).
If we have the orm script in `package.json` and defined `configPaths`:
```package.json
"scripts": {
"orm-node-loader": "cross-env \"NODE_OPTIONS='--loader ts-node/esm --no-warnings'\" mikro-orm",
"orm-esm-binary": "mikro-orm-esm"
},
"mikro-orm": {
"configPaths": [
"./src/db/orm.config.ts",
"./src/db/orm.config.js"
]
},
```
And run `npm run orm-esm-binary debug` or `npm run orm-node-loader debug` in development, you will see the message
```
- …
```

fix(core): detect `ts-node` when using esm loader

---

packages/core/src/utils/Cursor.ts
tests/features/cursor-based-pagination/__snapshots__/bidirectional-cursor.test.ts.snap
tests/features/cursor-based-pagination/__snapshots__/complex-cursor.test.ts.snap
tests/features/cursor-based-pagination/bidirectional-cursor.test.ts
tests/features/cursor-based-pagination/complex-cursor.test.ts
tests/features/cursor-based-pagination/simple-cursor.test.ts

When using cursor pagination, the `hasPrevPage` and `hasNextPage` has inconsistency behavior that display the wrong value when query to the last page of last/before (which is the first page of the first/after).
```ts
const { first, last, before, after, orderBy, overfetch } = options;
const limit = first || last;
const isLast = !first && !!last;
const hasMorePages = !!overfetch && limit != null && items.length > limit;
// this.hasPrevPage = before || after ? true : (isLast && hasMorePages);
// this.hasNextPage = !(isLast && !before && !after) && hasMorePages;
this.hasPrevPage = isLast ? hasMorePages : !!after; 
this.hasNextPage = isLast ? !!before : hasMorePages;
```
The old `hasPrevPage` is true if either `before` or `after` exists, which is wrong because having `before` doesn't mean it …

fix(core): fix value of `hasPrev[/Next]Page` when paginating backwards

---

docs/docs/identity-map.md
docs/versioned_docs/version-6.1/identity-map.md

Related to #5367 .
The sentence
> they don't really explain anything to someone not knowing what an Identity Map is.
kind of triggered me on this one, in that it is actually a fair point, despite not being the core of the issue. Not sure if my definition here makes sense, but I think _some_ definition of the term identity map being present is important.

docs(core): added definition of an identity map

---

docs/docs/query-conditions.md
packages/core/src/enums.ts
packages/core/src/typings.ts
packages/core/src/utils/QueryHelper.ts
packages/core/src/utils/Utils.ts
tests/issues/GH4678.test.ts

This PR will introduce few missing PostgreSQL [JSON operators](https://www.postgresql.org/docs/10/functions-json.html) In response to https://github.com/mikro-orm/mikro-orm/issues/4678
`?` - Does the string exist as a top-level key within the JSON value?
`?|` - Do any of array strings exist as top-level keys?
`?&`- Do all of array strings exist as top-level keys?
```ts
// ? operator
await orm.em.findAll(User, {
where: {
books: { parameters: { $hasKey: 'seasons' } },
},
});
```
```ts
// ?& operator
await orm.em.findAll(User, {
where: { books: { parameters: { $hasKeys: ['seasons', 'pages'] } } },
});
```
```ts
// ?| operator
await orm.em.findAll(User, {
where: { books: { parameters: { $hasSomeKeys: ['seasons', 'pages'] } } },
});
```
Related: #4678

feat(postgres): add `?`, `?|` and `?&` json operators

---

docs/docs/query-conditions.md

Pipes as values in Markdown tables need to be written as an HTML entity, e.g. `&|` should be written as `&&#x7c;`.

docs: fix table formatting in `query-conditions.md`

---

packages/knex/src/schema/SchemaHelper.ts
packages/postgresql/src/PostgreSqlSchemaHelper.ts

This PR fixes an issue introduced in v6.1.12 ([2dff96b](https://github.com/mikro-orm/mikro-orm/commit/2dff96bc48c6a84bc1fc213e8044b0ac722d4792)).
The query used to discover foreign keys was returning erroneous duplicate rows. The fixed query removes the duplicates and ensures FK columns are returned in the correct order.
This PR also reverses changes to the SchemaHelper, which are no longer needed.

fix(postgres): removed erroneous duplicates in FK discovery query

---

docs/docs/custom-types.md
packages/core/src/EntityManager.ts
packages/core/src/entity/BaseEntity.ts
packages/core/src/entity/EntityAssigner.ts
packages/core/src/entity/EntityRepository.ts
packages/core/src/entity/WrappedEntity.ts
packages/core/src/types/Type.ts
packages/core/src/types/index.ts
packages/core/src/typings.ts
tests/issues/GH910.test.ts
tests/types.test.ts

When your custom type maps a value to an object, it might break the internal types like in `em.create()`, as there is no easy way to detect whether some object type is an entity or something else. In those cases, it can be handy to use `IType` to provide more information about your type on the type-level. It has three arguments, the first represents the runtime type, the second one is the raw value type, and the last optional argument allows overriding the serialized type (which defaults to the raw value type).
Consider the following custom type:
```ts
class MyClass {
constructor(private value: string) {}
}
class MyType extends Type<MyClass, string> {
convertToDatabaseValue(value: MyClass): string {
return value.value;
}
convertToJSValue(value: string): MyClass {
return new …
```

feat(core): allow better type-safety for custom types via `IType`

---

packages/reflection/src/TsMorphMetadataProvider.ts

This makes the project init consistent with source files init, while also eliminating the otherwise unreachable path from project re-init that initProject() defended from.
This removal in turn increases coverage of TsMorphMetadataProvider.ts to 100%.

refactor(reflection): removed the defense inside initProject() in favor of check outside

---

packages/core/src/decorators/ManyToOne.ts
packages/core/src/decorators/OneToOne.ts
packages/core/src/enums.ts
packages/core/src/typings.ts
packages/knex/src/schema/DatabaseTable.ts
packages/knex/src/schema/SchemaComparator.ts
packages/knex/src/schema/SchemaHelper.ts
packages/knex/src/schema/SqlSchemaGenerator.ts
packages/knex/src/typings.ts
packages/postgresql/src/PostgreSqlSchemaHelper.ts
tests/features/deferrable-constraints/deferrable-constraints.postgres.test.ts
tests/features/schema-generator/__snapshots__/fk-diffing.postgres.test.ts.snap
tests/features/schema-generator/fk-diffing.postgres.test.ts

This PR adds the option to specify constraints as deferrable for relations.
On OneToOne and ManyToOne relations you can now specify a `deferMode` property, which can be either `not deferrable` (default), `immediate` or `deferred`. Those are also covered by a new `DeferMode` enum.
Closes #5306

feat(postgres): allow defining deferred FK constraints

---

docs/docs/guide/01-first-entity.md
docs/versioned_docs/version-6.0/guide/01-first-entity.md
docs/versioned_docs/version-6.1/guide/01-first-entity.md

Assuming this should read `userRef` instead of `user` based on previous const name.

docs: fix typo in getting started guide

---

packages/core/src/EntityManager.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/entity/EntityLoader.ts
packages/core/src/entity/EntityRepository.ts
packages/core/src/entity/WrappedEntity.ts
packages/core/src/enums.ts
packages/core/src/serialization/EntitySerializer.ts
packages/core/src/typings.ts
packages/knex/src/AbstractSqlDriver.ts
packages/mongodb/src/MongoDriver.ts

Currently, this includes just `"*"` and `"$infer"`.
Places where `"*"` is used as an actual SQL query expression remain using the literal string `"*"`.

refactor(core): added a PopulatePath enum, to contain the special prop names in populate

---

packages/core/src/naming-strategy/AbstractNamingStrategy.ts
packages/entity-generator/src/EntityGenerator.ts
packages/entity-generator/src/EntitySchemaSourceFile.ts
packages/entity-generator/src/SourceFile.ts
packages/knex/src/dialects/mysql/MySqlSchemaHelper.ts
packages/knex/src/schema/DatabaseTable.ts
packages/knex/src/schema/SchemaComparator.ts
packages/mariadb/src/MariaDbSchemaHelper.ts
packages/postgresql/src/PostgreSqlSchemaHelper.ts
tests/features/entity-generator/OddTableNames.mysql.test.ts
tests/features/entity-generator/OddTableNames.postgres.test.ts
tests/features/entity-generator/__snapshots__/GeneratedColumns.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/GeneratedColumns.postgresql.test.ts.snap
tests/features/entity-generator/__snapshots__/OddTableNames.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/OddTableNames.postgres.test.ts.snap

fix(entity-generator): allow arbitrary class and prop names as identifiers
AbstractNamingStrategy is updated to handle class conflicts, and inherently,
any naming strategy that inherits from it.
The "word boundary" character in entity and property names is now correctly replaced,
even in cases where multiple sequential separators are present.
Any table that starts with a character that is invalid as a JS start character (not just digits)
gets prefixed with "E".
Characters that are not valid in any position as a class identifier (or the character "$")
get turned into code points, prefixed with $, making them valid (though inconvenient to type)
identifiers and file names.
In AbstractNamingStrategy.columnNameToProperty(),
prop names that would be in conflict with PopulatePath values get …

fix(entity-generator): allow arbitrary class and prop names as identifiers

---

docs/docs/guide/01-first-entity.md
docs/versioned_docs/version-6.0/guide/01-first-entity.md
docs/versioned_docs/version-6.1/guide/01-first-entity.md
docs/versioned_docs/version-6.2/guide/01-first-entity.md

Fix the entity name of `Author` was a typo as `Book`.

docs: fix typo in 01-first-entity.md

---

.github/ISSUE_TEMPLATE/bug_report.yml

Allows selection of `@mikro-orm/mssql` package in the bug template.

docs: add @mikro-orm/mssql to bug report template

---

packages/core/src/metadata/MetadataDiscovery.ts
tests/MikroORM.test.ts
tests/complex-entities/abstract-class.entity.ts

After upgrading from `v5` to `v6`, initializing ORM doesn't work, throwing following stack trace:
```bash
TypeError: Cannot read properties of undefined (reading 'length')
at MetadataDiscovery.defineBaseEntityProperties (.../node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:733:75)
at .../node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:90:39
at Array.forEach (<anonymous>)
at MetadataDiscovery.processDiscoveredEntities (.../node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:90:18)
at MetadataDiscovery.discover (.../node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:47:14)
at async MikroORM.discoverEntities (.../node_modules/@mikro-orm/core/MikroORM.js:172:25)
at async Function.init (.../node_modules/@mikro-orm/core/MikroORM.js:44:9)
at async …
```

fix(core): fix folder-based discovery for multiple entities in single file

---

packages/migrations/src/Migrator.ts
tests/features/migrations/Migrator.test.ts
tests/features/migrations/__snapshots__/Migrator.test.ts.snap

When using custom migration fileName function which forces using name (throws) as in the example in documentaion https://mikro-orm.io/docs/migrations#using-custom-migration-names and having snapshots enabled, causes the update of snapshot. Second retry with using name is not generating migration, because the snapshot has already been updated and no changes are found.
```typescript
migrations: {
fileName: (timestamp: string, name?: string) => {
// force user to provide the name, otherwise you would end up with `Migration20230421212713_undefined`
if (!name) {
throw new Error('Specify migration name via `mikro-orm migration:create --name=...`');
}
return `Migration${timestamp}_${name}`;
},
snapshot: true,
},
```
Delaying update of snapshot after migration file is actually generated. Thus, …

fix(migrator): store snapshot only after migration is generated

---

.yarnrc.yml
packages/knex/src/query/QueryBuilder.ts
tests/QueryBuilder.test.ts

fix(query-builder): don't remove joins used by other joins during pagination

---

packages/core/src/decorators/Embedded.ts
packages/core/src/hydration/ObjectHydrator.ts
packages/core/src/metadata/MetadataDiscovery.ts
tests/features/embeddables/GH5578.postgres.test.ts
tests/features/embeddables/__snapshots__/embeddable-custom-types.postgres.test.ts.snap
tests/features/embeddables/embeddable-custom-types.postgres.test.ts

fix(core): allow hydration of non persistent embedded properties

---

packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/metadata/MetadataStorage.ts
packages/core/src/utils/Utils.ts
tests/Utils.test.ts

Related discussion here: https://github.com/mikro-orm/mikro-orm/discussions/5496
In [this commit](https://github.com/mikro-orm/mikro-orm/commit/271ff7dfe95ded8f2821b7a97a10ddfe409b1513) you changed the condition because of coverage. This is incorrect because it guards against going out of stack array bounds - I have added the test for this case. Also, I removed no longer needed condition.
Before the changes, the path was detected for every used decorator on the class and overwritten. This is not needed because the path used as a key should be stable and should not change for a given class. So I introduced the new symbol `MetadataStorage.PATH_SYMBOL`, which will hold the path and check if it exists for a given class using `Object.hasOwn` (this also works for class inheritance so the path …

fix(core): detect path from decorator for each class only once

---

packages/mssql/src/MsSqlSchemaHelper.ts

This fixes invalid sql produced by `MsSqlSchemaHelper` for tables with quote char in the name.

fix(mssql): account for quotes in table names

---

packages/mssql/src/MsSqlSchemaHelper.ts

This is linked with the issue closes #5633 
I have overriden the method `getNamespaces` inside the MSSqlSchemaHelper so that we can dynamically get the namespaces present in the MSSQL connection that was configured with the Mikroorm instance of the application.
I have tested this query with migration files that migrate the database up and I was able to successfully do that.
To be precise was able to run these commands successfully and the changes were reflected in the DB:
```sh
mikro-orm migration:create --initial
mikro-orm migration:create && mikro-orm migration:up
mikro-orm migration:down #If required to reduce the version of migration is also successful
```
Please let me know whether this looks good and I am up for any changes or refinements. Thank you

fix(mssql): fix creating migrations due to a missing helper method

---

packages/knex/src/schema/DatabaseTable.ts
packages/knex/src/schema/SchemaComparator.ts
packages/knex/src/schema/SqlSchemaGenerator.ts
packages/knex/src/typings.ts
packages/postgresql/src/PostgreSqlSchemaHelper.ts
tests/features/deferrable-constraints/deferrable-constraints.postgres.test.ts
tests/features/schema-generator/__snapshots__/fk-diffing.postgres.test.ts.snap
tests/features/schema-generator/fk-diffing.postgres.test.ts

In my initial implementation on `deferMode` for 1:m and 1:1 I overlooked the unique constraint which is created for 1:1 relations. This PR corrects this and also applies the selected `deferMode` to the unique constraint.
This PR also lays the framework for potentially using `deferMode` on custom unique constraints, though that is not critical since those could already be created through the `expression` prop.
If this PR looks fine, I'd appreciate a quick bugfix release after you had time to merge it, since this is currently a showstopper in one of my projects and I can't find a workaround :)

fix(postgres): respect `deferMode` option in 1:1 relations

---

packages/knex/package.json
yarn.lock

This help avoid bundlers like Vite trying to pre-package them, and instead leaves them as externals, without the need of an explicit config change.
Note that Knex itself declares all of the drivers it supports as optional peer dependencies. This package just defines its extensions as optional peer dependencies in addition to that.

fix(knex): explicitly declare all the extended drivers as optional peer dependencies

---

packages/core/src/utils/ConfigurationLoader.ts

Update configuration to allow `mikro-orm-esm` to work with newer versions of tsconfig.
#5427

fix(cli): use `module: 'nodenext'` when registering ts-node

---

docs/docs/decorators.md
packages/core/src/decorators/Indexed.ts
packages/core/src/decorators/ManyToOne.ts
packages/core/src/decorators/OneToOne.ts
packages/core/src/typings.ts
packages/core/src/unit-of-work/UnitOfWork.ts
packages/knex/src/schema/DatabaseTable.ts
packages/postgresql/src/PostgreSqlSchemaHelper.ts
tests/features/deferrable-constraints/__snapshots__/compound-deferrable-constraint.test.ts.snap
tests/features/deferrable-constraints/compound-deferrable-constraint.test.ts

Allows specifying `deferMode` on a unique constraint to get around issues with batch updates mainly.

feat(postgres): allow specifying deferred mode on unique constraints

---

docs/docs/configuration.md
packages/core/src/MikroORM.ts
packages/core/src/platforms/Platform.ts
packages/mongodb/src/MongoPlatform.ts
tests/features/entity-generator/EntityGenerator.test.ts

The extensions are now again checked dynamically if not explicitly registered, so it should be enough to have the given package (e.g. `@mikro-orm/seeder`) installed as in v5.

feat(core): check for ORM extensions dynamically

---

packages/core/src/typings.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/SqlEntityManager.ts
packages/knex/src/SqlEntityRepository.ts
packages/knex/src/query/QueryBuilder.ts
packages/mariadb/src/MariaDbDriver.ts
packages/mariadb/src/MariaDbQueryBuilder.ts
packages/mssql/src/MsSqlDriver.ts
packages/mssql/src/MsSqlQueryBuilder.ts
tests/QueryBuilder.test.ts
tests/features/entity-assigner/EntityAssigner.mysql.test.ts
tests/features/result-cache/GH3294.test.ts
tests/issues/GH222.test.ts
tests/issues/GH3812.test.ts
tests/issues/GH4741.test.ts
tests/types.test.ts

```ts
const authors = await em.createQueryBuilder(Author, 'a')
.leftJoinAndSelect('a.books', 'b')
.leftJoinAndSelect('b.tags', 't')
.leftJoinAndSelect('b.pulisher', 'p');
// authors is of type `Loaded<Author, 'books' | 'books.tags' | 'books.publisher'>[]`
```

feat(query-builder): infer `Loaded` hint based on `joinAndSelect` calls

---

docs/docs/naming-strategy.md
packages/core/src/naming-strategy/AbstractNamingStrategy.ts
packages/core/src/naming-strategy/NamingStrategy.ts
packages/entity-generator/src/EntitySchemaSourceFile.ts
packages/entity-generator/src/SourceFile.ts
packages/knex/src/schema/DatabaseTable.ts
tests/features/entity-generator/OddTableNames.mysql.test.ts
tests/features/entity-generator/__snapshots__/OddTableNames.mysql.test.ts.snap

Enum options that are invalid JS identifiers get the property treatment (independent of naming strategy), and the enum name itself gets the entity name treatment.
Two new NamingStrategy methods have been added to optionally adjust the default behaivour. getEnumClassName() and enumValueToEnumProperty().

fix(entity-generator): support complex enum names and values

---

packages/entity-generator/src/EntitySchemaSourceFile.ts
packages/entity-generator/src/SourceFile.ts
tests/features/entity-generator/OddPkTypes.mysql.test.ts
tests/features/entity-generator/__snapshots__/MetadataHooks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/OddPkTypes.mysql.test.ts.snap

Previously, PKs that are not scalar would miss the "primary" option in the output, and enums would use the PrimaryKey decorator instead of the Enum decorator.
Also, FKs that are refs to enum columns would previously create a brand new enum class in each ref. Now, only the "origin" column gets the enum class, and other references use the entity class.

fix(entity-generator): primary keys that are foreign keys or enums are now generated correctly

---

packages/knex/src/dialects/sqlite/BaseSqliteSchemaHelper.ts
packages/knex/src/schema/SchemaHelper.ts
packages/knex/src/schema/SqlSchemaGenerator.ts
tests/features/schema-generator/GH2959.test.ts
tests/features/schema-generator/SchemaGenerator.sqlite.test.ts
tests/features/schema-generator/__snapshots__/SchemaGenerator.sqlite.test.ts.snap
tests/features/schema-generator/__snapshots__/enum-diffing.sqlite.test.ts.snap
tests/features/schema-generator/enum-diffing.sqlite.test.ts

This replaces the knex implementation which is dependent on the current state, which was wrong on its own, since the state might not be matching the metadata we have (e.g. when generating migration against a snapshot).
Closes #5672

fix(sqlite): fix altering tables via malformed temp table

---

packages/mssql/src/MsSqlPlatform.ts
packages/mssql/src/UnicodeStringType.ts
tests/EntityHelper.mysql.test.ts
tests/QueryBuilder.test.ts
tests/entities-mssql/FooBaz2.ts
tests/entities-sql/FooBaz2.ts
tests/features/entity-generator/__snapshots__/EntityGenerator.mssql.test.ts.snap
tests/features/entity-generator/__snapshots__/EntityGenerator.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/EntityGenerator.postgres.test.ts.snap
tests/features/entity-generator/__snapshots__/MetadataHooks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/ScalarPropsForFks.mysql.test.ts.snap
tests/features/migrations/__snapshots__/Migrator.mssql.test.ts.snap
tests/features/migrations/__snapshots__/Migrator.postgres.test.ts.snap
tests/features/migrations/__snapshots__/Migrator.test.ts.snap
tests/features/schema-generator/__snapshots__/SchemaGenerator.mariadb.test.ts.snap
tests/features/schema-generator/__snapshots__/SchemaGenerator.mssql.test.ts.snap
tests/features/schema-generator/__snapshots__/SchemaGenerator.mysql.test.ts.snap
tests/features/schema-generator/__snapshots__/SchemaGenerator.mysql2.test.ts.snap
tests/features/schema-generator/__snapshots__/SchemaGenerator.postgres.test.ts.snap
tests/features/schema-generator/__snapshots__/custom-type-mapping.test.ts.snap
tests/features/virtual-entities/__snapshots__/virtual-entities.postgres.test.ts.snap
tests/mssql-schema.sql
tests/mysql-schema.sql
tests/postgre-schema.sql

Previously, specifying "type: 'varchar'" on a property was treated as aliasing it to "nvarchar" for schema diffing and entity generation purposes, without wrapping it up as UnicodeString at runtime.
Now, it is using MSSQL's native "varchar" for schema diffing / entity generation purposes. Those values are not wrapped up in the UnicodeString wrapper at runtime, as before.
For other drivers, "varchar" still means "varchar if supported" (sqlite still aliases to "text").

fix(mssql): add proper support for MSSQL's native "varchar" type

---

packages/core/src/EntityManager.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/core/src/utils/Utils.ts
packages/core/src/utils/upsert-utils.ts
packages/knex/src/query/QueryBuilder.ts
packages/knex/src/query/QueryBuilderHelper.ts
packages/mongodb/src/MongoDriver.ts
tests/features/upsert/GH5668.test.ts

```ts
await em.upsert(
A,
{ y: 'y1', z: 'z1' },
{
onConflictFields: sql`(z, y) where x is null`,
onConflictAction: 'ignore',
onConflictMergeFields: ['z'],
},
);
```
Closes #5668

feat(core): allow passing `raw()` into `onConflictFields` of upsert methods

---

packages/core/src/EntityManager.ts

Currently such code raises TS error:
```ts
await this.em.transactional((em) => {
worksheet.AcknowledgedDate = new Date();
em.persist(worksheet);
});
```
The error is the following:
```
Argument of type '(em: EntityManager<IDatabaseDriver<Connection>>) => void' is not assignable to parameter of type '(em: EntityManager<IDatabaseDriver<Connection>>) => Promise<unknown>'.
Type 'void' is not assignable to type 'Promise<unknown>'.
```
Even though a very similar example is suggested in MikroORM docs ( https://mikro-orm.io/docs/transactions#approach-2-explicitly ).
This PR I guess would fix this.

fix(core): allow `em.transactional` handler to be synchronous

---

packages/knex/src/dialects/mysql/MySqlSchemaHelper.ts
packages/knex/src/schema/DatabaseTable.ts
packages/knex/src/schema/SchemaHelper.ts
packages/mariadb/src/MariaDbSchemaHelper.ts
tests/features/entity-generator/__snapshots__/EntityGenerator.mssql.test.ts.snap
tests/features/entity-generator/__snapshots__/EntityGenerator.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/EntityGenerator.postgres.test.ts.snap
tests/features/entity-generator/__snapshots__/MetadataHooks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/OddPkTypes.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/ScalarPropsForFks.mysql.test.ts.snap

Note that MySQL and MariaDB populate an empty string in columns, always, even when none was defined. For them, empty comments on columns are turned into nulls.

fix(entity-generator): output entity and prop comments

---

docs/docs/defining-entities.md
docs/docs/guide/05-type-safety.md
docs/docs/type-safe-relations.md
packages/core/src/typings.ts

If one is to use a ScalarReference to get type-safe access to a lazily loaded scalar value it should be possible to encode in the types that the scalar may be null in the database. Currently, ScalarReferences, when de-referenced through `.get()` or `.$` are typed with "NonNullable" variants of their wrapped types. That non-nullability is not reflected at runtime, which opens up code that perfectly type-checks to runtime exceptions because of null reference accesses. This is demonstrated in this reproduction: https://github.com/ropbastos/mikro-orm-reproduction
Briefly linking the "fixed" version of the library with my companies project I didn't see any types that looked wrong, and all tests still pass, so I'm creating this PR. However, I'm aware the NonNullable helpers are pretty explicit …

fix(core): respect nullability of wrapped types for ScalarReference's

---

packages/core/src/types/Type.ts
packages/mssql/src/MsSqlPlatform.ts
tests/features/schema-generator/SchemaGenerator.postgres.test.ts

One broken usage in MsSqlPlatform and in SchemaGenerator.postgres.test.ts are fixed to work with it.

refactor: the Type.getType() method now returns the concrete type passed

---

docs/docs/dataloaders.md

I just found that `Dataloader` should be `DataloaderType` in the docs example.

docs: fix the dataloader reference in usage

---

packages/core/src/EntityManager.ts
packages/core/src/unit-of-work/ChangeSetPersister.ts
packages/mariadb/src/MariaDbDriver.ts
packages/mongodb/src/MongoConnection.ts
packages/mongodb/src/MongoDriver.ts
packages/mysql/src/MySqlDriver.ts
tests/features/upsert/GH3787-2.test.ts
tests/features/upsert/GH4153.test.ts
tests/features/upsert/__snapshots__/upsert-without-unique-values.test.ts.snap
tests/features/upsert/upsert-without-unique-values.test.ts

`em.upsert` and `em.upsertMany` no longer enforce a unique value in the payload. An insert with a default PK value is issued in such a case.

feat(core): allow upserting without a unique value

---

packages/entity-generator/src/SourceFile.ts
tests/features/entity-generator/OddTableNames.mysql.test.ts
tests/features/entity-generator/__snapshots__/OddTableNames.mysql.test.ts.snap

The naming strategy is now consulted for the default value option names.
Independent of the naming strategy, if the resulting option name is not a valid identifier, it will be used via "array access".

fix(entity-generator): fixed default values for enums

---

packages/migrations/src/Migrator.ts
tests/features/migrations/Migrator.test.ts
tests/features/migrations/__snapshots__/Migrator.test.ts.snap

This enables easier "schema first" approach, whereby users first create the schema through an initial migration, before generating the entities out of it.
The "No entities found" error is still present when the "--blank" flag is absent.
When using "--blank" and "--initial" together, the new blank migration is not logged.

feat(migrations): allow initial migration to be blank if no entities are defined

---

packages/core/src/typings.ts
packages/entity-generator/src/SourceFile.ts
tests/features/entity-generator/MetadataHooks.mysql.test.ts
tests/features/entity-generator/__snapshots__/MetadataHooks.mysql.test.ts.snap

Adding a new option repositoryClass to the meta data will produce a repository factory function, and a EntityRepositoryType symbol.
Repository classes themselves are not generated (yet). This is merely creating a reference to a class the user is responsible for creating, akin to a custom type reference.

feat(entity-generator): repository class reference can be added from hooks

---

packages/entity-generator/src/SourceFile.ts
tests/features/entity-generator/__snapshots__/AmbiguousFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/FkIndexSelection.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/FkSharedWithColumn.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/FksWithDefaults.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/NonCompositeAmbiguousFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/NullableFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/OverlapFks.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/ScalarPropsForFks.mysql.test.ts.snap

The extra information may be useful to custom types.
In the case of the "type" option, it's also required to skip runtime type inference.

fix(entity-generator): output all DB related info even for virtual properties

---

packages/core/src/decorators/CreateRequestContext.ts
tests/decorators.test.ts

I've noticed that there was an existing PR addressing the same issue (https://github.com/mikro-orm/mikro-orm/pull/5423) which hasn't been merged yet. Therefore, I've created this PR to address the issue.
According to [the documentation](https://github.com/mikro-orm/mikro-orm/blob/623ee3a9768a88184c8b249250135b891261886a/docs/docs/identity-map.md?plain=1#L132), `CreateRequestContext` or `EnsureRequestContext` should support a callback that returns an `EntityManager` instance, but currently, it does not.
This PR updates `CreateRequestContext` to support a callback that returns an `EntityManager` instance.
The following code does not work with the current implementation, but this PR resolves the issue:
```ts
export class Service {
constructor(private readonly em: EntityManager) {} …
```

fix(core): fix CreateRequestContext not working with callback returning EntityManager

---

docs/docs/seeding.md
docs/versioned_docs/version-6.3/seeding.md

Hello, this is just fixing a typo in the docs. The `make` method requires a number as its first argument, but the documents do not include that.
I added correct examples for `make` and `makeOne`, similar to the existing examples for `create` and `createOne` below it.

docs: fix `make` method usage example in seeding section

---

packages/core/src/utils/Configuration.ts

Knex moved to tarn.js way back (https://github.com/knex/knex/issues/4395), this type hasn't kept up
The current type includes options which will prevent the pool from starting up as tarn validates the provided options (`evictionRunIntervalMillis`) and is missing options which can be useful

fix(knex): update `PoolConfig` interface to match what knex supports

---

.github/workflows/tests.yml

Since the perf improvements in node 22 are quite significant, this should lower the overall CI time spent in tests in the slower node versions.

test: generate code coverage only on node 22

---

docs/docs/guide/03-project-setup.md
docs/versioned_docs/version-6.3/guide/03-project-setup.md

The initial test setup was missing the `entities` option in the ORM configuration, leading to a 'No entities found' error. Updated `initTestApp` function to include the existing configuration from `mikro-orm.config.js` and override specific settings for testing.
- Imported the existing ORM configuration.
- Added `entities` option to the configuration for test environment.

docs(guide): resolve 'No entities found' error in test setup

---

docs/docs/guide/04-advanced.md
docs/versioned_docs/version-6.3/guide/04-advanced.md

fix "Generic type 'RequiredEntityData' requires between 1 and 3 type arguments." errors in docs

docs(guide): add missing generics

---

packages/core/src/hydration/ObjectHydrator.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/platforms/Platform.ts
packages/core/src/utils/Configuration.ts
packages/core/src/utils/EntityComparator.ts
packages/mssql/src/MsSqlConnection.ts
packages/postgresql/src/PostgreSqlPlatform.ts
tests/features/custom-types/GH5540.postgres.test.ts
tests/features/embeddables/__snapshots__/entities-in-embeddables.postgres.test.ts.snap
tests/features/upsert/GH4242.test.ts
tests/issues/GH5591.test.ts

Postgres driver always used to write dates as UTC, but it was parsing them back in local timezone by default. Now it properly respects the `forceUtcTimezone` and `timezone` options. The postgres driver defaults to `forceUtcTimezone: true` since it used to be writing everything in UTC anyway. 
Other drivers behave differently, notably MySQL and MSSQL use `forceUtcTimezone: false` by default, changing that would be breaking, but we might want to normalize this in v7.
This also improves the processing of properties with a custom type and a runtime type `Date`, those used to be always converted during result mapping, now we only do such conversion if the custom type is not a numeric type like int/bigint.
Closes #5591

fix(postgres): respect `timezone` option and interpret `timestamp` columns in UTC by default

---

README.md

Current link is broken: https://mikro-orm.io/docs/lifecycle-hooks

docs: update link for lifecycle hooks

---

packages/knex/src/AbstractSqlDriver.ts
tests/features/cursor-based-pagination/virtual-entities.test.ts

Now we cannot use cursor-based pagination on virtual entities because  `qb.where` will override the `processCursorOptions` return where.
So I move the `qb.where(where)` to beginning.

fix(sql): correct cursor conditions application on virtual entities

---

packages/core/src/utils/clone.ts
tests/Utils.test.ts

I'm using MikroORM 6.3.7 with Postgresql 14.
I'm using MikroORM with ts-jenum.
When I use [ts-jenum](https://github.com/reforms/ts-jenum) in MikroORM's where condition, following error occurs
```
Cannot set property enumName of [object Object] which has only a getter
TypeError: Cannot set property enumName of [object Object] which has only a getter
```
This issue was caused by the [following code](https://github.com/reforms/ts-jenum/blob/e1a45f54537ec5bd6abc258391e656e8c6339595/src/ts/jenum.ts#L181-L184). In the ts-jenum library, the “enumName” of the parent enum type has a getter but no setter implemented. Therefore, when [clone.ts tries to call the setter](https://github.com/mikro-orm/mikro-orm/blob/c0dacd8964786118d094fb6f88c3c136bcfa7115/packages/core/src/utils/clone.ts#L123), an …

fix(core): check proptotype chain while cloning

---

packages/knex/src/schema/SchemaHelper.ts
packages/mssql/src/MsSqlSchemaHelper.ts
packages/postgresql/src/PostgreSqlSchemaHelper.ts

This changes `MsSqlSchemaHelper` and `PostgreSqlSchemaHelper` to group tables by schema name and use `IN` operator for table names instead of using `OR` for every schema/table combo, e.g.
```sql
WHERE (
(ccu.table_name = 'seals' and ccu.table_schema = 'mammals')
OR (ccu.table_name = 'owls' and ccu.table_schema = 'birds')
OR (ccu.table_name = 'parrots' and ccu.table_schema = 'birds')
)
```
becomes
```sql
WHERE (
(ccu.table_name IN ('seals') and ccu.table_schema = 'mammals')
OR (ccu.table_name IN('owls','parrots') and ccu.table_schema = 'birds')
)
```
This doesn't change the current behavior, yet it makes the entity generator faster (at least for large databases) when multiple tables belong to the same schema (which is almost always the case).

refactor: group tables by schema to load information schema

---

packages/knex/src/query/QueryBuilder.ts
tests/features/embeddables/GH5992.test.ts

Fixes using proper alias, within selects, when dealing with embedded objects.
Closes #5992

fix(core): allow proper select with embedded many to many

---

packages/core/src/EntityManager.ts
packages/core/src/drivers/IDatabaseDriver.ts
packages/knex/src/AbstractSqlDriver.ts
packages/knex/src/query/QueryBuilder.ts
tests/EntityManager.mysql.test.ts
tests/features/__snapshots__/dataloader.test.ts.snap
tests/features/embeddables/GH5325.test.ts
tests/features/filters/filters.postgres.test.ts
tests/features/joined-strategy.postgre.test.ts
tests/issues/GHx16.test.ts

#5893 introduced the concept of nested inner joins, used for the `populateWhere` conditions when the parent is a to-many relation. This ensures the collection items are discarded if they conflict with the child condition. While it makes sense for the `populateWhere` to behave this way, we also use this option internally for filters on joined relations, and there we can't just discard items because the children are not correct.
This PR introduces new `populateFilter` option, which is now used for the joined filters and will produce simple `left join`s, unlike the `populateWhere` option.

fix(core): implement joined filters via `populateFilter` option, separately from `populateWhere`

---

packages/migrations/src/MigrationGenerator.ts
tests/features/migrations/__snapshots__/Migrator.mssql.test.ts.snap
tests/features/migrations/__snapshots__/Migrator.postgres.test.ts.snap
tests/features/migrations/__snapshots__/Migrator.sqlite.test.ts.snap
tests/features/migrations/__snapshots__/Migrator.test.ts.snap

This enables better handling of multi line SQL statements, which users can produce with customization of MigrationGenerator that result in a single statement spanning multiple lines.
Related to #6015

fix(migrations): support multiline strings in `addSql()`

---

packages/core/src/EntityManager.ts
packages/core/src/entity/EntityLoader.ts
packages/core/src/hydration/ObjectHydrator.ts
packages/core/src/unit-of-work/ChangeSetComputer.ts
tests/EntityFactory.test.ts
tests/EntityManager.mongo.test.ts
tests/features/partial-loading/m-n-owners.mongo.test.ts

This resolves several things for mongo specific M:N implementation, which uses array properties on owning sides.
- new entities with empty collections are now property saves with `[]` value
- partial loading without the collection property will result in not initialized collection
- `em.populate` can be used to load such relation without the initial value

fix(mongo): support partial loading of M:N owning sides

---

packages/core/src/utils/Utils.ts

When the extension is not registered, paths are needed, both in ESM and in CJS.
When the extension is registered, file URLs are OK regardless of ESM or CJS. When the extension is registered, paths are OK in CJS, but not in ESM, which is what the original patching was meant to be doing.

fix(core): properly detect when Windows imports need patching

---

packages/knex/src/dialects/mysql/MySqlColumnCompiler.ts
packages/knex/src/schema/DatabaseTable.ts
packages/knex/src/schema/SchemaHelper.ts
packages/knex/src/typings.ts
tests/issues/GH6057.test.ts

Support for the unsigned attribute on auto-incrementing primary keys seems to be a special case that is likely only supported by MySQL.
Previous source code seemed to be designed to generate DDL for MySQL without considering unsigned property, similar to how it handles schema generation for other databases.
In scenarios where the unsigned option needs to be passed, the code relied on the external knex package's types.
To address this, I modified the code to extend these types.
Initially, I attempted to override interface types within namespace using `declare module`, but encountered type conflicts.
As a solution, I chose to inherit from the existing TableBuilder interface.
Closes #6057

fix(schema): ensure `unsigned: false` works for primary keys

---

packages/knex/src/dialects/mysql/MySqlColumnCompiler.ts
packages/knex/src/dialects/mysql/MySqlSchemaHelper.ts
packages/knex/src/schema/SchemaHelper.ts
packages/knex/src/typings.ts
tests/features/schema-generator/SchemaGenerator.mysql.test.ts
tests/features/schema-generator/__snapshots__/GH3230.test.ts.snap
tests/issues/GH5996.test.ts
tests/issues/GH6057.test.ts

Modified the handling of `tinyint/smallint/mediumint` primary keys to be consistent with `int/bigint`.
This involved removing branching code specific to `MediumIntType` and making minor adjustments to existing test code.

fix(schema): ensure `CREATE TABLE` DDL for `tinyint/smallint/mediumint` primary keys

---

packages/knex/src/query/QueryBuilder.ts
tests/issues/GH6083.test.ts
tests/issues/__snapshots__/GH6083.test.ts.snap

The result of the first cached execute('get') is guaranteed to be a single object,
so I modified it to ensure that the data stored in or retrieved from the cache is a single object.
When there is no result, it will be `null` rather than an array containing `null`.
Closes #6083

fix(query-builder): ensure cached `execute('get')` returns a single result instead of an array

---

packages/core/src/utils/clone.ts
packages/mongodb/src/MongoPlatform.ts
tests/issues/GH6091.test.ts

This PR fixes a regression introduced in v6.3.11.
After upgrading from v6.3.10 to v6.3.11, ObjectID subproperties of JSON properties are not persisted in the MongoDB database.
The fix reverts the change in 55df57ff1aa84e5d45188d849ba09e91ae6d3642 that uses `structuredClone` instead of `Utils.clone()` to convert JSON to database values in the MongoDB driver. Unfortunately, `structuredClone` doesn't clone non-built-in classes (see [supported types](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#javascript_types)).
I've added a condition to `Utils.clone` to continue supporting both tests:
- [should copy child object even though getter property is dynamically injected](https://github.com/mikro-orm/mikro-orm/blob/f48e5443f3fe3539d24a53dcb6a82f280e399 …

fix(mongo): fix persisting objects like `ObjectID` in JSON properties

---

packages/core/src/entity/EntityFactory.ts
tests/issues/GH6092.test.ts

Return value of `extractConstructorParams` appears to be passed only as an argument to the Entity constructor.
In typical use cases, entities in many relationships should only be accessed through a Collection.
However, in special situations where `forceEntityConstructor: true`, users can handle it directly in the constructor.
Closes #6092

feat(core): prevent conversion of `many` entities in `oneToMany` from `extractConstructorParams`

---

.github/workflows/tests.yml
docker-compose.yml
packages/core/src/utils/Utils.ts
tests/Utils.test.ts
tests/features/embeddables/GH2391-2.test.ts
tests/features/embeddables/GH2391.test.ts

This small PR fixes a minor regression that I think was introduced in https://github.com/mikro-orm/mikro-orm/commit/55df57ff1aa84e5d45188d849ba09e91ae6d3642.
When updating an entity and changing a date property to another one very close to it (by a difference in microseconds), the change is not persisted in the database. Indeed, diffing dates by comparing the `toString()` output doesn't give enough precision to compare microseconds shifts. Example:
- `toString()` output: `Tue Oct 01 2024 08:54:48 GMT+0000 (Coordinated Universal Time)`
- `toISOString()` output: `2024-10-01T08:54:48.651Z`
Two dates can have the same `toString()` output even though their `toISOString()` output is different.
The impact is low and probably only concerns the test scenarios: It's rare to persist the same entity …

fix(core): fix same-second dates diffing

---

docs/docs/serializing.md
docs/versioned_docs/version-6.0/serializing.md
docs/versioned_docs/version-6.1/serializing.md
docs/versioned_docs/version-6.2/serializing.md
docs/versioned_docs/version-6.3/serializing.md

The documentation for 6.x says `forceObject` should be `false` if you want to enforce objects. This is wrong, it should be `true`.

docs: fix forceObject to true to enforce objects

---

packages/entity-generator/src/EntityGenerator.ts
packages/knex/src/schema/DatabaseSchema.ts
tests/features/custom-order/custom-order.mssql.test.ts
tests/features/entity-generator/EntityGenerator.postgres.test.ts
tests/features/entity-generator/__snapshots__/EntityGenerator.postgres.test.ts.snap
tests/features/entity-generator/__snapshots__/OddTableNames.mysql.test.ts.snap
tests/features/entity-generator/__snapshots__/OddTableNames.postgres.test.ts.snap
tests/features/entity-generator/__snapshots__/multple-schemas.postgres.test.ts.snap
tests/features/multiple-schemas/__snapshots__/multiple-schemas.mssql.test.ts.snap
tests/features/multiple-schemas/__snapshots__/multiple-schemas.postgres.test.ts.snap
tests/features/multiple-schemas/multiple-schemas.mssql.test.ts
tests/features/multiple-schemas/multiple-schemas.postgres.test.ts
tests/features/truncate/truncate.mssql.test.ts
tests/features/truncate/truncate.mysql.test.ts
tests/features/truncate/truncate.postgresql.test.ts
tests/features/truncate/truncate.sqlite.test.ts

This moves table filtering from after retrieving all table details (i.e. columns, foreign keys, etc.) to after retrieving a list of tables as described in #5900.
Closes #5900

perf(schema): filter tables before fetching table details

---

docs/docs/entity-manager.md
packages/core/src/EntityManager.ts
packages/core/src/utils/Configuration.ts
tests/features/upsert/GH3667.test.ts
tests/features/upsert/GH3787-2.test.ts
tests/features/upsert/upsert-managed.test.ts
tests/features/upsert/upsert.mssql.test.ts
tests/features/upsert/upsert.test.ts

Previously, if you tried to upsert a managed entity, the call was interpreted as `assign`, and an explicit `flush` was required to persist those changes to the database. Now the upsert query is always issued regardless of the entity being managed or not.
To opt in to the previous behavior, use `upsertManaged: false` in the ORM config.
Closes #6055

feat(core): upsert managed entities

---

docs/docs/configuration.md
packages/core/src/utils/Configuration.ts
packages/knex/src/AbstractSqlConnection.ts
tests/EntityManager.postgre.test.ts
tests/bootstrap.ts

Sometimes you might want to alter the generated queries. One use case for that might be adding contextual query hints to allow observability. Before a more native approach is added to the ORM, you can use the `onQuery` hook to modify all the queries by hand. The hook will be fired for every query before its execution.
```ts
import { AsyncLocalStorage } from 'node:async_hooks';
const ctx = new AsyncLocalStorage();
// provide the necessary data to the store in some middleware
app.use((req, res, next) => {
const store = { endpoint: req.url };
ctx.run(store, next);
});
MikroORM.init({
onQuery: (sql: string, params: unknown[]) => {
const store = ctx.getStore();
if (!store) {
return sql;
}
// your function that generates the necessary query hint
const hint = createQueryHint(store);
return sql + …
```

feat(core): add `onQuery` hook

---

docs/docs/configuration.md
docs/docs/logging.md
packages/cli/src/CLIConfigurator.ts
packages/cli/src/CLIHelper.ts
packages/cli/src/commands/ClearCacheCommand.ts
packages/cli/src/commands/CreateDatabaseCommand.ts
packages/cli/src/commands/CreateSeederCommand.ts
packages/cli/src/commands/DatabaseSeedCommand.ts
packages/cli/src/commands/DebugCommand.ts
packages/cli/src/commands/GenerateCacheCommand.ts
packages/cli/src/commands/GenerateEntitiesCommand.ts
packages/cli/src/commands/ImportCommand.ts
packages/cli/src/commands/MigrationCommandFactory.ts
packages/cli/src/commands/SchemaCommandFactory.ts
packages/core/src/MikroORM.ts
packages/core/src/connections/Connection.ts
packages/core/src/logging/DefaultLogger.ts
packages/core/src/logging/Logger.ts
packages/core/src/utils/Configuration.ts
packages/core/src/utils/ConfigurationLoader.ts
packages/knex/src/AbstractSqlConnection.ts
packages/mongodb/src/MongoConnection.ts
tests/Connection.test.ts
tests/EntityManager.mongo2.test.ts
tests/features/cli/CLIHelper.test.ts
tests/features/cli/CreateSeederCommand.test.ts
tests/features/cli/DebugCommand.test.ts
tests/features/logging/Logger.test.ts

The output of debug is adjusted as a consequence of the config being a passed dependency. Driver dependency versions are going to be shown if a config is found, independently of whether a package.json was found.
The config is always validated, even during entity generation. When warnings about missing entities are disabled, the entities options are also set to empty arrays, to avoid the old / additional entities' meta data influencing the entity generation.
If the config path is automatically inferred from a CLI argument during MikroORM.init(), a deprecation warning is logged.

refactor(cli): made the CLI explicitly pass the config path from the arg, or else infer it once

---

packages/core/src/utils/ConfigurationLoader.ts
tests/features/cli/CLIHelper.test.ts

If true is explicitly given at the first argument, it will trigger the legacy behavior, where `--config` is also searched for in `process.argv`.
If left without arguments, the new default is used, which is still mostly compatible, except `--config` is not searched in `process.argv`.
In either situation, the paths to search for default to the result of `ConfigurationLoader.getConfigPaths()`.

refactor: make `ConfigurationLoader.getConfiguration()` backwards compatible

---

docs/docs/guide/03-project-setup.md
docs/docs/metadata-providers.md
packages/cli/src/CLIConfigurator.ts
packages/cli/src/CLIHelper.ts
packages/cli/src/commands/DebugCommand.ts
packages/core/src/MikroORM.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/utils/Configuration.ts
packages/core/src/utils/ConfigurationLoader.ts
packages/migrations-mongodb/src/Migrator.ts
packages/migrations/src/Migrator.ts
packages/seeder/src/SeedManager.ts
tests/bootstrap.ts
tests/features/cli/DebugCommand.test.ts
tests/features/reflection/TsMorphMetadataProvider.test.ts

The name `tsNode` was confusing and rather a relic from the past. The purpose of this option was always the same, telling the ORM that TS is supported, regardless of its auto-detection thinking something else.
The old `tsNode` name is still supported for backwards compatibility.

fix(core): rename `tsNode` option to `preferTs`

---

packages/core/src/errors.ts
packages/core/src/metadata/MetadataValidator.ts
packages/core/src/utils/Configuration.ts
tests/MetadataValidator.test.ts

Adding `persist: false` to relations is supported, but rather discouraged, it was designed to be used on scalars instead. Using it on a relation targeting composite PK will cause issues and is now disallowed. You can opt out of this validation via `checkNonPersistentCompositeProps` discovery option.

feat(core): validate non-persistent relations are not composite

---

packages/core/src/utils/ConfigurationLoader.ts
tests/features/cli/CLIHelper.test.ts

There is now a search for files even on validate files, so that if there is a config, it can be augmented with envs rather than an env only config being returned.
The search for files itself is now moved into a separate helper function called getConfigFile which returns a tuple of path and config file contents (whatever it may be) or an empty tuple (when none of the config files existed or failed to be imported). As a nice side effect of this,
the complexity of ConfigurationLoader.getConfiguration is reduced by a little.

refactor: the BC layer of ConfigurationLoader.getConfiguration now fully emulates old behavior

---

docs/docs/guide/02-relationships.md
docs/versioned_docs/version-6.4/guide/02-relationships.md

Respect the definite assignment assertion operator in the entity 'Article'. Without assigning the previously missing class variables, TypeScript complains about the same.
Closes https://github.com/mikro-orm/guide/issues/5

docs: Update 02-relationships.md

---

packages/core/src/entity/EntityLoader.ts
packages/knex/src/AbstractSqlDriver.ts
tests/features/unit-of-work/map-to-pk.test.ts

Related issue: [#6265](https://github.com/mikro-orm/mikro-orm/pull/6265). Before the changes, populating a `mapToPk` relation did not extract just the key; instead, the entire entity object was assigned to the property.
I have added tests for both simple and composite primary keys. While adding tests for the `select-in` loading strategy, I noticed that the second query (for loading the primary key entity) is not executed. This makes sense because the keys are already selected.  
This led me to reconsider whether we should use a join for the `joined` strategy, as the keys are already present on the owning entity. 
**Select-in strategy:**
```sql
select `t0`.* 
from `team` as `t0` 
where `t0`.`id` = 'team1' 
limit 1
```
**Joined strategy:**
```sql
select `t0`.*, `c1`.`id` as `c1__id`
from …
```

fix(core): correctly handle populate of `mapToPk` relations

---

packages/knex/src/query/QueryBuilder.ts
tests/issues/GHx17.test.ts

If you query entity already in identityMap, its serialization options will not be modified from joins from the query builder. This concats the populate options just like in `setSerializationOptions` so all fields will be populated from the identity map and inserted into the serialized result

fix(query-builder): combine serialization hint from managed entities and QueryBuilder result

---

packages/mongodb/src/MongoConnection.ts
tests/EntityManager.mongo.test.ts

The PR incorporates MongoDB's [wrapping client library](https://github.com/mongodb/specifications/blob/master/source/mongodb-handshake/handshake.md#supporting-wrapping-libraries) specification for the connection handshake to allow library details to be included in the metadata written to `mongos` or `mongod` logs.
For example, this change would allow server-side logs such as the following:
> {"t":{"$date":"2024-01-27T23:10:40.108Z"},"s":"I","c":"NETWORK","id":51800,"ctx":"conn16235","msg":"client metadata","attr":{"remote":"127.0.0.1:1094","client":"conn16235","doc":{"driver":{`"name":"nodejs|MikroORM"`,`"version":"6.12.0|6.4.2"`},"platform":"Node.js v18.18.2, LE","os":{"name":"linux","architecture":"x64","version":"5.15.133+","type":"Linux"}}}}
For anyone hosting clusters with …

feat(mongo): include MikroORM version in MongoDB handshake

---

packages/seeder/src/Factory.ts

Currently when I am extending a `Factory` class, so that e.g. I can build definitions of child relations, I can't reuse other `Factory` classes, as they depend on `EntityManager`. Factory class access to the entity manager, but it is `private`. If it were `protected`, then I could reuse it.
For now I have to cheat TypeScript into thinking that `this.em: EntityManager` exists (and it does).
Example usage:
```ts
// organisation.factory.ts
import { faker } from '@faker-js/faker';
import { Factory } from '@mikro-orm/seeder';
import { OrganisationEntity } from '../entities/organisation.entity';
export class OrganisationFactory extends Factory<OrganisationEntity> {
model = OrganisationEntity;
definition(): Partial<OrganisationEntity> {
return {
name: faker.company.name(),
};
}
}
// …
```

feat(seeder): make `Factory.em` protected

---

packages/mariadb/src/MariaDbSchemaHelper.ts

New minimum version is 5.3.1, when MariaDB specific execution comments were introduced.
Fixes #6350

fix(schema): fixed handling of check constraints on MariaDB before 10.5.10

---

packages/seeder/src/Factory.ts
tests/features/seeder/factory.test.ts

Sometimes I want to dynamically assign different params to my seeded entities, depending on their index.
Example:
```ts
const participants = await new TournamentParticipantFactory(em)
.each((p, i) => {
p.seed = i + 1;
})
.create(16, {
tournament,
});
```
Without this, I have to write something like
```ts
const participants = await new TournamentParticipantFactory(em)
.create(16, {
tournament,
});
participants.forEach((p, i) => { p.seed = i + 1; });
await em.persistAndFlush(participants);
```
This in part resolves https://github.com/mikro-orm/mikro-orm/discussions/3002 .

feat(seeder): make `.each()` function receive `index: number` argument

---

docs/docs/seeding.md
packages/seeder/src/Factory.ts
tests/features/seeder/factory.test.ts

Some of my entities have a lot of attributes, that can have a lot of combinations. It would be nice if I could pass a property to the `.definition()` method (when making or creating an entity), so that I can dynamically define how a generated entity should look like.
Example usage:
```ts
export class TournamentFactory extends Factory<
TournamentEntity,
EntityData<TournamentEntity> & { groupsCount?: number }
> {
model = TournamentEntity;
async definition(
params?: EntityData<TournamentEntity> & { groupsCount?: number }
): EntityData<TournamentEntity> {
return {
name: "XXX Olympic Games",
...params,
groups: params.groups ?? [...Array(params?.groupsCount ?? 0)].map((v, i) =>
new TournamentGroupFactory(this.em).makeEntity({
number: i + 1,
})
),
};
}
}
// Final usage
new …
```

feat(seeder): pass params to `.definition()` function as argument

---

packages/core/src/EntityManager.ts
packages/core/src/typings.ts

This PR adds an extra argument to the filters condition function.
When you execute a relational query, a filter function is executed multiple times. By using the entity name, you can deduce which layer the filter is applied to.

feat: add entityname as argument for filters

---

packages/reflection/src/TsMorphMetadataProvider.ts

This significantly reduces the time to initialize the TS project. We were previously checking all the files included in the tsconfig.json, which usually means the whole project. We add the entity files explicitly, so this shouldn't be needed.

perf(reflection): only consider entity files instead of evaluating the whole project

---

packages/core/src/decorators/Entity.ts
packages/core/src/decorators/Indexed.ts
packages/core/src/metadata/EntitySchema.ts
packages/entity-generator/src/SourceFile.ts
packages/knex/src/schema/DatabaseTable.ts

hi! this PR improves the typings for these decorator options:
- `@Entity` → `discriminatorColumn`
- `@Index`, `@Unique` → `properties`
so that they only accept property keys from the decorated class, instead of just any string.
this particular example is pretty cool, as it shows how this supersedes the runtime [`unknownIndexProperty`](https://github.com/mikro-orm/mikro-orm/blob/a6c48fd1b436edcd2bcead74ebfec42bb65da043/packages/core/src/errors.ts#L214) error (at least in simple cases where every property is a @​Property):
```ts
@Unique({ properties: ["platform_id" }) // Type '"platform_id"' is not assignable to type 'keyof Thing'. Did you mean '"platformID"'?
@Unique({ properties: ["platform", "platformID"] }) // good
class Thing { id: number, platform: string, platformID: number }
``` …

feat(core): improve typings for `@Entity`, `@Index` and `@Unique` decorators

---

packages/core/src/entity/Collection.ts
tests/features/collection/collection-order.test.ts

After adding default `orderBy` to my collection in the entity class `@OneToMany(...)` decorator, I noticed that my collections are sometimes sorted correctly and sometimes not at all.
Upon debugging it appeared that this happens only if `dataloader` is enabled (and it is, in my case).
This PR fixes it, making the `Collection#loadItems` load items in the default order (rather than none) also when dataloader is enabled. (Currently, it happens only when it is disabled.)

fix(core): respect Collection property `orderBy` when dataloader is enabled

---

packages/core/src/utils/Utils.ts

This check was problematic because of Node.js type stripping uses it now too, and it does fail to parse decorators.
It was already removed from v7, but since the type stripping will be backported to Node.js 22, I am removing it from v6 too, otherwise things break when executing the compiled code.
Related to https://github.com/nodejs/node/pull/57298#issuecomment-2703430792

fix(core): skip TS support detection via `require.extensions`

---

docs/docs/serializing.md
docs/versioned_docs/version-6.0/serializing.md
docs/versioned_docs/version-6.1/serializing.md
docs/versioned_docs/version-6.2/serializing.md
docs/versioned_docs/version-6.3/serializing.md
docs/versioned_docs/version-6.4/serializing.md

Very minor fix.
I believe the title "Foreign keys are `forceObject`" must be a typo, because it does not make sense to me.
I think the intended title is "Foreign keys _and_ `forceObject`".

docs: fix typo in Foreign keys and `forceObject` title

---

packages/postgresql/src/PostgreSqlSchemaHelper.ts

This PR fixes an issue I had when using the migration tool using CockroachDB.
When running migration:create or similar, any existing enums are fetched from the database. For some reason with CockroachDB, Knex or the driver automatically deserializes the array, so `unmarshallArray` will fail.

fix(postgres): cockroachdb may not require unmarshallArray

---

packages/core/src/utils/Utils.ts

In bun 1.2.7 the error stack trace (used in `lookupPathFromDecorator`) was changed (see the image below, the line starting with `--` was dropped ). Therefore, mikro-orm doesn't work on this bun version (and the following versions). This PR should fix it. Works for both 1.2.6 and 1.2.7.

Fix entity path discovery for bun 1.2.7

---

tests/Utils.test.ts

Adds test for the entity path discovery fix for bun 1.2.7 (merged in #6564).
I have added the current stack trace for `bun run`. I am not sure about the other use cases (e.g., `bun build`) in bun 1.2.7, but they work quite differently so they shouldn't be affected by this change.

test: lookupPathFromDecorator for bun 1.2.7

---

packages/postgresql/src/PostgreSqlSchemaHelper.ts
tests/features/schema-generator/enum-diffing.postgres.test.ts

- Add functionality to handle default values and nullable properties in the PostgreSqlSchemaHelper.
- Update tests to verify changes, including scenarios for adding/removing default values and nullable constraints in enum fields.
Closes #6571

fix(postgres): fix schema diffing for `default` and `nullable` of check constraint enums

---

packages/core/src/EntityManager.ts

fix(core): make `populate` parameter of `em.populate()` readonly

---

docs/docs/guide/01-first-entity.md
docs/versioned_docs/version-6.3/guide/01-first-entity.md
docs/versioned_docs/version-6.4/guide/01-first-entity.md

Change was made in this PR: https://github.com/mikro-orm/mikro-orm/pull/5650 - the code sample was updated but not this sentence. Great package by the way, I'm new coming from EF Core that is also based on Data Mapper and really enjoying it so far.
I've gone through the entire guide now and don't see any other mentions of `mikro-orm` in `package.json`

docs:  remove mention for manual typescript config in `package.json`

---

packages/mssql/src/MsSqlPlatform.ts
tests/platforms/order-by.test.ts

This PR fixes an issue with order by with nulls first and nulls last

fix(mssql): handle mapping for order by expressions with nulls first/last

---

docs/docs/filters.md

@B4nan I don't sure if it's an expected behavior since it's possible to have same names for different entities defined in `@Filter`. Anyway, I think it is nice to highlight the current behavior in the doc.

chore(docs): document global addFilter behavior

---

docs/docs/relationships.md
packages/core/src/decorators/ManyToMany.ts
packages/core/src/decorators/ManyToOne.ts
packages/core/src/decorators/OneToOne.ts
packages/core/src/metadata/EntitySchema.ts
packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/typings.ts
packages/knex/src/schema/DatabaseTable.ts
packages/knex/src/schema/SchemaHelper.ts
packages/knex/src/typings.ts
tests/features/createForeignKeyConstraint/__snapshots__/createForeignKeyConstraint.mysql.test.ts.snap
tests/features/createForeignKeyConstraint/__snapshots__/createForeignKeyConstraint.postgres.test.ts.snap
tests/features/createForeignKeyConstraint/createForeignKeyConstraint.mysql.test.ts
tests/features/createForeignKeyConstraint/createForeignKeyConstraint.postgres.test.ts
tests/features/createForeignKeyConstraint/entities/Author.ts
tests/features/createForeignKeyConstraint/entities/AuthorAddress.ts
tests/features/createForeignKeyConstraint/entities/BaseEntity.ts
tests/features/createForeignKeyConstraint/entities/Book.ts
tests/features/createForeignKeyConstraint/entities/BookTag.ts
tests/features/createForeignKeyConstraint/entities/Publisher.ts
tests/features/createForeignKeyConstraint/entities/PublisherAddress.ts

This PR follows my comment [here](https://github.com/mikro-orm/mikro-orm/issues/2548#issuecomment-2765607556) regarding the possibility to disable foreign key constraint, per relation.
This work complements what had been previously done in fcdb236.
Being able to disable foreign key creation on specific relations is useful when using DDD (Domain Driven Design) philosophy to design your app. Inside a DDD aggregate, entities are linked to each other by object references, and at the DB level we want to have strong integrity using foreign key constraint. Now for cross-aggregate links, we usually want to use _soft references_, meaning at the db level we just want an id referencing another entity but without the foreign key constraint.
Down the road it allows to implement eventual consistency …

feat(schema): allow disabling foreign key constraint creation, per relation

---

packages/core/src/metadata/MetadataDiscovery.ts
packages/core/src/utils/QueryHelper.ts
packages/knex/src/dialects/mysql/MySqlSchemaHelper.ts
packages/knex/src/query/CriteriaNodeFactory.ts
tests/features/schema-generator/__snapshots__/diffing-default-values.test.ts.snap
tests/issues/GH6688.test.ts
tests/issues/__snapshots__/GH6688.test.ts.snap

Fixes #6688. While testing across all databases, MySQL was failing with the following error:
```sql
DriverException: create table `a` (
`id` int unsigned not null auto_increment primary key,
`languages` text not null default 'en',
`accounts` json not null default '[]',
`items` text not null default ''
) default character set utf8mb4 engine = InnoDB;
- BLOB, TEXT, GEOMETRY or JSON column 'languages' can't have a default value
```
See: https://dev.mysql.com/doc/refman/9.0/en/data-type-defaults.html
> The [BLOB](https://dev.mysql.com/doc/refman/9.0/en/blob.html), [TEXT](https://dev.mysql.com/doc/refman/9.0/en/blob.html), GEOMETRY, and [JSON](https://dev.mysql.com/doc/refman/9.0/en/json.html) data types can be assigned a default value only if the value is written as an expression, even if the …

fix(schema): properly handle array defaults

---

packages/knex/src/AbstractSqlDriver.ts
tests/issues/GH6715.test.ts

This PR fixes lazy support for custom type properties, which were always selected even if not explicitly populated.

fix(sql): correctly handle lazy scalar properties with custom types

---

docker-compose.yml

Running
```
docker compose up -d
yarn test
```
yields broken tests because of a failing MSSQL docker container. The container is reporting `no such file or directory` (last line of the output). The version prior to latest works fine and all tests pass.
Given the other database containers are version pinned, this one probably should be too. 
In this case `latest` === `mcr.microsoft.com/mssql/server:2025-CTP2.1-ubuntu-22.04`.
```
2025-07-11 16:13:14 This program has encountered a fatal error and cannot continue running at Fri Jul 11 21:13:14 2025
2025-07-11 16:13:14 The following diagnostic information is available:
2025-07-11 16:13:14 
2025-07-11 16:13:14          Reason: 0x00000006
2025-07-11 16:13:14         Message: PROCESS_FAULT_FLAGS_UNHANDLED_EXCEPTION: The process [sqlservr.exe ] …
```

Pin mssql container to a non-latest 2025 version

---

docs/docs/guide/01-first-entity.md

fix(docs): SchemaGenerator typo on docs/guide/first-entity

---

packages/knex/src/AbstractSqlDriver.ts
tests/EntityManager.postgre.test.ts

**TL;DR**: Optimize `mergeJoinedResult` for JOINED strategy to prevent quadratic performance on large collections
🚧 **Problem**
When populating large collections in JOINED strategy, query result processing becomes prohibitively slow as the collection size grows.
On a findOne by primary key populating a 5k items collection, it takes ~6 seconds on my machine (MacBook Pro, Apple M1 Pro, 32 GB RAM).
By digging into it, I found the cause to be the `AbstractSqlDriver.prototype.mergeJoinedResult` method in the `knex` package .
Profiling showed ~12.5 million loop iterations, indicating an O(n²) like behavior due to nested loops inside the merge logic.
This leads to high CPU usage and increased memory pressure during result assembly.
Example reproduction (included in PR tests):
```ts
const author …
```

perf(knex): revamp mergeJoinedResult algorithm to boost perfs

---

docs/docs/json-properties.md
docs/versioned_docs/version-6.4/json-properties.md

Explained how the json type is persisted differently depending on the database used.

docs: clarify why `JsonType` is needed

---

docs/docs/defining-entities.md
docs/docs/guide/02-relationships.md
docs/versioned_docs/version-6.1/guide/02-relationships.md
packages/core/src/typings.ts
tests/types.test.ts

Followup from https://github.com/mikro-orm/mikro-orm/discussions/6744#discussioncomment-13766303
This PR adds a type `RequiredNullable ` that can be used to make an entity field nullable, but still require the user to supply a value (`null` or otherwise) when instantiating 
```ts
export class Article extends BaseEntity {
@Property({ length: 1000 })
description: RequiredNullable<string>;
// ...
}
em.create(Article, { description: "Description!" }); // ok
em.create(Article, { description: null }); // ok
em.create(Article, {}); // compile error: missing description
```

feat(core): add `RequiredNullable` helper type

---

docker-compose.yml
packages/knex/src/query/ObjectCriteriaNode.ts
tests/issues/GH6824.test.ts

- Set preferNoBranch to true if relationship is :1. This allows the child alias to be correctly matched.
Closes #6824

fix(query-builder): skip branching on to-one joins

---

packages/core/src/utils/EntityComparator.ts
tests/features/embeddables/__snapshots__/GH2391-2.test.ts.snap
tests/features/embeddables/__snapshots__/GH2391.test.ts.snap
tests/issues/GH6861.test.ts

reproduction repo – https://github.com/isaryy/mapped-field-overwrite-reproduction
closes #6861

fix: correctly map raw result fields to entity properties with @Property({ name: 'x_name' })

---

packages/core/src/entity/EntityLoader.ts
tests/issues/GH6874.test.ts

- When getting entities and populating child references with `SELECT_IN` and `BALANCED` strategies, a max call stack error is triggered due to `.push` and `...` being used in conjunction in `getChildReferences` for larger datasets (>100k entities). 
- This is because using push and spread adds each array element onto `.push`'s method parameters and, in turn, the call stack. 
```
children.push(...array) --> children.push(array[0], array[1], ... array[n)) // stack overflow.  
```
I've been able to reproduce this in this repo: https://github.com/kitopang/mikro-orm-populate-strategy-bug

fix(core): prevent stack overflow errors when using SELECT_IN populate strategy on lots of entities

---

packages/core/src/typings.ts

This PR will fix https://github.com/mikro-orm/mikro-orm/issues/6882
In the current implementation, for the following entity:
```ts
import { defineEntity, type InferEntity } from '@mikro-orm/core';
export const User = defineEntity({
name: 'User',
tableName: 'user',
properties: (p) => ({
id: p.integer().primary().autoincrement(),
name: p.string(),
email: p.string().unique(),
bio: p.string().nullable(true).default(null),
}),
});
export type IUser = InferEntity<typeof User>;
```
`IUser` will be inferred as:
```ts
type IUser = {
id: number;
name: string;
email: string;
bio: string & {
[__optional]?: 1;
};
}
```
With the improved brand type, `IUser` will be inferred as:
```ts
type IUser = {
id: number;
name: string;
email: string;
bio: string & Opt.Brand;
}
```

fix(typings): enhance branded type definitions for `Opt`, `Hidden`, `Config` and `RequiredNullable`

---

packages/core/src/entity/defineEntity.ts
tests/defineEntity.test.ts

As mentioned in [this discussion](https://github.com/mikro-orm/mikro-orm/discussions/6865), `somePk: p.bigint().primary().autoincrement()` should be optional when creating an entity.
This PR fixes this issue, so any property marked with `.autoincrement()` will be optional when creating an entity via `em.create(...)`.

fix(defineEntity): update autoincrement method to return Opt<Value>
